### ISSUE TITLE
Does this enable sharing deeplinks?

### ISSUE THREAD

**Issue by loganpowell** [faceyspacey/redux-first-router#10]
If dependent on a Redux store/state to handle URLs, what happens when you try to share a deep link with a friend? How do they pick up the state to reflect the position in the app you shared?

Forgive me if this is a naive question...

**Comment by faceyspacey** [comment]
u read the RN docs?

https://github.com/faceyspacey/redux-first-router/blob/master/docs/react-native.md

basically u get the URL the app was opened with, *and then start your app*:

```js
Linking.getInitialURL().then(startApp)
```
...in the last 2-3 versions of RN you dont need to call `registerComponent` immediately. You can do so in response to a promise (specifically the `getInitialUrl`). 

Previously u would have to start your app with path, say, `/`, and then dispatch an additional action once u received the URL from `getInitialUrl`. So if you have an existing app, that may be the quickest way to do it. In that case, just call `push(path)` after stripping the domain etc from the URL (that's actually wrong in the RN doc i linked to u.

```js
Linking.addEventListener('url', ({ url }) => push(url))
```

...thats actually wrong, i gotta normalize the URL to the path before pushing. But hopefully it's starting to make sense. Try to start your app the way I mentioned though. Make sure u have the latest version of RN to do so.

**Comment by faceyspacey** [comment]
...also note, that promise returning the initial URL is super quick. maybe 50ms. i forget.

**Comment by faceyspacey** [comment]
also by the way, all im doing going forward is using this for RN. I'm basically exclusively doing RN work for the next few months. So expect RN to be the absolute top priority, lots of support from me etc.

**Comment by faceyspacey** [comment]
specifically React Navigation. ...if ur using React Navigation, ur gonna love this setup. There is in fact a React Navigation boilerplate linked in the docs page i linked above. U may be very intrigued by that. Using this with React Navigation is the primary focus for me. It already works stunningly. Tests, flow + cleanup are coming. Let me know how it goes if u give the boilerplate a spin.

**Comment by loganpowell** [comment]
Thank you for the quick and thorough response!! Great to hear you're driving hard on the RN side. Will the features translate over pretty seamlessly to React web?

**Comment by faceyspacey** [comment]
When React Navigation comes to web, definitely!

**Comment by faceyspacey** [comment]
you ever put this to use in RN?
