### ISSUE TITLE
2 specials use cases : Pinterest modals & infinite scroll seo friendly

### ISSUE THREAD

**Issue by Vincz** [faceyspacey/redux-first-router#102]
Hey! First of all... Thank you for the great great job. I discovered your work recently and I really like your approach. I still have two use cases that I don't know how to implement based on what I read (and the full actions approach).

1) I was wondering how it would be possible with RFR to implement something like that: 
https://reacttraining.com/react-router/web/example/modal-gallery 
Same url but the component (page) doesn't display the same way (normal or modal) if it the first hit or not (and we would also have to keep the old page to display it at the "background" of the modal.

2) The second would be to do something like this : http://scrollsample.appspot.com/items 
As you scroll, the url get updated based on the scroll. This way, if you reload the browser at some point, you stay on the page you were viewing. It would involve updating the url without triggering the action / routing / thunk ... 

Many thanks !

**Comment by faceyspacey** [comment]
1. is more than doable. you have `state.location.prev` to get the previous location from state. Or from actions you can do: `action.meta.location.prev`. In addition, you also have any state generated from having visited the landing page or gallery. You have to think Redux is powerful, and Redux has been informed of all routes/urls/actions that have been visited. So you can store any state you need in reducers. And then display any views based on that. So for your use case, it's just a matter of how simplify we can solve it: do we simply analyze the current action's `prev` key, *or* do we get a bit fancier and have some reducers record state, which you can then use to make these decisions. 

2. For the scrolling things, if you can get a hook that is called at each section, you can simply dispatch an action. You don't need to worry about the page changing or anything--it's just actions being dispatched. It's up to you what you do with them in your reducers. So basically only on initial load of the app in `componentDidMount` somewhere do you want to trigger the auto-scroll based on this state. Then as the user navigates the app, you dispatch the actions and record the state, but the state is never used. This way scrolling doesn't become janky. There likely is a few ways to refine the approach, but this idea should set the initial path toward solving this.

Glad you like it brotha!

**Comment by faceyspacey** [comment]
Ima close this, but let me know if there's anything else I can do for you.

**Comment by Vincz** [comment]
You were right. That was really easy to implement :) Thank you! I'll send a PR with the example.
I'm about to start a long project with your stack and I was wondering what would be the best repository to start and which one do you intend to keep up to date the most ? redux-first-router-demo ? redux-first-router-boilerplate ? universal-demo ? I need a repository I can check every week to keep my own up to date with the latest releases. Thanks again for your amazing work.

**Comment by faceyspacey** [comment]
The RFR demo.
