### ISSUE TITLE
Suggestion: one place only in the payload for `query` object

### ISSUE THREAD

**Issue by gouegd** [faceyspacey/redux-first-router#105]
Hi fellows !

Currently in a RFR action, the `query` can be passed onto `action.payload.query`, `action.meta.query` or `action.query`.

That means both RFR internals and any user-made middlewares that wants to do something with it, need to look for the query in those several places.
Also it leaves some uncertainty on what's going to happen if the query is provided in several places at the same time (we don't have a single source of truth).

For simplicity and maintainability I suggest sticking to one of those only.
One option is to leave the choice to the user via options, like it's done currently for the `location` key in the redux state.
Or just plainly decide which to use.

`action.query` has the disadvantage to not be redux-actions compliant (too popular to ignore ?)
`action.payload.query` has the disadvantage that something will probably go wrong if a user has a path parameter named `query` (we can mitigate a bit by advertising to not do that...)
`action.meta.query` usually takes a few more chars to type. No big deal I think, though.

I'm throwing this idea because I saw there's one breaking change coming on `onBeforeAction` etc callbacks, so if we ever do this, it's best to do it before a v1 (yes, this is a breaking change too).

How do you think ? :)

**Comment by faceyspacey** [comment]
i think if i had to choose, i'd choose .payload. This is something we can consider for sure. I'll look into it again. 

The main thing is probably on the bottom here where we put it on the `meta` in order to not make any possibly breaking assumptions on people's payloads or actions:

https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/pathToAction.js

**Comment by faceyspacey** [comment]
im thinking just limiting it to `action.payload.query` is the way to go.

You interested in doing a PR? 

We would need to update the link component as well as the docs:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/query-strings.md

and remove the tests that break as a result of it being removed (i.e. tests for meta.query and action.query).

**Comment by gouegd** [comment]
OK, I'll try to get on this in the next few days.

**Comment by faceyspacey** [comment]
ima close this, we know what needs to be done. this is the right move. action.payload.query only. who cares if it's a reserved keyword, it's not that time-consuming to change, plus RFR is new enough that people will know what they are getting into and won't choose that keyword.
