### ISSUE TITLE
Question about using thunk with Firebase

### ISSUE THREAD

**Issue by kevando** [faceyspacey/redux-first-router#107]
I know this question might be a bit outside the scope of this repo, but I am using the redux-first-router with Thunk and this Firebase package https://github.com/prescottprue/react-redux-firebase

However, when I try to use routesMap to get firebase from state, it is not defined yet. I'm having trouble figuring out if I need additional configuration to make this work. Here is my code and the console output:

``` javascript
export const routesMap = {
[ROUTE_ABOUT]: {
    path: '/about',
    thunk: (dispatch, getState, getFirebase) => {
      console.log(getFirebase)
      console.log(getState())
    }
  },
// ....
```

[Console Output](https://i.imgur.com/v5XKhmZ.png)
getFirebase is undefined and firebase from state does not seem to be initialized yet. I am able to call firebase from both locations in my components.

**Comment by faceyspacey** [comment]
Check the top of the readme. There is info about how to provide a 3rd argument. It's not handled by the `redux-thunk` package. You have to specify it here as the `extra` option to `connectRoutes`. You also have to be using the latest @next version of the package (`yarn upgrade redux-first-router@next`). This feature was added just a few days ago. Check the top of the readme :)

**Comment by kevando** [comment]
Mucho Gracias
