### ISSUE TITLE
Optionally Skip Number Parsing on Route Params

### ISSUE THREAD

**Issue by sdougbrown** [faceyspacey/redux-first-router#109]
https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/pathToAction.js#L49

`fromPath` won't run if the param is a number.  For 99% of cases this probably makes sense, but for something like a search terms parameter this won't work.  (e.g. `/search/007` results in a payload of `int 7`)

Are you open to an option on the routeMap that bypasses this check?  Happy to implement if so.

**Comment by faceyspacey** [comment]
Whatup brother. I'm gonna change this when it becomes Rudy. No need for a pr, but appreciate the proactiveness. I already refactored the code to make it a 5 minute change. But unfortunately it's too big a change to go in the current next releases. We need those to work without breaking things for people. Feel free to fork u too then.

Another issue is I actually haven't even pushed the next distributions to GitHub. They only exist on npm. So u would be working with old code. I'm gonna push it soon tho.

**Comment by faceyspacey** [comment]
this is done and on @rudy on NPM :)
