### ISSUE TITLE
Using hash history instead of browser history?

### ISSUE THREAD

**Issue by chanand** [faceyspacey/redux-first-router#114]
On previous versions we were able to pass a hash history to the `connectRoutes` function, like:

```
const history = createHashHistory()

export const {reducer, middleware, enhancer} = connectRoutes(
  history,
  routesMap,
  options
)
```
It seems like now, with history handled internally, there is no way to use hash history anymore, is that correct and intended?

**Comment by faceyspacey** [comment]
It's intended. Since ur bringing it up I'm not sure if it's correct :). If that's a problem I think the best solution is to add a createHistory option which takes a factory. That way people can use hash history or forks. But we have to actually call the factory internally now.

**Comment by faceyspacey** [comment]
Thanks for pointing this out.

There is now a `createHistory` option which you can pass the hash history to or your own fork/implementation etc. Eg:

```js
import createHashHistory from 'history/createHashHistory'

connectRoutes(routesMap, { createHistory: createHashHistory })
```

**Comment by faceyspacey** [comment]
Also, just fyi, it's only currently on the `@rudy` tag on NPM. so do `yarn upgrade redux-first-router@rudy`

**Comment by faceyspacey** [comment]
@chanand out of curiosity why are you choosing to use memory history? Are there any reasons outside of fallbacks to use hash history? 

It seems as far as SSR, it would pose some additional challenges. Basically in that case you have to determine the would-be path based on the hash and pass that to `createMemoryHistory`. 

Also, the hash history doesn't work when pressing the back/next buttons in firefox without reloads.

I'm trying to determine if some automatic fallback to hash history in some cases might be of use to us. I'm currently thinking of just falling back to memoryHistory. I'm not a fan of forced reloads. My current thinking is that there's more value in just keeping the app running smoothly than letting a small percentage of users have URLs to hang on to.

**Comment by chanand** [comment]
@faceyspacey I'm using the hash history because I'm deploying a single page app (with no SSR) while I have no control on the hosting server.

**Comment by schmidsi** [comment]
We're using `hashHistory` because we deploy to [ipfs](https://ipfs.io/). So we have no control over the root, but also, serverside rendering is not even an option.

**Comment by deepfriedbrain** [comment]
Is there any example or documentation on using hashHistory?

My application doesn't have any use for SSR. It interacts with a Java-based server side application through REST APIs. The content on the client side is very dynamic resulting in thousands of unique URLs. I do not need to generate a new request for each behind a user login. hashHistory is a better fit than regular browserHistory. 

I'm trying to use the @latest npm version.
