### ISSUE TITLE
[Question] Recommendation for nested routes?

### ISSUE THREAD

**Issue by zsherman** [faceyspacey/redux-first-router#120]
Just came across this library, thanks for the great work @faceyspacey! I was just wondering if there are best practices recommended for nested routes and the associated data fetching. I come across this all the time in real apps but notice none of the examples have it. For instance you might have a tree that looks like:

```
<TeamRoute>
  <ProjectRoute>
    <ItemRoute />
  </ProjectRoute>
</TeamRoute>
```

**Comment by faceyspacey** [comment]
You deal with it differently with RFR. You have to think every URL accessed Redux has complete info about it. So it's up to you to mold the state into what you need. There's no concept of route components where `/path` and `/path/:param` are both displayed for the URL `/path/foo`.

Similar with the `thunk` option to your routes, you have 2 routes with the respective paths and can define independent data fetching requirements within it. But both will not be called.

Perhaps what you're looking for is optional path path segments. That's a new feature in the @next and @rudy tags:

https://github.com/faceyspacey/redux-first-router/issues/83#issuecomment-327703226

Make sure to read the top of the RFR readme to see what all the new features are and which tag they're in.

Basically you can define a route path like this `/path/:param?` and its thunk will be called whether :param is present or not.

But again, at the end of the day, redux is powerful, it has access to all URL info that comes in, and in a way that is easy to access from your reducers (i.e. you can switch over route types). So it's up to you to generate the state you need to show what you want in your components. So for example you may have `/team` and `/team/project/:id`. Then you can have a `projectId` reducer, a `modelsHash` reducer and a `projectList` reducer. The `modelsHash` state has a normalized hash of al your models (they can be projects, users, or any other model, all in the same hash), with their IDs as keys (or slugs if you want better SEO). Then `projectList` has an array of those ids/slugs. And `projectId` (or `projectSlug`) has the current id/slug. Then you have a selector that will take an id or slug and key into the has to get a single model. Or if you want the array of models, you do the same but map through them. Anyway, for your example, you take the selector that returns the project model and if its truthy you display `<ProjectRoute />`. When the user is on another route that wont have a `<ProjectRoute />` component, you set `projectId` to null. 

It all boils down to being savvy with redux. Anything you can do with Redux you can do. All the information you need passes through. You have complete control.

**Comment by faceyspacey** [comment]
ima close this, but let me know if you need any more assistance.

**Comment by zsherman** [comment]
Gotcha, thanks for the thorough response @faceyspacey I'm going to replace react-router shortly and will let you know how it goes 👍

**Comment by Grsmto** [comment]
I'm just starting with RFR and I'm setting up some static nested routes. If you follow what's suggested here you'll end-up writing extra logic that you don't need if your routing has only static routes:
> projectList is a reducer and has an array of ids/slugs
It means you will have to make sure the `/team/project/:id` is a project that exists and do some filtering in your reducer which kinda should be the job of `RoutesMap` imo.
So my suggestion is that you could keep that logic be handled by RFR and do something like this in your `RoutesMap`:
```
const projectList = ['project-1', 'project-2', 'another-project'].join('|');

PROJECTS: {
    path: `/team/project/:id(${projectList})?`
}
```

The route matching algorithm is powerful enough to support this so RFR will automatically redirect to /not-found if the project doesn't exist.
Of course this idea only works if your project lists is defined statically (not loaded from an API...) otherwise doing that in the reducer probably makes more sense.
