### ISSUE TITLE
Server-Rendering docs - where is `thunk`?

### ISSUE THREAD

**Issue by eudaimos** [faceyspacey/redux-first-router#13]
@faceyspacey first I want to say fantastic work on all of your libs for react + ssr + code splitting - doing myself a deep-deep dive the last several days to get something correctly started, and I came across all of your stuff today and it's been a godsend.

I have a question and a comment about the [server-rendering](../blob/master/docs/server-rendering.md) docs.

**Question**
In _configureStore.js_ you make the inline comment
```javascript
// notice `thunk`
```
but don't do anything with `thunk` in that file. (this would normally fail eslinting)

In _serverRender.js_ you have the line
```javascript
await thunk(store) // THE WORK: if there is a thunk for current route, it will be awaited here
```
but I don't see `thunk` imported or declared anywhere.

Can you please provide more explicit clarity on what to do with `thunk` returned from `connectRoutes(…)` as well as how to retreive it for calling in `serverRender.js`?

**Comment**
In _serverRender.js_, it is **not** idiomatic to send redirects which should result in `HTTP 404` (aka `NOT_FOUND`).  Redirecting may be what's needed client-side as there's no way to provide a 404 in an SPA, but according to the HTTP spec and what Google bot expects, the server should always return a 404 when a path does not match a resource on the server.

**Comment by faceyspacey** [comment]
...crap, before launched i broke up that example code into multiple "files" and `thunk` isn't assigned in `serverRender.js`. I'm gonna fix what u pointed out. Thanks for pointing that out. 

...regarding ur comment, are you saying, you want a "fail whale" style message on the ***same incorrect URL*** that was accessed (i commented this possibility in the doc)?
 
Or are you saying to call `res.redirect(404, '/unavailable)`--I dont even know if that works.

I usually do the first option or I often take the user to the homepage or something if they enter an invalid URL. And ur saying not to do that. Are there any real ramifications to this? I always just figured it assigned more link juice to the homepage if people pasted bad/outdated links to ur site across the web. That's my thinking.

**Comment by faceyspacey** [comment]
So instead of this:

```js
if (type === NOT_FOUND) {
    return res.redirect(302, '/unavailable') 
    // note: another option is to render the same URL, but with a "fail whale"
    // in that case, use `locationState.type === NOT_FOUND` to render something
    // different, and perform no interception here
  }
```

u want this:

```js
  let status = 200

  if (type === NOT_FOUND) {
    status = 404
  }
  else if (kind === 'redirect') {
    return res.redirect(302, pathname) 
  }

  
  const app = ReactDOM.renderToString(<Provider store={store}><App /></Provider>)
  const state = serialize(store.getState())
  const html = ReactDOM.renderToStaticMarkup(<Html app={app} state={state} />)
  
  res.status(status).send(`<!DOCTYPE html>${html}`)
```

at which point, it's up to your React component tree to render a FAIL WHALE graphic or similar if it detects `state.location.type === NOT_FOUND`?

**Comment by faceyspacey** [comment]
i updated the docs with the fix to the thunk issue:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/server-rendering.md

**Comment by eudaimos** [comment]
awesome response time @faceyspacey !!!

Yes, for the 404, the second example is what's expected as a standard, and again what googlebot expects (which is the point if I'm not mistaken of SSR in the first place - besides a better user experience with immediately rendered first page)

Fail Whale is different (and confusing to be used here) as that was representing HTTP 500 error (Server Error), not a 404 (Not Found) - hope that helps

**Comment by faceyspacey** [comment]
...ok, so i'll put that in the doc instead since that raises less eye brows. 

i often just redirect cuz i want the user to see a primary landing page rather than "nothing is here" page. i've doing that for a very long time lol. i just checked several top sites, and they're all doing it like u said, and like github. i coulda sworn other sites do redirects to topical pages. i wonder if there are any penalties for this. i never noticed any...

> yea maybe im getting terminology wrong with fail whale. i just mean a page with a graphic saying the page doesnt exist. a 404 page essentially.

**Comment by eudaimos** [comment]
Also wanted to say, and forgot in my initial post, that this reminds me of the State Router in Angular 1.x which I always thought was a better way to manage an app.  The URL should reflect the current state of the app, not drive it, and all links/transitions occur by pushing state.  The URL is just one form of state serialization that allows it to be shared and bookmarked.

I believe this also can fix my outstanding issue with regards to having a singular routing pattern for client-side and server-side as what I really desire client-side is to fetch the data then transition the UI (changing the URL) since the result of the data fetch may determine a different location in the app, but in order to make ssr work, the route is needed first to inform the server what data to retrieve.  To make SSR work in the past, the client pattern had to follow the same as the server, but with this, it's possible to have both with the same code.  Well done, sir.

**Comment by eudaimos** [comment]
Funny 404 pages are great, and there are certainly better examples out there, but should reflect the fact that the requested resource essentially does not exist.  Redirecting confuses the browser into thinking the requested resource was moved.

**Comment by faceyspacey** [comment]
404 is now updated in the docs as well:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/server-rendering.md

let em know if there was anything i missed. ..honestly i had a sneaking suspicion that what i was teaching/showing here was not what i should be. so thanks for pointing this out early on.

**Comment by eudaimos** [comment]
@faceyspacey thanks for updating so quickly with the `thunk` clarity.  So if I understand it correctly, the call to bootstrap the redux store essentially initiates fetching the data from any matching "routes"/actions triggered by the current location - I understand the effect of this on the server, but what are the affects to this client-side?

**Comment by faceyspacey** [comment]
so client side a `thunk` if available is automatically called whenever u change routes. with one exception: ON PAGE LOAD *IF U HAVE SSR*. 

How does RFR know if u have SSR?
Well, the server adds a `state.location.hasSSR === true` to the serialized state u send over the wire. Then on the client, if `state.location.kind === 'load'`, it does not execute the thunk again :)

If it's detect that ur not using SSR, it will call the thunk even on load. 

So from the client's perspective it's fully automatic. On the server, since Redux middleware is not asynchronous, u gotta write one extract line calling `await thunk(store)`. 

I could possibly remove the need for that line, but u'd have to await somewhere. E.g: `await customCreateStore()`. And I'd provide a thin wrapper over createStore. I think what i have is more explicit, and lets you determine if u want to await other async dispatches before or after it or both :)

**Comment by eudaimos** [comment]
Awesome @faceyspacey . This really is great stuff. Would you mind stating that in the doc page so this issue doesn't have to be referenced?

I'll go ahead and close this issue since my original question has been answered

**Comment by faceyspacey** [comment]
yea, there are clues about it, but it def could be better said

**Comment by faceyspacey** [comment]
@eudaimos you're gonna love the latest update to the Demo:

https://github.com/faceyspacey/redux-first-router-demo

It's major. It includes lots of authentication filtering stuff. It has SSR + Code Splitting. There's also updates to this package. So update your deps. The takeaway is redirect in `onBeforeChange` if not authenticated.
