### ISSUE TITLE
SSR initialEntries payload type casting

### ISSUE THREAD

**Issue by primozs** [faceyspacey/redux-first-router#132]
SSR initialEntries initial entry is '/someroute/691950721070799378'

location object becomes:
because the number is too big id is casted wrong.
```
location: {
    hasSSR : true,
    history : undefined ,
    kind : "load",
      pathname : "/someroute/691950721070799378",
     payload : {
      id :  691950721070799400
    }
}
```
Could I somehow specify how SSR initial route parameters should be casted. Or it should be just string by default?
I am using rudy version.

**Comment by faceyspacey** [comment]
Use the toPath and fromPath route options. Check the connectRoutes docs in the docs folder of this repo.

**Comment by primozs** [comment]
Great! thank you!
