### ISSUE TITLE
Handle route index

### ISSUE THREAD

**Issue by bultas** [faceyspacey/redux-first-router#134]
Hi, 

for the first I would like thank for this lib. is really something what I was looking for. 

for the second I have question about having index of some folder path:

For example now I have to have two routes where I use same thunk and same component:

```
'locationA': '/p/:id',
'locationB: '/p/:id/:section'
```

but I would like to define just one route

`'location: '/p/:id/:section'`

which handle `p/123/` in same way as `p/123/section` because I don't want to do request or do another actions in thunk every time when somebody go from location A to B.. because is very same application under these routes.

Solution for this can be folder index for example:
1. `/folder`
2. `/folder/`
3. `/folder/:section`

where 2 a 3 can be handled by one route. And in 2 case you will receive section parametr as empty string..

Or do you have another opinion/solution for this?

Thanks

**Comment by faceyspacey** [comment]
this will do it for you:

`/p/:id/:section?`

:section is optional. your thunk just needs to have the logic to deal with both cases :)

**Comment by bultas** [comment]
Works like a charm.. Thank you.
