### ISSUE TITLE
SEO URL generation

### ISSUE THREAD

**Issue by jackwilsdon** [faceyspacey/redux-first-router#138]
What's the best way to go about generating SEO URLs from just an ID? An example would be redirecting `/categories/1` to `/categories/1/my-category-name`.

I can do it in the `thunk` option for the route, but that causes a flash in the URL without the `/my-category-name` suffix. Is there a better way to do this?

**Comment by faceyspacey** [comment]
The best and typical way is to store a `slug` field in each database table, and then use that to find models instead of the ID #. That's what people serious about SEO do. They forgo using ID numbers altogether :)

That also saves you from doing redirects.
