### ISSUE TITLE
Only getting NOT_FOUND actions and could-not-create-path-from-action errors.

### ISSUE THREAD

**Issue by waynebloss** [faceyspacey/redux-first-router#144]
Hello, I added rfr to my project but it doesn't seem to do anything except fire off `@@redux-first-router/NOT_FOUND` whenever I change the address-bar. The `Link` component from `redux-first-router-link` also complains that it "could not create path from action: `{type: "DASH"}` if I use the object form.

Everything seems pretty straightforward, and I'm sure that I followed the directions but I'm also using a new (rudy) version as mentioned below. I think I understand how this library is supposed to work: It listens for location changes and it's supposed to dispatch the action matching the current path.

Here's my `routeMaps` object:

```js
const routesMap = {
  HOME: '/',
  DASH: '/dashboard',
  USERS: '/users',
};
```

Here's my `createStore` (basically):

```js
    const rudy = connectRoutes(routesMap); // updated, removed history.
    
    const reducers = getAReducerObjectFromStuff();
    reducers.location = rudy.reducer;

    const rootReducer = combineReducers(reducers);
    const middleware = applyMiddleware(logger, rudy.middleware); // (basically)
    const enhancedMiddleware = compose(rudy.enhancer,/* autoRehydrate(), */middleware);
    const store = createStore(rootReducer, preloadedState, enhancedMiddleware);
   persistStore(store);
   return store;
```
And my reducer, which only ever gets called with `NOT_FOUND`:

```js
  function reducer(state = null, action) {
    console.log('reducer called with state, action', state, action);
    switch(action.type) {
      case 'HOME':
      case 'NOT_FOUND':
      case 'USERS':
        return null;
      default:
        return state;
    }
  }
```

Here are my dependency versions. I went with the latest versions. Was that a mistake?

```json
  "dependencies": {
    "prop-types": "^15.5.0",
    "react": "15.6.2",
    "react-bootstrap": "0.31.3",
    "react-dom": "15.6.2",
    "react-overlays": "^0.8.2",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-first-router": "0.0.4-rudy",
    "redux-first-router-link": "0.0.2-rudy",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.10.1",
    "rudy-history": "1.0.0"
  },
```

UPDATE: I followed the updates in your readme and stopped passing history to connectRoutes.

**Comment by waynebloss** [comment]
[Link](https://github.com/faceyspacey/redux-first-router-link/blob/64510c1e954d4139143d48f0bdff0bf5b1e8d83d/src/toUrl.js#L22) swallows errors there. You should print it in the warning IMO.

I assumed that it was happening because I didn't pass in a querySerializer so I tried that too but no luck. I will see if I can get the actual error there, maybe that will help me figure out the rest.

**Comment by waynebloss** [comment]
The error causing the "could not create path" warning is: `"Cannot read property 'length' of undefined"`.

Turns out, you MUST pass a `querySerializer` option to connectRoutes. Once I did that, everything worked.

**Comment by waynebloss** [comment]
This was frustrating. I actually stayed up way too late hacking on this!

I guess I'll just close this issue now and hopefully other users will find the solution here. It would be nice if the README were updated. I'll let you split this out into separate issues if you want to. Thanks for your work.

**Comment by faceyspacey** [comment]
you don't have to pass the `querySerializer` option. Perhaps it's a bug in the latest rudy version, but I really i don't think so. 

If you're new to RFR, you likely want to use what's on master to avoid these problems. Either way, good luck, thanks for joining us.

**Comment by waynebloss** [comment]
@faceyspacey I have a very simple setup and if I don't pass `querySerializer`, I get errors.

Debugging in chrome, I put a breakpoint on the line with the console warning in toUrl.js file. When I don't pass  `querySerializer`, that breakpoint gets hit and the `e` error says `"Cannot read property 'length' of undefined"`.

I can repro this if you want. I'll do it later today.

**Comment by faceyspacey** [comment]
I won't have time my friend, I'm working on a the next release which will be the biggest release to date, and as a result a lot of these problems will solve themselves. My best recommendation is to use the standard version npm provides rather than `@rudy` if these problems are causing you pain. But rest assured they will be resolved shortly.

**Comment by waynebloss** [comment]
OK, no problem. Thanks for saving me the work!

I got it working now and I know what to do to fix my 2 problems, so no biggie.

**Comment by SimplySeth** [comment]
@waynebloss  share your secret ...

**Comment by waynebloss** [comment]
@SimplySeth The main issue was solved by simply passing the `querySerializer` to RFR. I stopped using `redux-first-router` though because I had too many problems with it and it looks like nobody is developing/maintaining it anymore.

**Comment by Alevale** [comment]
@waynebloss This is 5 years later, but I'm in the same path as you, what did you use instead, and how painful was it to change it?

**Comment by ghost** [comment]
@Alevale I don't even use Redux anymore in my projects, instead I'm using `valtio` - https://github.com/pmndrs/valtio

For routing in an SPA I always use `react-router-dom` - https://reactrouter.com/en/main/start/tutorial

It doesn't matter where the state comes from with react-router. You just use the state to configure the routes or to conditionally render them. (That tutorial for react-router also uses `vite` to build the app instead of `create-react-app` which I think is a good choice because it is faster, more flexible and it has fewer issues.)

If you're making a react SSR app and using something like Next.js, they have their own router.
