### ISSUE TITLE
Dispatching redirect with optional params in onBeforeChange doesn't change URL on initial load

### ISSUE THREAD

**Issue by NicholasGWK** [faceyspacey/redux-first-router#146]
Hey, I've got another scenario where I'm trying to prefix all my URLs with a /region/language code, but want it to be dynamic so stayed away from baseName. I covered most of the cases with Link by just injecting them, but I'm lost on fixing the case where the user initially loads a URL without including the params ( I have them as optional to catch this case).

IE for the route `HOME: /:region?(ca)/:language(en)? I would expect navigating to `localhost:3000` to redirect to `localhost:3000/ca/en.

To accomplish this, I check if region/language exist on the payload, and if not dispatch a redirect with those filled in with defaults. For all subsequent links/dispatches, I just use the ones already set in state, that way it's impossible for the user to be on the site without these being defined.

However, the redirect is dispatched from onBeforeChange as expected, but doesn't update the params. If I dispatch another action with the same values, the params update as expected, so I'm unsure if it's something related to the initial load.

I made a repro here...in console you can see the region is undefined, then set to ca with a direct action, but the URL doesn't update:

https://codesandbox.io/s/w6x3q2o0z5

Any help or comments on if what I'm attempting makes no sense would be appreacited!

**Comment by NicholasGWK** [comment]
Got it! I was expanding the entire action in the redirect with `...action` forgetting it's including a bunch of the meta and messing things up. When I just used the type and appended to the payload, works like a charm!

**Comment by faceyspacey** [comment]
Excellent. FYI in the very soon you will be able to update the basename with an action creator FYI, for your exact purpose.

**Comment by NicholasGWK** [comment]
Amazing! Looking forward to it + the rudy release, thanks for such a great library. Will probably go with this for now and update when that's available 👍
