### ISSUE TITLE
Dynamically adding routes with 'addRoutes' doesn`t work when server-side rendering.

### ISSUE THREAD

**Issue by rcalabro** [faceyspacey/redux-first-router#155]
Hi! 

Using a redux-first-router-demo clone

I am experimenting with **redux-first-router@next**, and trying to implement the strategy for dynamically adding routes form split modules from #62, where you suggest the following:

```
import { addRoutes } from 'redux-first-router'
import universal from 'react-universal-component'

const UniversalComponent = universal(props => import(`./${props.page}`), {
   onLoad: module => {
       const aThunk = addRoutes(module.newRoutes)
       store.dispatch(aThunk)
   } 
})
```

I have a very similar setup where I am adding a single route
```
export default {
  ABOUT: '/about'
}
```
I just added the component tp the same folder as the others and the component name on **page reducer** temporarily, so I don`t have to worry loading a new reducer now.
```
const components = {
  HOME: 'Home',
  LIST: 'List',
  VIDEO: 'Video',
  ADMIN: 'Admin',
  LOGIN: 'Login',
  ABOUT: 'About',
  [NOT_FOUND]: 'NotFound'
}
```

When I go to '/' (Home) and the use a redux-first-router-link to navigate to /about, it works perfectly.

The issue happens when I access http://localhost:3000/about directly.

What I got so far:

The first thing executed is the routing, and the first action dispatched is:
`action @@redux-first-router/NOT_FOUND`
but the routesMap is not updated yet

from state:
```
routesMap: 
        { HOME: '/',
          LIST: [Object],
          VIDEO: [Object],
          PLAY: [Object],
          LOGIN: '/login',
          ADMIN: [Object] }
```

Right after that the App module `onLoad` is triggered and the routesMap is uptaded correctly, but I I have NotFound already rendered.

```
universal onLoad: App
action @@redux-first-router/ADD_ROUTES
```

from state:
```
routesMap: 
        { HOME: '/',
          LIST: [Object],
          VIDEO: [Object],
          PLAY: [Object],
          LOGIN: '/login',
          ADMIN: [Object],
          ABOUT: '/about' }
```

I am doing something wrong ? Any ideias how to setup the correctly?

Thanks!

**Comment by faceyspacey** [comment]
This is something I'm working on improving in the upcoming Rudy stuff. A quick fix probably would be to discover the routes you need to add before rendering on the server, and then dispatch `ADD_ROUTES` before render. I know that takes away from the *component-level* capabilities of *universal component*, but for universal apps, it's likely not going to work as-is if you're adding routes on the same route where they are needed.

This sorta stuff is basically really fresh stuff in the React game I'm just gonna have to make a first-class priority in the upcoming release and get truly right. It's just not there yet. Ultimately, it boils down to a lot of the same problems I've been discussing in my articles: route level vs component level. Component level messes things up for real apps and the result is more and more needs to be pushed to the route level. Component level was a new *ideal*, and makes things very accessible for learners and for simpler apps, but it's not practical for super pro apps that want to take things like code splitting + ssr to the highest level.

The new architecture will take things like this into account and make them very straightforward.

**Comment by rcalabro** [comment]
Nice! I am looking forward to Rudy! Do you have an approx release date?

By now I will go with discovering the routes before rendering on the server. Thanks!

**Comment by faceyspacey** [comment]
i'll be rolling it out over the coming weeks.
