### ISSUE TITLE
Storing functions in state

### ISSUE THREAD

**Issue by luke-j** [faceyspacey/redux-first-router#157]
Great project, thanks for all your work on it.

I've noticed, though, that the entire `routeMap` object is added to state via [the location reducer](https://github.com/faceyspacey/redux-first-router/blob/master/src/reducer/createLocationReducer.js#L36), including `thunks`.

[It's generally accepted](http://redux.js.org/docs/faq/OrganizingState.html#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state) as less-than-best practice to have an unserialisable state. Including functions in state is one way state can be unserialisable.

One solution to this would be to refactor the location reducer into something like:
```js
const query = action.meta.location.current.query
const search = action.meta.location.current.search

return {
  pathname: action.meta.location.current.pathname,
  type: action.type,
  payload: { ...action.payload },
  ...(query && { query, search }),
  prev: action.meta.location.prev,
  kind: action.meta.location.kind,
  history: action.meta.location.history,
  hasSSR: state.hasSSR,
  routesMap: Object.keys(routesMap).reduce((obj, key) => {
    const { thunk, ...map } = routesMap[key];
    obj[key] = map;
    return obj;
  }, {});
}
```
but I'm not sure if this would cause any unintended side effects. Do you have any thoughts on this?

**Comment by faceyspacey** [comment]
Glad you like the project. 

As far is this issue goes, the routesMap is re-added on the client after SSR, since as you pointed out, it's not serializeable. Everything works fine with it.

My personal gripe with it is it makes looking snapshots in wallaby longer and harder to read. I'm gonna close this, but in the next version I may find a way to remove it.
