### ISSUE TITLE
Having trouble using RFR thunk feature with Bearer Token Authentication (redux-oauth)

### ISSUE THREAD

**Issue by pineapplethief** [faceyspacey/redux-first-router#158]
Ok, here is the problem: Bearer Token Auth basically require to append auth headers to each request to the API, problem is: on first load route actions dispatch BEFORE auth bootstrap, which takes headers from cookies and validates auth token via API /validate_token endpoint. Here is a bit from my index.js:
```
document.addEventListener('DOMContentLoaded', () => {
  store.dispatch(initialize(reduxAuthConfig))
    .then(store.dispatch(fetchFirstLaunch()))
    .then(() => {
      render(App)
    })
})
```
But route actions and corresponding thunks dispatch independently way before this code executes, so any requests to my API fail since redux-oauth expects headers to be already present in my redux state.
I'd guess I need somehow to chain router bootstrapping to happen sequentially before that last `then`, but have no clue how I'd make this happen, spent several hours banging my head at the problem already. It would nice to get some high-level advice

**Comment by faceyspacey** [comment]
pass `initialDispatch: false` in your `options` to `connectRoutes`, and then you will be returned a function called `initialDispatch` along with the `enhancer`, `reducer`, etc. You can then dispatch that when you're ready :)

**Comment by faceyspacey** [comment]
https://github.com/faceyspacey/redux-first-router/blob/master/docs/connectRoutes.md#options
