### ISSUE TITLE
Incompatibility with redux-localstorage

### ISSUE THREAD

**Issue by icopp** [faceyspacey/redux-first-router#160]
Right now, having thunks in the routeMap doesn't work very well for some use cases, because the initial location doesn't get a dispatch. For example, if the user bookmarks a deep URL in a web app, there will never be a dispatch issued for that on the initial page load, so thunks and other store-dependent things won't get triggered.

**Comment by faceyspacey** [comment]
Make sure your enhancers and middleware are in the correct order. My suggestion is to stick as close to the boilerplate and demo as possible until you got it running smoothly.

**Comment by icopp** [comment]
It looks like I got bit by an issue similar to #151, with a combination of `composeWithDevTools` from `redux-devtools-extension` and `mergePersistedState` from `redux-localstorage` keeping the first dispatch from happening.

The former I could fix by changing things to the same method as #151 (accessing `window.__REDUX_DEVTOOLS_EXTENSION__`), but I'm still hunting for something to replace `redux-localstorage` that won't break the first dispatch from `redux-first-router`.

**Comment by icopp** [comment]
Some experimenting got things working like I want (I think) with `redux-persist` using (in abbreviated form):

```js
/* store/location.js */
const {
  reducer,
  middleware,
  enhancer,
  initialDispatch
} = connectRoutes(history, routesMap, {
  initialDispatch: false
})
export { middleware, enhancer, initialDispatch }
export default reducer

/* store/index.js */
export const persistor = persistStore(store, {}, () => {
  locationInitialDispatch && locationInitialDispatch()
  // ... other initialization dispatches here
})
```

**Comment by faceyspacey** [comment]
so is it safe to say the `initialDispatch` technique worked and we can close this?

**Comment by icopp** [comment]
Yes, I would say so. Might be useful to stick as a note somewhere for use with v5 (as compared to the current doc's mention of redux-persist v4).
