### ISSUE TITLE
React Navigation support

### ISSUE THREAD

**Issue by scarlz** [faceyspacey/redux-first-router#161]
It's mentioned in the readme that RFR has first class support for React Navigation (and that this support is its crown jewel, no less). Upon reading through the documentation dedicated to RN, however, it seems that neither its documentation, boilerplate or RRFN package itself has been updated in some time.

Is the RN side of this project still being actively developed?

**Comment by faceyspacey** [comment]
Ultimately I found React Navigation not quite ready.

That said, there will be a revisit at some point. The best thing I can say is to give it a try. It was working swimmingly when it was built. It was a real unique solution that solved some real problems when using React Navigation with Redux. One caveat is that it was based on a fork of React Navigation with a few minor PRs, some of which have been merged. That was the main reasons I de-prioritized it. The things that might be problematic are more advanced things like reseting routes, which has been problematic with React Navigation itself.

**Comment by scarlz** [comment]
Ok, thanks for the swift response. At a slight tangent, from your reply, did you ultimately end up dropping React Navigation (in your apps)? I'm aware that you are the author of the popular issue over at React Navigation regarding managing the reset transition animation, which is the issue with which we're primarily stuck with, and for which I'd hoped (out of desperation!) that RFRN may allow us to circumvent.

**Comment by faceyspacey** [comment]
I only used it one small app. Other than that my primary work related to it was preparing it for serious use along with RFR. Ultimately I came to the conclusion that it's just best to wait until its maintainers get farther along with it. 

My best recommendation--and what i had to do--is to fork it and work on their code directly. If you can invest a day into analyzing the source, you may be surprised by how within reach what you want to do is.
