### ISSUE TITLE
Support for defining query parameters as arrays

### ISSUE THREAD

**Issue by rshackleton** [faceyspacey/redux-first-router#164]
When specifying only a single query parameter (i.e. ?years=2017) the value in the `location.query` object will be a string. Whereas if you define multiple parameters (i.e. ?years=2017&years=2016) it will be an array. 

It would be useful if we could specify that the "years" parameter will always be an array to remove some of the superfluous code.

Is there a recommended approach to handling this scenario?

**Comment by faceyspacey** [comment]
In the next version, Rudy, you can supply your own reducer, in which case you could wire it up :). It will be out in a week or 2.

**Comment by faceyspacey** [comment]
also, you can wrap the reducer now like this:

```js
const locationReducer = (state, action) => {
    const nextState = reducer(state, action)
    if (nextState !== state && typeof nextState.query.years === 'string') {
            nextState.query.years = [nextState.query.years]
    }
    return nextState
}
```

...to make it a bit more robust and trigger less re-renderings within your components, you could also check if the previous state had a single value array with the same value, in which case, you do nothing.

**Comment by rshackleton** [comment]
Brilliant, thanks for the quick reply! Especially for the example, I'll be able to clean up some of the components now.
