### ISSUE TITLE
Any chance that you'd remove capitalizedWords and auto parseFloat?

### ISSUE THREAD

**Issue by stevemao** [faceyspacey/redux-first-router#167]
There is a `fromPath` and `toPath` hook that can easily handle these.

In fact, the auto `parseFloat` brings some unexpected behaviours.

**Comment by faceyspacey** [comment]
Why remove the former. Check the source code on the Rudy-next branch, the latter is likely handled.

**Comment by stevemao** [comment]
Sorry, accidentally hit enter without a complete sentence. I'm using the `rudy` on npm (checked rudy-next branch, the looks like `pathToAction` is the same). There's a few reasons:

1. keep the api/core as simple as possible
2. `fromPath` and `toPath` not only provide some transformation, but also stop auto `capitalizedWords` and `parseFloat`. They are doing two seperate things (well arguable related). But I'd just expect them to do transformation.
3. Auto `parseFloat` brings some unexpected behaviour. EG: I have a path `/photos/:id?` `id` is a number and is optional. I have a link in `/photos` page which takes to `/photos/:id?`(a photo) page. when that happens `pathToAction()` is not called again (probably thinks it's the same route?). So the `id` is not auto parsed. But if I refresh, the `id` is parsed. This is actually a bug and is fixable but I feel like you'd add too much logics to handle this edge case.

**Comment by faceyspacey** [comment]
Can u explain more how that second link doesn't work.

**Comment by stevemao** [comment]
My `/photos/:id` and `/photos` are almost the same page, only the content views are slightly different. So I just use `path: /photos/:id?`. `/photos` shows all photos in the content view whereas  `/photos/:id` display a photo with some extra info. when I click on any photo in `/photos` it will display this photo (route changes to `/photos/:id`). in that case the `id` is not parsed (`pathToAction()` is not called at all). so `id` is a string not a number. When I refresh the page here, `pathToAction()` is called and `id` is parsed. So `id` becomes a number.

Hope this makes sense.

If we remove auto parse and `capitalizedWords` this bug is not relevant. Again it's very easy to do these things in `fromPath` and `toPath`. It's more explicit this way too. It's probably easy to wrap it as well so this becomes pluggable. I don't think modules like `react-router` is doing it.

**Comment by faceyspacey** [comment]
I dont understand how `pathToAction` is not called. I'm not getting how it works if you do a refresh, and it doesn't if you just navigate to it (via an action or link). And then I'm not getting how that's related to auto-parse. If it's not being called, that's a problem, and one that seems unrelated to auto parse. 

Also, does this only occur using the link package? Does the problem exist if you manually dispatch the action to a `/photos/:id` route? 

...I'm open to removing `parseFloat` (not capitalizedWords--can't see how that it would be a problem if not used), but let's solve your bug, and circle back to changes to the automation later.

**Comment by stevemao** [comment]
I'll have to create a failing unit test or a simple project that replicates this when I'm free.

**Comment by faceyspacey** [comment]
convertNumbers will be an option in the upcoming Rudy release. so this shouldn't be a problem as both convertNumbers and capitalizeWords won't happen by default.

**Comment by ngbrown** [comment]
`convertNumbers` isn't an option yet.  I hit this because the initial path is converted to an action, and one of the parameters sometimes looks like a number, and other times it has letters in it.  Anyways, when an action is dispatched from a `<Link/>`, then the parameter is always a string, and it forces large portions of the application to reload data because a parameter changed and is no longer `===`.
