### ISSUE TITLE
Match path that contains query parameter '?'

### ISSUE THREAD

**Issue by chongjunhong** [faceyspacey/redux-first-router#169]
Hi guys,

Just a quick question, how can I match a url that contain query parameter with RFR, eg ?name=james.

Thanks!

**Comment by leggomuhgreggo** [comment]
https://github.com/faceyspacey/redux-first-router/blob/master/docs/query-strings.md

**Comment by chongjunhong** [comment]
Please correct me if I am wrong, I don't think It contains the information I want.

A url is constructed on the backend eg. reduxfirstrouter.com/router?name=superman

How to have the routesMap to match the the url?

I have tried /router?name=:name, and it is not working.

**Comment by faceyspacey** [comment]
What you are trying to do is filter what types paths can match by query params. You can't yet do that with RFR. You can only match based on path params. In a future version coming soon you will be able to further filter if the route type matches by the presence of query params and optionally their precise values.  

You can however extract query params as @leggomuhgreggo mentioned.

**Comment by leggomuhgreggo** [comment]
Yeah you can get it from the RFR location key in state

```
// routesMap.js

{
  "ROUTE_ROUTER": {
    path: "/router",
    thunk: async (dispatch, getState) => {
      const { location: query: {name} } = getState();

      if (name === "superman") {
        const action = redirect(supermanAction());
        dispatch(action);
        return;
      }
    }
  },
};
```

but you have to have query string in your options

```
// options.js

import queryString from "query-string";

export default {
  querySerializer: queryString, // this here
  initialDispatch: false,
  onBeforeChange: (dispatch, getState, actionObj) => { ...code... }
}
```

**Comment by chongjunhong** [comment]
@faceyspacey @leggomuhgreggo 

Guys, you know what? You guys are legends.

thanks!
