### ISSUE TITLE
An equivalent to StaticRouter (from react-router v4)?

### ISSUE THREAD

**Issue by hypoalex** [faceyspacey/redux-first-router#170]
Hi,

For server-side rendering, it would be really cool to have something like StaticRouter from React Router v4. See: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/StaticRouter.md

I would feel fairly confident about submitting a PR to add this, if there is any interest. I'm fairly new to React/Redux but this seems like a fairly good idea to me (as does redux-first-router).

Something like this with Koa...

    const routeContext = {};
    const components = (
      <StaticRouter store={ctx.store.router} location={ctx.request.url} context={routeContext}>
        <ApolloProvider store={ctx.store} client={ctx.apollo.client}>
          <App />
        </ApolloProvider>
      </StaticRouter>
    );
    // Wait for GraphQL data to be available in our initial render.
    await getDataFromTree(components);

**Comment by faceyspacey** [comment]
what's the goal though? I can't see it from your example. Just to be able to extract stuff off a context object that was added during rendering? What would be added to it? RFR figures out redirects before you even render based on the route, allowing you to redirect with the proper status code before wasting cycles rendering.

Perhaps what you want is related to how Apollo works with the additional "pre-render" it does. The next version of RFR will have a graphql/Apollo middleware and route-level graphql. Component level graphql and queries is unnecessary and almost nobody actually needs that and benefits from it in anyway. It's been born out of the fact that React has had no abstraction besides components, but I'm willing to bet if you analyze your app you don't need to make decisions on what data to get at the component level, but rather can do it at the route/URL-level.  The benefits to doing it this way are many and outweigh doing it at the component level by far. There just hasn't been any good model-layer-coupled routing abstractions for the React community until Redux-First Router. The next major release, Rudy, will take its overall "controller" concept all the way.

Also what do we actually get from passing `store` and `location` as props to `<StaticRoute />`? The way RFR works is you simply populate your store and use the redux provider.
