### ISSUE TITLE
Docs update - Add Main Page tldr?

### ISSUE THREAD

**Issue by bmoquist** [faceyspacey/redux-first-router#173]
@faceyspacey - Would you be able to add a concise paragraph with bullets on the state of the repo at the top of the main page? 

I've been developing with RFR/Rudy for the last couple months and have loved the experience -- everything has worked really well. Today, I came back to look at the repo changelog/tags/etc. to upgrade to the latest version and found myself somewhat confused by the documentation/branches/npm and direction of the project.

Specifically, would be great to address at the top of the repo main page:
- RFR to Rudy transition: what does this look like? A **very brief** bulleted list of the 3-4 major things in the works for the Rudy release to get everyone on the same page as to where we are going -- by no means does this need to be exhaustive or set in stone. 
- What should RFR/Rudy users be using from where? Specifically, what do I pull for the latest and is there a list of breaking changes/features aside from those listed in your updates (last update on 9/22)? There are four branches - master, next, rudy, and rudy-next. What are each being used for?

Thanks so much for all your hard work on this -- it really shows. I know keeping up docs is a pain, but I'd hate for this project to lose momentum if people are overwhelmed by the first page and can't figure out what's going on.

**Comment by faceyspacey** [comment]
I agree. But I'm focused on the big Rudy release (the code) and will do all that *once* when I'm done :)

Everything available on npm in the additional tags is listed there.
