### ISSUE TITLE
Enhancer loose all the query parameters on first route

### ISSUE THREAD

**Issue by dbertella** [faceyspacey/redux-first-router#174]
I'm experiencing a weird issue, the first url of my app is something like `http://localhost/url?foo=foo&bar=bar`.
If I add the enhancer to my store and the first action is being dispatched I loose all the parameter and my url became just `http://localhost/url`.

My route is defined normally in the routMap as 
```
const routesMap = {
  ROUTE_URL: '/url'
}
```
Do I need to specify further options perhaps?
How can I keep the query parameters in the url using the enhancer?

**Comment by dbertella** [comment]
Never mind I've found out that I was suppose to add the `querySerializer` as a last parameter of my `connectRoutes`, and now everything is working as expected. 
Closing since it works as expected, it might be worthy to have some example though.

**Comment by slavab89** [comment]
Exactly what happen to me now.
Having support for querystring is quite common, no? Shouldnt it be included in the base?

**Comment by faceyspacey** [comment]
It will be in the next version

**Comment by florian-bd** [comment]
@faceyspacey Do you mean it will be handled automatically in the next version?
