### ISSUE TITLE
[Rudy] Not Found redirect breaks via Link when using custom state location & selector

### ISSUE THREAD

**Issue by BrendanFDMoore** [faceyspacey/redux-first-router#175]
This issue arises when you try access an undefined route (via a `Link` from `redux-first-router-link`) with a configuration that places the `redux-first-router` in the store somewhere other than `location` at the root. The custom location selector or path is not honoured when creating not found actions.

Branch/version: `rudy@latest`
Reproduction:
1. Configure your store and root reducer such that the RFR state exists somewhere other than `rootState.location` (ie, place the `reducer` returned from `connectRoutes` at `notlocation`)
2. Provide a custom selector in the `options` to get that slice of state. (eg, `location: state => state.notlocation` in your `options`)
3. Create a menu entry or other link to `/some/fake/path` (which has no route defined)
4. Click that menu entry/link

What I expected: To reach the stub not found component
What happened: Application crashed with error `Cannot read 'pathname' of undefined`
Screenshot:
<img width="944" alt="educator_dashboard" src="https://user-images.githubusercontent.com/4238814/33745614-de115994-db85-11e7-92bb-f6451710e27a.png">

Interestingly, this error does *not* happen if you navigate to the undefined/unrouted path directly via deep link, only via actions in the app. 🤷‍♂️

**Comment by chaucerbao** [comment]
I'm running into the same issue.
```
connectRoutes(history, routesMap, { location: 'routes' })
```

Regular links work fine, but routes that don't exist will throw errors.

![image](https://user-images.githubusercontent.com/794434/36364173-5ab6a8f0-14f7-11e8-96f4-d3d75b2da740.png)

This doesn't happen when using RFR with defaults.
```
connectRoutes(history, routesMap)
```

**Comment by faceyspacey** [comment]
ok, I finally got around to fixing this on the `@rudy` tag on npm. `yarn upgrade redux-first-router@rudy` should do the trick. When you upgrade, double check `node_modules/redux-first-router/package.json` to insure you have version `0.0.5-rudy`.
