### ISSUE TITLE
Versioning & documentation

### ISSUE THREAD

**Issue by schmidsi** [faceyspacey/redux-first-router#180]
I really like this project and the redux first approach, but it was hard to get started because of confusing version & documentation.

So the current version on NPM is: `0.0.16-next`, which is also the documented one in the README on the master branch. I refer to this line:
```
const { reducer, middleware, enhancer } = connectRoutes(history, routesMap) // yes, 3 redux aspects
```

On rudy version, it seems to be like this: 
```
const { reducer, middleware, enhancer }  = connectRoutes(routesMap);
```

Without the history. See https://github.com/faceyspacey/redux-first-router/issues/114#issuecomment-330499555.

But then the updates on top of the readme somehow say, that I should use the `@rudy` version. (What's the meaning of rudy anyway?)

Cross-checking versions with `npm show redux-first-router versions` revealed, that there seems to be different version schemes: 1.x.x, 0.0.x-next and 0.0.x-rudy. Whereas 0.0.1-rudy was deployed after 0.0.20-next.

In the end: I'm confused 😕 .

I'm happy to help with documentation a bit, since I have now a working version, but I need to know which is the future version.

**Comment by skeet70** [comment]
I have pretty similar questions. I'm loving using the router, and we're currently using 0.0.4-`rudy`. I ran into issues as well with the documentation that were resolved by reading issue comments or the code. I've now got an issue with the flow types in `rudy` and I'm not sure if I should submit a PR trying to fix them or upgrade (?) to `rudy-next`.

A bit of version/documentation consolidation would be pretty sweet. I'd also be glad to help out if given direction.

**Comment by faceyspacey** [comment]
Glad you like it guys. The best I can say is to read the main docs and *then* go through the updates at the top of the readme. Rudy is almost out and will have revamped documentation.

**Comment by schmidsi** [comment]
Cool. Looking forward to it. If I can be of any help, let me know.

**Comment by zackljackson** [comment]
Use master if it will do what you need. We are working on a large upgrade (Rudy) which should be out in a couple weeks

Versioning should clear up too, soon. 
Pretty much Rudy is going to be a significant upgrade capable of doing a lot of things. Rudy is also the brains of the operation for our next big thing, the Respond Framework.
