### ISSUE TITLE
query string from url

### ISSUE THREAD

**Issue by tvald** [faceyspacey/redux-first-router#182]
Documentation indicates that it should be available at `action.meta.location.query`. However, in `redux-first-router@0.0.20-next`, I don't see that field being set.

When I set up a test server and navigate to `/?foo=bar`, I observe the following action dispatched:

```
{
  type: '/',
  payload: {},
  meta: {
    location: {
      current: {
        pathname: '/',
        type: '/',
        payload: {}
      },
      prev: {
        pathname: '',
        type: '',
        payload: {}
      },
      kind: 'load'
    }
  }
}
```

**Comment by faceyspacey** [comment]
Query string support likely isn't enabled:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/query-strings.md#how-to-enable-query-string-serialization
