### ISSUE TITLE
The readme confused me

### ISSUE THREAD

**Issue by ericandrewlewis** [faceyspacey/redux-first-router#184]
The first section of the readme details updated about Rudy, which seems like a new version of redux-first-router. 

As a newcomer to redux-first-router trying to learn about what the project is I was confused by these updates.

It might be helpful to move those updates somewhere else in the readme, and perhaps describe Rudy a bit more. Is it a 1.0 of redux-first-router? 

Thanks and I'm excited to try out your package :)

**Comment by schmidsi** [comment]
Actually, I had similar problems discussed here #180

**Comment by faceyspacey** [comment]
I know i know. When I release Rudy all the docs will be updated and all this stuff reconciled. There's not much I can do until then as my time is limited, and the BIG upcoming update will bring it all together all at once.
