### ISSUE TITLE
With SSR, the thunk is not run when the client dispatches a location equal to current location

### ISSUE THREAD

**Issue by w9** [faceyspacey/redux-first-router#185]
With SSR, it is documented that the thunk will not be run on the server side so that the server can await it before sending the HTML.

However, it seems that at the client-side, if user's *first* action is to dispatch the same location (e.g., clicking the nav button corresponding to the *current* page, normally causing the current page to "refresh"), then the thunk of this page is *not* fired at all.

I think this is not correct, since most of the time when a user clicks the "Home" nav button when they are at "Home" page, their intention is to "refresh" the page and thus the thunk (which is responsible for fetching data) should be re-run in this case.

Note that this seems to only happen when self-direction is the *first* action they do. If they go to "About" page and then keep clicking "About", then the thunk of "About" fires as expected.

**Comment by w9** [comment]
These are the relevant lines:

https://github.com/faceyspacey/redux-first-router/blob/b98a645a7eb29e8c419bb8ea29582022d657be91/src/pure-utils/attemptCallRouteThunk.js#L20-L33

**Comment by w9** [comment]
I think setting hasSSR to be false upon hydration of the page is a good way to fix this.

**Comment by faceyspacey** [comment]
This is the intent. SSR is supposed to supply the data

**Comment by faceyspacey** [comment]
In Rudy double dispatching the same action isn't even allowed. It short circuits.

**Comment by w9** [comment]
@faceyspacey But in that case what's the recommended way to do pseudo-refreshing?

**Comment by faceyspacey** [comment]
You don't. The user isn't supposed to gain anything from that. Everything should be on the page already.
