### ISSUE TITLE
`manual` scroll restore should short circuit unless performed by user

### ISSUE THREAD

**Issue by kshahani** [faceyspacey/redux-first-router#186]
[This line](https://github.com/faceyspacey/redux-first-router/blob/660c9492ea4ba97fc2726cb394f980c9e9872f62/src/connectRoutes.js#L560) should probably be:

```
if (!scrollBehavior.manual || performedByUser)
```

...to allow the user to call `updateScroll()` from anywhere in the application while `manual: true` is set for `redux-first-router-restore-scroll`. Otherwise, `updateScroll` does nothing.

**Comment by faceyspacey** [comment]
This will be changing to be an optional plugin configurable by the user in Rudy, which is almost out. Stay tuned.
