### ISSUE TITLE
onBeforeChange not fired on back button

### ISSUE THREAD

**Issue by mattoni** [faceyspacey/redux-first-router#188]
I feel like I'm overlooking something, but I'm trying to check authentication and redirect in my 'onBeforeChange' option, but ran into two issues:

1) onBeforeChange is never called when clicking the back button (firefox quantum)
2) on the client, dispatching a redirect in this function leads to an infinite loop since 
onBeforeChange is called for the redirects as well. 

I'm using redux-saga as well, and while my reducer picks up the back button action, my saga does not (perhaps an ordering issue with middleware?)

Looking for the best way to solve this issue, thanks.

**Comment by faceyspacey** [comment]
That is an ordering issue. Your saga middleware should come after the RFR middleware. Re-open this if that doesn't work.

**Comment by mattoni** [comment]
Seems to be an issue no matter which order they are in. Going back completely ignores the onbeforechange handler.

**Comment by mattoni** [comment]
I've got all three pieces wired in - the middleware, the enhancer and the reducer. I suspect it might be how I'm setting up the enhancer since I was least familiar with that concept. I did:

```
store = createStore(
        rootReducer,
        state,
        composeEnhancers(rootMiddleware, routerEnhancer),
    );
```
where rootMiddleware is 

```
applyMiddleware(
    routerMiddlewared
    sagaMiddleware,
);
```

Should I be doing it differently?

Thanks so much.

**Comment by mattoni** [comment]
Ahh I swapped the enhancer + the rootMiddleware and it seems to have solved the issue :) Thanks for the help
