### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by viggyfresh** [faceyspacey/redux-first-router#19]
Just finished ripping out react-router and using this in its place...so far so (very very) good.

One pain point - any chance you can magic up a typings file for the TypeScript users of the world?

**Comment by faceyspacey** [comment]
It's definitely a must but low on my personal priority list.

They're all in this single file:

https://github.com/faceyspacey/redux-first-router/blob/master/src/flow-types.js

and then just re-exported here:

https://github.com/faceyspacey/redux-first-router/blob/master/src/index.js

it should be easy to make.


....glad it's working for u. let me know when u get to SSR, I'll help you out. I want to insure the SSR experience is frictionless.

**Comment by faceyspacey** [comment]
ps. if u do find a magic converter or something let me know.

**Comment by viggyfresh** [comment]
A quick Google spree showed typescript -> flow converters, but not the other way around. Time permitting, might be able to cobble a PR together...flow and TS definitions look eerily similar.

I'm actually building an Electron app, so I am (currently) miles away from SSR.

**Comment by faceyspacey** [comment]
...cool. u using the thunk feature?

**Comment by viggyfresh** [comment]
Saga actually! Although the thunks are slick. No problems so far; I think you had mentioned in the Medium blog post some tweaks might be necessary to get this to play nicely with saga, but (in my basic usage) doesn't appear to be the case.

Related question - in that blog post you said `isLocationAction` would be useful to fire navigationally-dependent sagas. If I'm dispatching actions in object form `dispatch({ type: 'USER', payload: { id: 5 } })`, those don't appear to be location actions (based on my own testing and looking at the source of `isLocationAction`). When would something actually return true for `isLocationAction`?

**Comment by faceyspacey** [comment]
in the middleware. 

...i think ur referring to a comment discussion regarding sagas right? ...this will key for me to know if it works.

**Comment by faceyspacey** [comment]
...it is considered an `isLocationAction` after my middleware adds all the info on `action.meta.location`. 

...maybe that hasn't happened yet. ...just do this:

```js
import routesMap from 'src/routesMap.js'

export const hasRoute = (type: string) => !!routesMap[type]
```

**Comment by viggyfresh** [comment]
yeah referring to the comment thread. makes sense - was my workaround as well!

**Comment by faceyspacey** [comment]
not a workaround. the idiomatic solution. i'll add it to the docs next time im in that area.

**Comment by viggyfresh** [comment]
thanks - turns out (duh) order of middlewares matters. Putting `redux-first-router` middleware before `redux-saga` middleware did the trick!

**Comment by faceyspacey** [comment]
excellent. yea, i think i forgot to put that in the readme. ideally put this first. first gets the most capability.

**Comment by faceyspacey** [comment]
....if u get a chance, u should create a PR for a sagas example.

**Comment by faceyspacey** [comment]
just `.md` doc. if u wanted to make an actual boilerplate, that would be cool too, but less important to start.

**Comment by Valbrand** [comment]
Concerning TypeScript support: I've been writing a .d.ts file for this project. It can currently be found at https://github.com/Valbrand/DefinitelyTyped/blob/redux-first-router/types/redux-first-router/index.d.ts

I'd appreciate any feedback as I'm not very experienced with TypeScript, @viggyfresh

**Comment by faceyspacey** [comment]
@Valbrand very cool!

**Comment by viggyfresh** [comment]
@faceyspacey will do for the sagas example - should be able to get to it later this week.
@Valbrand I'm not super experienced either 😄 at first glance, the non-FIXME-labeled definitions seem reasonable. I'll toss that file into VS Code and see if it gets picked up properly.

**Comment by Valbrand** [comment]
@viggyfresh I've added definitions for the missing types just now. It's not working properly, though (you can see that in the tests file in the same folder). I cannot work further on it for the next day or two, but I'll try to get it solved. If you find the issue, be my guest! I want this solved as much as you 😄

**Comment by Valbrand** [comment]
Nevermind – I found the problem.  I guess the current implementation is good to go.

**Comment by faceyspacey** [comment]
If u guys are having successes with the package can u post a Medium article about it. There's a lot of competition that just came out of the wood works. I've seen 2 new routers appear and Redux Little Router did my suggestion to remove a Provider and full app virtual dom re-rendering just yesterday, among a few other changes. 

I've reviewed em all. Don't worry, they still aren't getting it correct :) 

But anyway the rest of the world is likely to interpret this as the time when all these Flux variants came out. This is "Redux." It's already correct. The problem solved in its simplest form. Let the world know!

I can help with editing and promoting ur piece. My medium article is almost at 100 stars and I was an unknown name until last week.

**Comment by Valbrand** [comment]
Update: I've opened a Pull Request on DefinitelyTyped. If all goes well, type definitions for `redux-first-router` should be available soon. In this case, I'll open a PR here to update the README. 

I haven't had the time to actually sit and continue my project which uses this project. It's been great, by the way. As soon as I have something to share, I might really write a story about it.

**Comment by Valbrand** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17417 was merged. This can be closed

**Comment by faceyspacey** [comment]
That is excellent. Thanks so much @Valbrand !!!

**Comment by NicholasGWK** [comment]
@Valbrand Great work on the typings, it's working awesome! Not sure if this is the right place to post a potential issue but wasn't sure if I should open in on Definitely Typed or open a new issue. 
  
One comment about the type for the function `redirect`, it's listed as `Action` which restricts it to having a payload + redux-first-router specific `Meta` type which I don't think is correct...based on the look of the function is just switches the "kind" to redirect, so I'm not sure any props are actually required on the input (although requiring `type` would logically make sense).

In the docs it shows redirect used as a helper for actions which don't conform to the `Action` type. Right now the typings will throw an error if used as shown in the screenshot below.

Thanks for doing the typings! If I'm not crazy I'd be happy to make the updates as well, but wanted to verify I was correct first.

<img width="1052" alt="screen shot 2017-09-07 at 4 21 46 pm" src="https://user-images.githubusercontent.com/6642497/30183670-4f7f62a4-93e9-11e7-8a0c-6a44272cdb88.png">

**Comment by Valbrand** [comment]
@NicholasGWK Thank you very much! I don't have the time right now as it's almost midnight here in Brazil, but I took a quick look at the redirect action creator and I don't see much of a problem with the signature for `redirect`. I promise you to take a better look at it tomorrow, but I still wanted to give you my first impressions on what you brought up.

**Comment by quirk0o** [comment]
@Valbrand  I've had the same issue @NicholasGWK had - although it does seem to match the flow types from `redux-first-router`. But after looking deeper into the code I can see that the `redirect` action creator appends the fields necessary for it to be an `Action` (`Payload`, `Meta`, and `type`) and it doesn't really make sense to pass those in. Dunno how it works in flow but TypeScript complains if I just pass an object with the `type` property unless I cast it to `Action`.

**Comment by Valbrand** [comment]
@quirk0o in fact, all I did was to make the TS typings match the flow definitions. What you say makes sense, would you mind creating a PR for this? I've been away from this for a while (final months of my degree are sucking my life off me ahahaha), so maybe I'm not the best person to give you that answer right now.

**Comment by 1x-martin** [comment]
Not sure if this is the correct way of going about it. I ran into the same problem with the redirect signature.
