### ISSUE TITLE
How to execute code in thunk only when SSR

### ISSUE THREAD

**Issue by btmorex** [faceyspacey/redux-first-router#190]
I'd like to execute some code in a thunk only on the server. Perhaps there's a better way to workaround my problem though.

My use case is this:

I have a route that I'd like to prepopulate with state on the server, however, sometimes that route is redirected to on the client. On the client, I'd like to fetch the data in componentWillMount because the data fetch is actually an ongoing poll of the server. I have to start a fetch on client in componentWillMount regardless of whether data was fetched in the thunk because I need to stop the polling in componentWillUnmount. If a fetch is started both in the thunk and in componentWillMount, there will be two outstanding fetches and the results of the fetch can cause a redirect potentially leading to two redirects, which I'd like to avoid. Or does RFR ignore redirects to the current route in which case I don't need to worry about two redirects occurring?

**Comment by faceyspacey** [comment]
The way to handle this is just: `if (type window === 'undefined') //do something different on the server`
