### ISSUE TITLE
Redirect to external website

### ISSUE THREAD

**Issue by raRaRa** [faceyspacey/redux-first-router#193]
Hey, how does one redirect to an external website, e.g. `https://github.com`.

One way for me to solve it would be creating an action that changes `location.pathname`, but I wanted to know if there's a solution for ext. redirects in redux-first-router.

Thanks.

**Comment by srinivasdamam** [comment]
Are your rendering on server ? I think this helps:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/server-rendering.md#redirects-example)

**Comment by faceyspacey** [comment]
if it's on the client. just change the value of `window.location`. if it's on the server, do it the Node way. There's nothing built in to redirect to an external website. Links can link to external links though, but that's not a redirect.
