### ISSUE TITLE
Url encoded payload is not decoded

### ISSUE THREAD

**Issue by ngbrown** [faceyspacey/redux-first-router#194]
A payload value passed to `redux-first-router-link` is correctly url encoded, but when navigated to and the Redux state has the payload, the value is not decoded.

This is using the rudy branch and the `Link` looks something like this:

```jsx
<Link to={{type: 'ROUTE_A', payload: {id: 'R2VuZXJhbEVudHJ5OjMwNTE3MA=='}}}
```

Which generates a URL like this: `http://localhost:3000/view/R2VuZXJhbEVudHJ5OjMwNTE3MA%3D%3D`.  Which is all fine, except it isn't reversed when the route is loaded in `redux-first-router`.

To work around this, I added `decodeURIComponent` to the `fromPath` to the route map:

```js
const routesMap = {
  ROUTE_A: {
    path:'/view/:id',
    fromPath: (pathSegment, key) => decodeURIComponent(pathSegment)
  },
};
```

I think the expectation would be that `decodeURIComponent` would be handled internally.

**Comment by faceyspacey** [comment]
I'll look into doing this internally again. i forget why we don't do it, but yea, you find the solution.
