### ISSUE TITLE
Does redirect() include action.query when called on server?

### ISSUE THREAD

**Issue by willchertoff** [faceyspacey/redux-first-router#197]
I have the following redirect code running in `onBeforeChange()`

```javascript
const date = moment()

const newAction = redirect({
  type: 'DASHBOARD',
  payload,
  query: { date },
  ...action.query
})

return dispatch(newAction)
```

When this code runs on the server, I don't see the query params sent to the url. They are however present in the `store`.

I think the problem is that redirect only accepts `payload`. 
```javascript
export default (action: Action, type?: string, payload?: any) => { // Should query be added here?
  action = setKind(action, 'redirect')

  if (type) {
    action.type = type
  }

  if (payload) {
    action.payload = payload
  }

  return action
}
```

I have configured `connectRoutes` with `query-string` as instructed.

**Comment by faceyspacey** [comment]
the query params will be on the action. payload is just an optional helper.

I don't know what you mean by "sent to the url." That said, if they're in the store, you can always reconstruct the URL and redirect on the server yourself.

**Comment by faceyspacey** [comment]
i think what u might mean is the query from the URL isn't sent to RFR. Read the last paragraph here:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/query-strings.md#how-to-enable-query-string-serialization

express only sends the path with `req.path`. Instead use `req.originalUrl` which will contain the query string.

Re-open if you need.
