### ISSUE TITLE
Immutable.JS support

### ISSUE THREAD

**Issue by oleksiipysanko** [faceyspacey/redux-first-router#20]
Hi, thanks for an awesome library!

One thing that I've stumbled across when trying to use it in my app is a redux state wrapped in `immutable` structure. I'm using https://facebook.github.io/immutable-js across all my apps, so `store.getState` will return immutable map instead of a plain js object.

Is there any possibility to make it work?

**Comment by faceyspacey** [comment]
Doesn't the immutable ecosystem have an enhancer that replaces `store.getState` with an immutable one?

There could be more to it, but basically at the following line we need an immutable-based store:

https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L352

There's probably more--as my code doesn't use immutable. I assume the reducer needs to be rewritten in Immutable style:

https://github.com/faceyspacey/redux-first-router/blob/master/src/reducer/createLocationReducer.js

I could add a plugin that supports that. This is as opposed to converting back and forth from js to immutable, which would lose Immutable's structural sharing capabilities. 

But that's not the only challenge. Basically it seems the various times I access state, I need to use Immutuable's `get` methods. 

I'm down to help out with this, but I'm not an Immutable user, so it would take one to analyze the codebase and come up with a better diagnosis than this. But I don't think it's plug-n-play. At least not without losing the benefits of Immutable within this codebase. Like, we could probably quickly rewrite all calls to `store.getState()` to `parseWithImmutable(store.getState())`. As i recall they have a `toJS()` method or something like that, and that's what `parseWithImmutable` would do. So we could make this function and if u didn't specify the `usingImmutable` option to `connectRoutes`, we do it the normal way. 

Something like that could get you up and running sooner than later. And then over time, the optimizations could be made. Basically we need an interceptor consistently used. `getState()` is called a lot for various decision-making.

**Comment by oleksiipysanko** [comment]
@faceyspacey thanks for a quick response!

I'm using a common reducer for the whole state - components just dispatch a `changeState` action from redux sagas, so I've integrated your reducer into this flow the same way. As far as I know, there is a `redux-immutable` package which provides `combineReducers` function that should support a common use case. 

The problem is that if you patch `.getState` with something like immutable's `.toJS` it'll return a completely new object, so components will re-render for any state change. I've looked through `createLocationReducer.js` and `getState` is used a lot there indeed. I guess `parseWithImmutable` should do the trick by using `.get` or `.getIn` methods.

I can make a pull request, I guess, if possible. Please, let me know

**Comment by faceyspacey** [comment]
I want to say yes. But I also don't want to complicate the codebase just yet. A few final very important things are coming out next week. After that would be a better time. 

But that shouldn't stop you from forking it and using it. When the time is right we'll integrate it. Basically, the devil is in the details. It may be more than just `get` and `getIn`, or if it is, it's a lot of it--because here's how nested state is: `state.location.prev.payload` or `state.location.history.entries[0].pathname`. 

So the codebase would literally become littered with 2 ways to do something. What hopefully happens though is that after the research in your fork, you find an optimum *low impact* way to accomplish this. In most places, it's just accessing props one or 2 levels deep. So a helper function to access props, eg: `prop('prev.payload', store.getState())` could do the trick. And obviously `location` is assumed as the first key in that example, since that's what's accessed every time. `prop(store.getState())` would get `location`.

If something like this made the codebase a little shorter smaller/simpler, that would be a big sell. Perhaps we can hit 2 birds with one stone.

**Comment by faceyspacey** [comment]
we also could do the reverse, and just copy the Immutable API. But behind the scenes do it the regular non-structural-sharing way unless u specify that ur using Immutable. It may also end up simplifying things and making things more consistent. It may basically accomplish the `prop` api example in an almost identical way. I'll review the Immutable docs sometime soon.

**Comment by faceyspacey** [comment]
I would just do the latter. Rewrite it in Immutable style. If worse comes to worse, there's a working fork in the wild. This codebase isn't new. It's been iterated on over 8 months to get to where it is. I don't see very many major features I want to add. It will primarily be about fixing small bugs for edge cases people encounter. 

So even if ur behind a little bit, u should be fine. Make it work for you in the *idiomatic Immutable way*, and we'll circle back once you do.

**Comment by faceyspacey** [comment]
ps. it's HUGE in that it adds some very important features (code-splitting + prefetching in a very right form). But most the codebase won't change. It won't affect u much to merge them in. Its primarily new code. And actually the code is primarily in other related packages.

**Comment by oleksiipysanko** [comment]
I've started a fork, will see how it goes

**Comment by faceyspacey** [comment]
You may want to check out this:

https://github.com/FormidableLabs/redux-little-router/issues/77

https://gist.github.com/Nihaux/0ac0d5e4e7bdc82be78bcb83cbc2fd9e

**Comment by oleksiipysanko** [comment]
Thanks for a reference. As far as I understood the gist patches state for reducer itself, while `connectRoutes` uses `getState` in other places and for other purposes, so I guess this solution doesn't fully fit here. But, maybe, I just get it wrong.

Anyway, I've already done fast and dirty version which works with immutable in my fork, will see how it goes

**Comment by faceyspacey** [comment]
Super exciting! ...yea we use it a lot more, I just wanted to post that just in case. 

If this works for u, do a medium post to show other people ur results and bring more people to this router. More people equals more support.

**Comment by iansinnott** [comment]
@oleksiipysanko hey, how has your immutable project been going? I'm super interested in this as well.

@faceyspacey this is an AMAZING PROJECT! What the hell, this is great. But I'm commenting here because supporting arbitrary state shapes (including Immutable) would be great for this project and probably help it grow more quickly. Many people seem to be using immutable or some other data structures with Redux. For me personally this is the _only_ reason I haven't switched over yet—everything I'm writing uses immutable. 

Anyway, I'm following this project. Really great job 👍

**Comment by faceyspacey** [comment]
Thanks. I'm not opposed to full immutable support. I just want to get feature-complete first, and we're almost there. 

At the end of the day the Immutable thing will likely have to be pioneered by Immutable developers. I plan to make complete documentation of the codebase as well, to make it easier for people to work on.

**Comment by oleksiipysanko** [comment]
Hi @iansinnott. I've made a fork here https://github.com/rocketstation/redux-first-router and just replaced all `getState()` calls with immutable methods. Not sure if I can recommend using it to anyone else since it is not the way how I and, probably, @faceyspacey want it to be in prod repo. 

But still, it works for me just fine across my new projects and they're all web-based SPAs. Overall it is a great experience, really, and just what I was seeking for in routing space since starting with React/Redux.

We're now waging a usage of ImmutableJS in our projects and as a result a need for support and pull of this fork. But I'm still up to provide any help in this direction.

**Comment by iansinnott** [comment]
@faceyspacey yeah that makes sense. I'd be happy to help with this once you feel the project is feature complete and ready for something like this.

@oleksiipysanko thanks, that sounds great. I will check out your fork.

**Comment by iansinnott** [comment]
This should be supported once latest is released. Pass in a state selector function as the `location` option:

```js
const { reducer, middleware, enhancer } = connectRoutes(history, routesMap, {
  location: state => state.get('location'),
});
```

If you're using immutable it's worth noting that this approach means you will have a plain JS object sitting in state being managed by redux-first-router. Not sure if that could become an issue, but if so the redux-first-router reducer could be wrapped in higher order reducer to convert back and forth between plain JS and immutable.

```js
import { combineReducers } from 'redux-immutable';

// A toJS function you can call on anything, even undefined
const toJS = x => {
  if (x && typeof x.toJS === 'function') {
    return x.toJS();
  } else {
    return x;
  }
};

// Wrap a non-immutable reducer to make it compatible with an immutable state.
// This may not be necessary but it's worth noting that without it we are
// storing a plain javascript object within the larger immutable map
const wrapReducer = (innerReducer) => (state, action) => {
  return Immutable.fromJS(innerReducer(toJS(state), action));
};

const { reducer, middleware, enhancer } = connectRoutes(history, routesMap, {
  location: state => toJS(state.get('location')),
});

const rootReducer = combineReducers({ location: wrapReducer(reducer), ...otherReducers });
```

**Comment by faceyspacey** [comment]
very nice. 

I wonder with these solutions are we as fully performant as we would be if RFR was built fully with Immutable in mind? 

..ps @iansinnott i just pushed a bump that will auto-deploy. use `yarn run cm` in the future as that will force you to write your commits in a way that travis knows what to do with, i.e. auto-publish.

**Comment by faceyspacey** [comment]
and we're published! again, excellent job @iansinnott !!

**Comment by iansinnott** [comment]
Yeah, performance is definitely a concern if you're wrapping a reducer with `fromJS` and `toJS`. But so far I haven't had any issues keeping a the plain object state in my overall immutable state. It's just inconsistent and thus not _simple_.

If that perf ever did become an issue though there are options available. 

* Implement something like `redux-first-router/immutable` like [redux-form does](https://github.com/erikras/redux-form/blob/fd97e64f1f2aab65ebe5770d9eee32499e1bb5bb/src/immutable.js) or create a separate project that does the same
* Implement the reducer yourself like [react-router-redux suggests](https://github.com/reactjs/react-router-redux#what-if-i-use-immutablejs-or-another-state-wrapper-with-my-redux-store)
* Fork this project and just code it yourself
* More solutions I haven't thought of...

**Comment by Kay2dan** [comment]
Just want to add a shoutout here. I too am a big immutable fan and have just across this library. Will be going through the blog posts & docs & hopefully implement in the new project Ive started. First-class immutable support would be ideal though :)

**Comment by faceyspacey** [comment]
I'm closing this out. It sounds like we previously made good enough progress for immutable. If someone wants it bad enough they can make it and I'd be happy to help. Hit me on Reactlandia chat.
