### ISSUE TITLE
type="module" support

### ISSUE THREAD

**Issue by Alex-Ferreli** [faceyspacey/redux-first-router#200]
Hi faceyspacey, first of all thanks for your awesome work with this project. Really awesome and well structured.

I'm creating a boilerplate based on your boilerplate:
https://github.com/faceyspacey/redux-first-router-boilerplate

How can i implement this technique in my project?
https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

I didn't have control of witch files are returned by the `flushChunks` function.
I think that it's impossible right now, because i must generate two completly different bundle with webpack and refer the compiled bundles server-side:

```
<script nomodule type='text/javascript' src='/static/bootstrap-legacy.2930fdf0bbb4c3b1ec0e.js' defer></script>
<script nomodule type='text/javascript' src='/static/vendor-legacy.4ab8ec5c65af93a572c0.js' defer></script>
<script nomodule type='text/javascript' src='/static/Home-legacy.cf81cb15404d1523195b.js' defer></script>
<script nomodule type='text/javascript' src='/static/main-legacy.a2438deafe0f45ae06d2.js' defer></script>

<script type='module' src='/static/bootstrap.2930fdf0bbb4c3b1ec0e.js' defer></script>
<script type='module' src='/static/vendor.4ab8ec5c65af93a572c0.js' defer></script>
<script type='module' src='/static/Home.cf81cb15404d1523195b.js' defer></script>
<script type='module' src='/static/main.a2438deafe0f45ae06d2.js' defer></script>
```

Thanks for your reply in advance.

**Comment by faceyspacey** [comment]
@Alex-Ferreli glad you like it. I haven't been able to study `type="module"` yet, so you'd be a pioneer here. Feel free to supply your findings. 

ps. it is something I'm very interested in, and have imagined building a faster HMR experience during development, given it seems we can forgo both transpiling and bundling altogether in many scenarios.

**Comment by Alex-Ferreli** [comment]
I have tried to implement the type="module" with my own boilerplate (that is based on your boilerplate, so it's the same thing).
The problem is that to setup correctly client and server with `webpack-dev-middleware` and associated tools, you need to pass 1 webpack configuration for client and 1 for server (with different name, "client" and "server").
But like is pointed in the article, you should have 2 different client config, 1 to compile for older browsers and 1 to compile the same files for browsers that support type="module" on script tag, so didn't seems possible right now.

I have tried to compile 2 different entries (main.legacy.js and main.es2015.js) that point to the same file (./src/index.js) with 2 different loaders, one for each entry. But i didn't have find the right configuration to make it work; seems that i can't apply 1 loader for 1 entry and 1 loader for another entry that involve the same files.

Inherent to the ps, i would use the 2 different bundle in development too, to avoid problem in production that you can't reach in development.

**Comment by faceyspacey** [comment]
Why not just use the modern modules way in development, which should be lightning fast to build. And then in production produce all 3 builds, which is easy because it doesn’t require the dev middlewares.

???

**Comment by hedgepigdaniel** [comment]
It's a good idea to have a separate staging environment halfway between development and production. There are lots of other things that should be tested there, e.g. minification.

Obviously it would be better if the development environment matched production, but I think you have to compromise when you run into things like this that make the build slow. Faster development builds = more time to test on staging.

**Comment by Alex-Ferreli** [comment]
Yes, we can make only the es2015+ bundle in development because almost all web developers use Chrome but the problem of 3 bundles didn't is solved.

The problem is that i didn't have controll of wich scripts are attached to DOM with SSR; if i visit the homepage of your boilerplate, the script attached to the HTML are retrieved from `webpack-flush-chunks` package. I didn't have read the full source code, but it need webpack stats to match the name of the js file to expose and he didn't accept multiple stats so i can't do 2 different build and pass it to the package.

How can i teach `webpack-flush-chunks` to read from 2 stats and choce the right js files for the right path? Example for home page, the plugin must return 2 homepage file (plus vendor, webpack bootstrap and main) like in my example in the first post.

**Comment by faceyspacey** [comment]
before going any farther, i'd get this to work without dynamic imports. after that, it should be trivial to make this work or simply fork it and make your own way of discovering the dynamic imports.

here's the code you want to look into:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L66-L67

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L192-L209
