### ISSUE TITLE
Idiomatic solution to "layouts"

### ISSUE THREAD

**Issue by benhowdle89** [faceyspacey/redux-first-router#201]
This must feel like a cliche opener, but "in React Router I did it this way" but I'm desperately trying to adopt/migrate to Redux First Router in an existing application. 

I think I have quite a common set up where I have a set of "marketing" pages and then a "dashboard".

In my existing app, the <Router> would render my Root Component as so (pseudo-ish):

```
render() {
        if(inApp(this.props.location.pathname)){
            return <AppContainer>
                {
                    this.props.children
                }
            </AppContainer>
        }
        return <MarketingContainer>
            {
                this.props.children
            }
        </MarketingContainer>
    }
```

with `this.props.children` essentially equating to RFR's `<Switcher />` Component in the demos?

How would you recommend replicating (or, improving) this behaviour with RFR/Switcher?

Great work on the library, I'm _extremely_ excited to have navigation in Redux.

**Comment by faceyspacey** [comment]
i mean you just update some state in response to an action. so you'd have like a `page` reducer and depending on its value, you render App vs. Marketing :)

**Comment by benhowdle89** [comment]
I _believe_ I was over-thinking this. Because I ended up with:

```
const Switcher = ({ page, location }) => {
  const { type, pathname } = location
  const child = <TransitionGroup
    duration={500}
    prefix='fade'
  >
    <Transition key={page}>
      <UniversalComponent page={page} />
    </Transition>
  </TransitionGroup>
  if(inApp(type)) {
    return <AppContainer>
      { child }
    </AppContainer>
  }
  return <MarketingContainer>
    { child }
  </MarketingContainer>
}
```

And it works exactly like I hoped it would. Thanks!
