### ISSUE TITLE
Dynamic basename?

### ISSUE THREAD

**Issue by tume** [faceyspacey/redux-first-router#202]
First of all thanks for the great project. I have been really enjoying working with it (recently migrated medium-sized project from react-router to RFR).

I stumbled across this issue: https://github.com/faceyspacey/redux-first-router/issues/121 and was wondering whether the basename could also help in my case or cases or if there is something new coming in rudy-next?

We currently have two usecases where we share some common basename for bunch of urls.

1) We have a urls that look like this /company/:companyID/posts/ where companyID can change but most of the time stays static. Our pages are fetching data based on that companyID but aren't really used for anything else. Currently all the paths in routesMap just contain the companyID and it's also passed to links. This part is kind of okey because couldn't figure better way when I did this so not so big problem but could be nice to figure out some nicer way.

2) Our app also has "user" side and then admin interface. These basically render same views but admin might have few more options in some cases and so these urls look something like:

/company/123/user/posts and /company/123/admin/posts 

and now I'm thinking that would be really nice if I could leave the links like they are but just have the user/admin be automatically inserted there based on which url you are on. Not really sure how to tackle this one...now wondering whether basename might be good candidate or should I just create my own Link component with that custom behaviour.

Any feedback would be highly appreciated, especially since I still might have more react-router mindset and not really realize the full potential of RFR.

**Comment by faceyspacey** [comment]
Base name would work if you put it at the beginning of the url.

Basename handling in the next major release is going to get even simpler and completely automated. Basically you will be able to just put action.basename and it will change the basename + it will automatically detect it in all incoming URLs by providing an initial array of all available basenames as an option.

If at all possible wait a week or two more before implementing it and do it with Rudy.

**Comment by tume** [comment]
Sounds nice 👍 
I would assume that basename is also part of the meta on actions dispatched?

Is there a way to test this coming version?

**Comment by hartzis** [comment]
Looks like `rudy` was last published in Sept 2017 - https://yarnpkg.com/en/package/redux-first-router. I too would really like to test an updated published version, getting excited!

**Comment by zackljackson** [comment]
Rudy is currently under active development. We want it published as much as you do 😂🙂

**Comment by klis87** [comment]
@ScriptedAlchemy does recently published version 2.0 supports dynamic basename?

**Comment by ScriptedAlchemy** [comment]
@klis87 does this help at all?

https://github.com/faceyspacey/redux-first-router/blob/2039ac3787da92d51e9240bbf66e680a182967ac/docs/low-level-api.md

**Comment by klis87** [comment]
@ScriptedAlchemy before I try it, I have another question, last version I used was `0.0.16-next`, as I didn't use next tag. Everything worked perfectly. Unfortunately now no of my routes is hit anymore, for instance simple
```js
const routesMap = {
  HOME: '/en',
}
```
doesnt work anymore, as on load 
```js
{
  type: '@@redux-first-router/NOT_FOUND',
  payload: {},
  meta: {
    notFoundPath: '/en',
    location: {
      current: {
        pathname: '/en',
        type: '@@redux-first-router/NOT_FOUND',
        payload: {}
      },
      prev: {
        pathname: '',
        type: '',
        payload: {}
      },
      kind: 'load'
    }
  }
}
```
is dispatched.

I rechecked docs but I couldnt find any API change for this simple case, do I miss sth? Because of this unfortunately I cannot upgrade to 2.0 :(

**Comment by ScriptedAlchemy** [comment]
yep, dont worry about it :) 

First off, I am mega sorry that the docs had holes. Ive spent the last year working on Universal and Rudy, honestly wasnt sure what to expect with RFR2. 

Check this PR, its docs on migration. Should get you back up and running


https://github.com/faceyspacey/redux-first-router/pull/306

**Comment by ScriptedAlchemy** [comment]
As for Rudy, its got a new home - its still a few weeks away from release, but many of you have been waiting for Rudy so i thought id drop where the action is at :)

https://github.com/respond-framework/rudy

**Comment by ScriptedAlchemy** [comment]
@klis87 ☝️

**Comment by klis87** [comment]
@ScriptedAlchemy Please dont apologise, we are all super grateful for great job you have done :) I have a really busy working day, so I wont be able to work on this today, but I will check everything during weekend.

Btw, I am really waiting to try `rudy` too, although docs looks almost like RFR, is this a matter of updating DOCS or API is just similar?

**Comment by ScriptedAlchemy** [comment]
Its a matter of updating the docs. However theres a boilerplate in the monorepo and everything works :)

If you feel like making any form of notes while looking at rudy, ill happily accept them and turn it into docs.

RFR2 is like a year old version of Rudy, it contains about 40 file changes. Rudy is 400 file changes :joy: So there are similarities in the APIs

**Comment by klis87** [comment]
@ScriptedAlchemy migration to RFR 2 did work out, thx. Now I will test dynamic basename

Btw, I checked Remixx stuff and I cannot wait for this, it made me aware that it is not Redux which causes boilerplate (assuming we use action creator library like redux-act and you dont need to define constants), it is `mapStateToProps` and its family, it would be so great if indeed this could be automated, fingers crossed :+1:
