### ISSUE TITLE
Multiple path for one action

### ISSUE THREAD

**Issue by Muffassa** [faceyspacey/redux-first-router#203]
Thanks for the great project. I have a questions about routesMap. How can i add tow routes for one action. For example i have action `Home` and a want to route on this action from '/' and '' urls. It will be good to have ability to add path in array something like this: 

```
const routesMap = {
  HOME: ['/', '', '/home'],
}
```

and 

```
const routesMap = {
  HOME: {
    path: ['/', '', '/home']
  },
}
```

**Comment by faceyspacey** [comment]
Glad u like the project. Here’s how:

/(home)?

Read here for more info:

https://github.com/faceyspacey/redux-first-router/issues/83#issuecomment-327703226

**Comment by mariegodon** [comment]
Hi @faceyspacey! I have a similar question but for a more complex use case.

Is it possible to do something like this with RFR:
```
const routesMap = {
  BLOG: {
    path: ['/blog-:id(\\d+)', '/blog-:id(\\d+)-:accessCode']
  },
}
```

Here `:accessCode` is optional. Note in the second string, `:id` and `:accessCode` are separated by a `-` which we do not want to include in `:accessCode`.

Any help would be much appreciated! Thanks!

**Comment by ScriptedAlchemy** [comment]
Rather open a new issue. Also, investigate our new documentation  with version 2

**Comment by ScriptedAlchemy** [comment]
We now have ways to do what you need. It's also mention in our closed issues. 

If you learn a new trick, please feel free to open a pull request
