### ISSUE TITLE
Update Query Strings docs

### ISSUE THREAD

**Issue by dominicglenn** [faceyspacey/redux-first-router#207]
I tried looking up how to enable query serialization, and the docs are incorrect.

In `docs/query-strings.md` the example shown is

```
connectRoutes(routesMap, {
  querySerializer: queryString
})
```

but should read:

```
connectRoutes(routesMap, routeMap, {
  querySerializer: queryString
})
```

**Comment by faceyspacey** [comment]
that doc has the API of the `rudy` tag on NPM--the `history` arg is no longer needed. All will be resolved shortly.
