### ISSUE TITLE
What is Rudy?

### ISSUE THREAD

**Issue by edahlseng** [faceyspacey/redux-first-router#210]
I'm new to redux-first-router, but I've got to say that it looks fantastic! I'm excited to start using it. Before diving in, I just had a question about Rudy, as I couldn't figure it out clearly from the documentation – is Rudy the next version? If so, what is the focus of the release and what's its roadmap? I'm getting pieces that hint at all of this from different issues and PRs, but I was just hoping to get a more complete answer.

**Comment by faceyspacey** [comment]
Glad you are liking. It’s a major release with a lot of new features. Stay tuned for a blog article shortly.

Ps. Check Reactlandia chat and a comment from earlier today, as well as the feed of GitHub updates in the right column, there’s a comment from a GitHub issue today where I share more than I’ve shared before.

**Comment by edahlseng** [comment]
Awesome, thanks for the clarification @faceyspacey. [That comment](https://github.com/faceyspacey/redux-first-router-link/issues/88#issuecomment-368177865) was super helpful!
