### ISSUE TITLE
Treat hashes as first class citizens for the location state

### ISSUE THREAD

**Issue by edahlseng** [faceyspacey/redux-first-router#212]
I haven't found a way to do this cleanly, but hopefully I just missed it. If I've overlooked something, please let me know.

The problem that I'm experiencing is that hashes don't seem to be treated as first-class citizens within a route. The "intended purpose" of hashes in URLs is to provide a link directly to a specific part of a page. Given that mental model, I would expect `redux-first-router` to expose hashes as a property on the location object. Instead, the workaround that I'm currently using is to create a `routesMap` like this:
```
const routesMap = {
    PAGE: '/place/store/:fruit`,
    'PAGE-HASHES': '/place/store/:fruit#:hash`
};
```
This workaround is necessary to handle both the case where a URL for a page contains hashes and the case where it doesn't. Perhaps this can be cleaned up by supporting hashes as first class citizens within the location state object.

**Comment by faceyspacey** [comment]
it will be in Rudy. stay tuned.
