### ISSUE TITLE
How to integrate redux-first-router and redux-saga (for initial route)?

### ISSUE THREAD

**Issue by christian8287** [faceyspacey/redux-first-router#216]
I wanted to ask how do you normally start the initial route action? It depends where the user enters first. E.g., the user could enter the URL:

http://mysite.org/
http://mysite.org/users
http://mysite.org/users/1

For me the problem is that on entering the single-page-app the first route action is not fired? Do I do something wrong, am I missing something? Beside this issue redux-first-router is just working fine and I am really amazed by it!

Thank you for your help!

**Comment by faceyspacey** [comment]
I think you are doing something wrong. Try re-arranging the order the of your enhancers and/or middleware. Put RFR as close to the beginning as possible.

**Comment by christian8287** [comment]
Thank you very much for your help! Based on your comment I was able to find out what the problem really is. I am using redux-first-router together with redux-saga for async actions. In the log I can see after logging every action that the initial route action is dispatched, but the saga middleware isn't ready at this moment. I have a watchRoute saga which should be called for every route change. Do you have experience with integrating redux-saga and redux-first-router? My code looks like this:

```javascript
const history = createHistory(),
    {reducer, middleware, enhancer} = connectRoutes(history, routesMap), // yes, 3 redux aspects
    sagaMiddleware = createSagaMiddleware(),

    // and you already know how the story ends:
    rootReducer = combineReducers({location: reducer, notifications, my: myReducer, form: formReducer}),

    middlewares = applyMiddleware(sagaMiddleware, middleware),

    // note the order: enhancer, then middlewares
    store = createStore(rootReducer, compose(enhancer, middlewares));

sagaMiddleware.run(rootSaga);

render(
    <AppContainer>
        <Provider store={store}>
            <App/>
        </Provider>
    </AppContainer>,
    document.getElementById('root')
);
```

If you have any idea what I have to change to get this working I would be very thankful!

**Comment by faceyspacey** [comment]
Use option.initialDispatch: true. Search the repo for usage ...it’s made for sagas usage and will resolve this :)

**Comment by faceyspacey** [comment]
Oops I meant initialDispatch: false. It returns a function by the same name from connectRoutes to perform it when ready

**Comment by christian8287** [comment]
Works perfectly! Thank you very very much for your help! :+1:
