### ISSUE TITLE
react-redux as a peer dependency

### ISSUE THREAD

**Issue by Valbrand** [faceyspacey/redux-first-router#22]
I've only noticed today that `react-redux` is listed as a peer dependency here. It shouldn't be there, right?

**Comment by faceyspacey** [comment]
I'm pretty sure it should. U need to install it to work with this lib. All it does is produce warnings if u don't have it installed and let people reviewing the package.json that they have to have it and generally what to expect.

But not everyone bothers to use peer deps.

**Comment by faceyspacey** [comment]
But maybe ur right. Do I need use any of its methods and only Redux methods. If so it probably can and should be removed. Even though it's an implicit dep

**Comment by Valbrand** [comment]
Did this project start with the `Link` component bundled along with the Redux code? That may explain the peer dep being there. I might be wrong, though. I've done a quick search through the repo and only found react-redux in the docs examples

**Comment by faceyspacey** [comment]
Yup that's why

**Comment by faceyspacey** [comment]
handled

**Comment by Positive07** [comment]
Was this fixed somewhere? Should we wait for the next release?

**Comment by faceyspacey** [comment]
it will be in the next release
