### ISSUE TITLE
Workarounds for mapStateToProps getting called with new route immediately before unmount

### ISSUE THREAD

**Issue by waynebloss** [faceyspacey/redux-first-router#221]
I just put this here in case anyone else runs into it and I think something like this should be in the docs.

Anyone working with Redux should know that `mapStateToProps` gets called whenever the state is changed. However, it's easy to forget that each redux-first-router action will change the state and that a components `mapStateToProps` will be called when arriving at a route and also again when navigating away from a route (immediately before the current component is unmounted).

My workaround for this is to simply filter calls to `mapStateToProps`.  I created a function that only calls the target `mapStateToProps` when the current `state.location.type` matches a given value. A simplified version of it is show below.

To use it, you just wrap your own `mapStateToProps` with `filterState`, passing `filterRoute('PAGE_XYZ')` as the first argument.

```js
/**
 * Returns a function that only calls the given mapStateToProps when stateFilter returns true.
 * @param {(state)=> boolean} stateFilter
 * @param {(state: object)=> object} mapStateToProps 
 */
function filterState(stateFilter, mapStateToProps) {
  return function mapStateToPropsFilter(state) {
    if (!stateFilter(state)) {
      return undefined; // This is perfectly fine with Redux, as a way to early-exit mapStateToProps.
    }
    return mapStateToProps(state);
  }
}
/**
 * Returns a function that returns false whenever state.location.type is not equal to the page type.
 * @param {string} type
 */
function filterRoute(type) {
  return function filterRoutePageType(state) {
    if (!state) {
      return false;
    }
    const { location } = state;
    if (!location) {
      return false;
    }
    return location.type === type;
  }
}
```

**Comment by faceyspacey** [comment]
What’s the goal? To prevent unnecessary re-renderings? Or to prevent accidental errors in mapStateToProps because certain state is now undefined?

**Comment by waynebloss** [comment]
The goal for my own usage is to prevent errors in mapStateToProps. Not just because certain state could be undefined, but also because the wrong values would otherwise be taken from my `state.location` payload or query and transformed into props for my page-component, even though that page-component is about to unmount and probably won't be rendered.

This way, each one of my mapStateToProps can be sure that its logic will only run for the intended page type.

**Comment by waynebloss** [comment]
Here's a scenario that happened to me with the undefined state:

1. I navigate to page with a route path of `/:orgId/clients/` called `OrgClientsPage`.
2. The `OrgClientsPage.mapStateToProps` expects `state.location.payload.orgId` to exist, which works just fine the first time its called.
3. However, I click a link on the page to go to `/settings/`, which has no `orgId` in its payload.
4. `OrgClientsPage.mapStateToProps` is then called again, right before navigating away from the page, but this time the `location.state.payload.orgId` doesn't exist.

The other problem that can happen is if you navigate to another page which happens to have an `/:orgId` in its payload, despite it not being the same page type at all. 

The only way to ensure that `mapStateToProps` will not run with incorrect payload and query inputs is to filter calls to it by looking at the `state.location.type` first.

**Comment by waynebloss** [comment]
Just to state the obvious: This is only a problem if you structured your app like me - where you have one module per page type. The solution could also be expanded if you have one module per multiple page types.

However, if you have only one `mapStateToProps` in your whole app, which handles every type of route - then this tactic shouldn't be necessary.

**Comment by faceyspacey** [comment]
When Rudy comes out, we'll have an FAQ + Troubleshooting sections that will be open for quick PRs. If you remember by then, just PR a the short version of the problem + top 3 solutions there.

**Comment by waynebloss** [comment]
I added a better work-around for this. Now I just memoize the `mapStateToProps` return value so that when any navigation occurs, the current "page component" that is about to get unmounted will not even re-render.

I updated the original post with the example.

**Comment by vezzick** [comment]
This was super useful, I found that this behaved slightly differently in my release version and not the debug version, in the debug version it just gives a warning, so it was very tough to debug.

**Comment by cdoublev** [comment]
`prop-types` users may also be confused by this behavior, as I was when I recently decided to use it in my app and a lot of components props that I typed with `PropTypes.<type>.isRequired` were throwing errors because of incoming props derived from state and based from the current route (using `reselect`), that were undefined when route was changing. 

It took me 2 hours to figure out what was happening (but I'm probably not a ninja dev). I think I wouldn't had this issue by using Flow or TS instead of `prop-types`. An FAQ, as faceyspacey is suggesting above, would be nice for the developer experience given to RFR users, as it's not specifically related to RFR but to all react routers solutions.

`mapToPropsForPage` is a nice workaround but I'm not sure that I want to introduce one more abstraction in my head. I feel like removing `.isRequired` or even `prop-types` would be easier, which would be sad as it has been somewhat helpfull.

Anyway, I hope that my comment may at least help RFR/`prop-types` users in the future.

**Comment by cdoublev** [comment]
I just want to let you know that I finally adopted the suggested workaround, as it's worth it to detect real bugs, and I can keep using `prop-types`. As I also use `reselect`, I created the following `createRouteSelector` abstraction, slightly derived from @waynebloss solution.

```js
import { createSelector } from 'reselect'

const createRouteSelector = (type, selectors, select) => {
    const selector = createSelector(selectors, select)
    let lastResult
    return state => {
        if (state.location.type !== type) {
            return lastResult
        }
        lastResult = selector(state)
        return lastResult
    }
}
// Example
const getPost = createRouteSelector(
  'POST', 
  [state => state.posts, state => state.location.payload.id], 
  (posts, id) => posts[id]
)
```

I didn't find a better abstraction using `reselect` API.

**Comment by twelve17** [comment]
Has anyone figured out how to do this with hooks? I'm running into the same problem of a component expecting certain state on a render, which is not present due to the updated path.  It seems odd that there should ever be a use case where it is expected for a component associated with a given path to be rendered with another path (and associated params, etc).
