### ISSUE TITLE
Params started with '0x' are passed as number

### ISSUE THREAD

**Issue by borovik96** [faceyspacey/redux-first-router#222]
I have this path

```javascript
[ROUTE_TOKEN]: {
  path: '/token/:address'
}
```
when `address` is string like `0x454a4ecad748807f1cceb90fc04d7ef3067cd098`. In action I have `address: 0` as payload.

Expected: `'0x454a4ecad748807f1cceb90fc04d7ef3067cd098'` as string

**Comment by faceyspacey** [comment]
as mentioned in your PR we have this in the next major version named Rudy. Thanks for pointing this out though.
