### ISSUE TITLE
Dispatch action with a side effect of opening in new tab.

### ISSUE THREAD

**Issue by ybv** [faceyspacey/redux-first-router#225]
@faceyspacey thanks so much for all the work with redux-first-router, it has made my redux work life a shit ton easier.

I couldn't find it in docs/ issues but, is there a way to dispatch an action to change the route, and open it in a different tab? (possibly via window.open(url,'_blank'); + some middleware that I'm not aware of?)
OR
Am I thinking about it the wrong way, and should i just use https://github.com/faceyspacey/redux-first-router-link  to do something like this?

**Comment by hedgepigdaniel** [comment]
I did something mildly similar to handle actions that needed to result in changing to a different origin.

Basically I made a global `onBeforeChange` callback, which checked all routing actions that went through and in some cases did a `window.location.assign(url)` if the destination was on a different domain. Perhaps you could add a flag to the action and then do something similar except with `window.open`?

**Comment by faceyspacey** [comment]
@hedgepigdaniel 's way is the most robust, as it doesn't require actual `<Link />` components.

Otherwise, you can use the `onClick` prop to do whatever you want and return false:

https://github.com/faceyspacey/redux-first-router-link#familiar-react-router-props

**Comment by ybv** [comment]
Thanks @faceyspacey and @hedgepigdaniel
