### ISSUE TITLE
Using redux thunk in route thunk doesn't return a promise

### ISSUE THREAD

**Issue by psachs21** [faceyspacey/redux-first-router#227]
When I try to dispatch a redux thunk, the result returned is always undefined.

I'm trying to figure out if it's a problem with my store configuration or with the library itself. I've got a route something like the following:

```js
{
  path: '/login',
  thunk: dispatch =>
    dispatch(getUser()).then(() => doSomething());
}
```

Where `getUser` is just a regular thunk action which returns a promise.

```js
const getUser = () => (dispatch, getState) => {
   return new Promise(...);
}
```

My configuration for the store looks like this:

```js
const { reducer, middleware: routingMiddleware, enhancer: routingEnhancer, history: routingHistory } = connectRoutes(routesMap, {
  querySerializer: qs,
  location: state => state.routing
});

const createStoreWithMiddleware = composeEnhancers(
  routingEnhancer,
  applyMiddleware(
    thunkMiddleware,
    routingMiddleware
  )
)(createStore);
```

I realize I can get around this (at least at the surface layer) but I thought maybe something was up with my configuration.

**Comment by psachs21** [comment]
I am using the 0.0.8-rudy. Of interesting note, 1.9.15 does not have this problem.

**Comment by faceyspacey** [comment]
fixed :)

https://github.com/faceyspacey/redux-first-router/commit/9c3822a2c224752b1aae3e66c6525f6d56aec25f#diff-e93dc268a463b8fa67c0b201239bcbc8R384

**Comment by faceyspacey** [comment]
upgrade to 0.0.9

**Comment by psachs21** [comment]
Wow. I should have been able to spot that one. Thanks @faceyspacey!
