### ISSUE TITLE
Default url

### ISSUE THREAD

**Issue by osipovvictor** [faceyspacey/redux-first-router#228]
Hi! I have a use case: settings page with tabs like 'account', 'notification' etc, are available on `/settings`. By default on `/settings` I want to show account tab, so it will be logical to change URL to` /settings/account`. How can I do that?

**Comment by faceyspacey** [comment]
```js
const routes = {
   SETTINGS: '/settings/:page?'
}

const pageReducer = (state, action) =>
   action.type === 'SETTINGS' ? action.payload.page || 'settings' : state

dispatch({ type: 'SETTINGS' })
dispatch({ type: 'SETTINGS', payload: { page: 'notifications' })
```

should do the trick.
