### ISSUE TITLE
Add query params to window.location without a route change

### ISSUE THREAD

**Issue by aryzle** [faceyspacey/redux-first-router#229]
Hey there!

I'm wondering if you could help me with a little problem. I'm trying to set some state in my url so that I can share a link to a friend and she can then open the page up with my same state.

A small example is going to a show's page and having the season selected with, say, a seasonId passed as a query param in the url

/shows/rick&morty?seasonId=2

I want to append this seasonId query param to the url when I choose that season and then be able to just copy paste it to my friend. I don't want the route to change however because that opens up a can of worms.

Currently I'm trying to just pass an action that has the same path and a new query in its payload according to your docs but it registers as a route change 😞

```
dispatch({
  type: 'SHOW',
  payload: {
    show: 'rick&morty',
    query: {
      seasonId: selectedSeason.id,
    },
  },
});
```

Any way to do a silent update? am I thinking about it wrong?

would love to hear your advice/thoughts

**Comment by aryzle** [comment]
also assume this episode list with a season selector is on other pages, so a dedicated route like

`/shows/rick&morty/season2`

would not work in this case. Just a constraint I forgot

**Comment by faceyspacey** [comment]
what "can of worms" does it open up? That's how it's supposed to be done, or how your app reactively respond to it? Perhaps through other means like `setState` separately within components, but that's moving away from the "single source of truth" principle in terms of your location state.

It's likely not going to be able to happen without the re-render in the current version. If it's work in reducers checking this query value that you gotta change, you likely just gotta change your reducers for this case. 

However, if it's work related to cross cutting concerns like scroll restoration, code splitting etc, in the next version there will be ways to configure non-state-related work that happens as a result of URL changes. You will be able to treat *non-essential* parts of the URL as secondary, and skip optional behavior of the cross cutting concerns.

**Comment by mattoni** [comment]
Is there a way to do this for a hash? I want a user to be able to click on a header and add it to the url like `/test#id-of-anchor`. It doesn't need to rerender or anything, and I'll probably use the restore scroll package to jump to it, but how can I add it to the URL?

**Comment by faceyspacey** [comment]
basic links with `#something` should work. using our `<Link />` component may or may not work when providing paths. If it gets erased, use real links for this case. The next version has full support for this stuff.
