### ISSUE TITLE
[Question]: How can I address redirects efficiently with a more complicated scenario than the example

### ISSUE THREAD

**Issue by brendanwheble** [faceyspacey/redux-first-router#23]
Firstly, I'm current using react/redux/react-router but I'm keen to drop react-router.
I've read your docs on redirecting but I'm not 100% sure how I can use it without repetition

Imagine I have the following routes (a greatly reduced list!):

/a
/a/a1
/a/a2
/b
/b/b1
/b/b2
/admin
/login

My app requires authenticated users so my top level route (/) checks for a user session and redirects to /login if the user isn't logged in. Simple to achieve in react-router

The user then needs a specific permission to access the nested routes e.g. /a, /b, /admin or they're redirected to /login

Now I could duplicate this logic for every distinct path in redux-first-router (using a helper function) but this will get tedious when the list of paths is long. Am I missing something?

**Comment by faceyspacey** [comment]
Hey there. There's the onAfterChange callback provided as an option for exactly this. Check the docs page containing options. It takes a dispatch and getState. Check state.pathname and redirect to login if ur user auth state is negative.

**Comment by faceyspacey** [comment]
Also use the redirect action creator. There's a redirect example linked from the homepage in the links of the page near the bottom. It does a replace instead of a push.

**Comment by brendanwheble** [comment]
Sounds like a plan. Cheers

**Comment by faceyspacey** [comment]
@brendanwheble you're gonna love the latest update to the Demo:

https://github.com/faceyspacey/redux-first-router-demo

It's major. It includes lots of authentication filtering stuff. It has SSR + Code Splitting. There's also updates to this package. So update your deps. The takeaway is redirect in `onBeforeChange` if not authenticated.

**Comment by brendanwheble** [comment]
I've now replaced react-router with redux-first-router and I'm happy with the results. When combined with redux-logic my components now seem much cleaner and focused on simply rendering. Nice work!

**Comment by faceyspacey** [comment]
That's awesome. Let the world know.

Id love to see an example of some stuff u did.
