### ISSUE TITLE
Thunk of pathless route is not called at the server-side

### ISSUE THREAD

**Issue by Oopscurity** [faceyspacey/redux-first-router#230]
Hello,

Thank you for wonderful library.

I use `redux-first-router@0.0.20-next` with pathless routes support included to evaluate route related thunks without actual url change. Pathless routes' `thunk`s work perfectly at the client-side but they are completely useless at the server-side not being called automatically with `redux-first-router` provided middleware.

Since the middleware finishes handling pathless route transition action right after calling `attemptCallRouteThunk()` ([`connectRoutes.js:251`](https://github.com/faceyspacey/redux-first-router/blob/next/src/connectRoutes.js#L251)) without location state change, it looks like there's no way to achieve desired behaviour at the server-side someway.

Is there any way to add SSR support of pathless routes' `thunk`?

Something like adding touched pathless routes to the queue to evaluate their `thunk`s further with `connectRoutes()`'s [`thunk()`](https://github.com/faceyspacey/redux-first-router/blob/next/src/connectRoutes.js#L578)?

Or since pathless routes transition can be performed with "common" routes' `thunk` (such as it is in your [example](https://gist.github.com/faceyspacey/2771c05a62a338fa6d3d23d76e6e7c5a#file-pathless-routes-with-redux-first-router-js-L12)), maybe additional function like `connectRoutes()`'s `thunk()` is welcome to avoid calling `thunk()` twice with the same effect as a first call.

Finally, it can be reasonable to manage the pathless (and "common" maybe) routes's `thunk` call queue to perform as many `connectRoutes()`'s `thunk()` call cycles until the queue is empty.

**Comment by faceyspacey** [comment]
The next major version has full support for this. It will be out in a few weeks. Glad you're enjoying the library.
