### ISSUE TITLE
Custom basename missing in links

### ISSUE THREAD

**Issue by psachs21** [faceyspacey/redux-first-router#231]
I wasn't sure if this issue/question belongs here or in redux-first-router-link.

I've setup redux-first-router (rudy or 1.9.15) with a custom basename:

store
```js
import createHistory from 'history/createBrowserHistory';

const history = createHistory({ basename: 'BASENAME' });

const { reducer, middleware, enhancer } = connectRoutes(history, routesMap, {
	querySerializer: qs,
	location: state => state.routing
});
```

Adding links like so:

```
<Link to={{ type: 'INBOX' }}>Whatever</Link>
```

And I've noticed that if i open the link in a new tab, it navigates to `/inbox` and not `BASENAME/inbox`. Looking at the html, the anchor generated by <Link /> has an href of '/inbox' instead of what i expected. Clicking it works fine. 

Did I configure something wrong?

**Comment by faceyspacey** [comment]
That's a tough call, as the concept is to preserve the link juice (in terms of SEO) of the primary URL, while allowing different-language users to receive a language-specific experience.

Ideally it would be configurable. Or perhaps it's the wrong idea to preserve link juice, and make it easier for google to tell the difference between different language versions of the same page (or similar for use-cases other than language).

**Comment by faceyspacey** [comment]
yea, we should get rid of that. i'll make sure it's in the next version which is *almost* out.

**Comment by psachs21** [comment]
Actually, the issue I was having was I was using the wrong version of redux-router-link and it wasn't picking up the basename. Pretty silly mistake really. Anyways, super excited to see what the next release looks like. Thanks @faceyspacey
