### ISSUE TITLE
Routing with wildcard paths is impossible

### ISSUE THREAD

**Issue by stezu** [faceyspacey/redux-first-router#234]
I've been using this router for a week and finally ran into my first major issue that's so far been impossible to work around. The code in master would seemingly allow a workaround, but the code deployed to NPM does not.

As a bit of back story, I am using `redux-first-router` as a top-level router for my app, and everything but the first level is handled by other child apps with their own routers. I am using wildcards in my route configuration like this:

```js
const routesMap = {
  ROUTE_APP_A: {
    path: '/appA(.*)',
    ...,
  },
  ROUTE_APP_B: {
    path: '/appB(.*)',
    ...,
  }
}
```

That configuration works fine for most cases except for when I dispatch an action which includes paths that to take the place of the wildcard. This is an example of the action I'm dispatching:

```js
dispatch({
  type: 'ROUTE_APP_A',
  payload: { 0: '/subRoute' }
});
```

The router will run through this code in `pure-utils/actionToPath.js` with each item in the payload:
```js
var transformSegment = function transformSegment(segment, route, key) {
  if (typeof segment === 'string') {
    if (segment.indexOf('/') > -1) {
      return segment.split('/');
    }

    if (route.capitalizedWords === true) {
      return segment.replace(/ /g, '-').toLowerCase();
    }

    if (typeof route.toPath === 'function') {
      return route.toPath(segment, key);
    }

    return segment;
  } else if (typeof segment === 'number') {
    return segment;
  }
};
```

It hits the first check `segment.indexOf('/') > -1`, and splits the string to an array of `['', 'subRoute']`.

Eventually, that param gets to [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp/blob/master/index.js#L154) which throws the following error:
```
TypeError: Expected "0" to not repeat, but received `["","subRoute"]`
```

The error is swallowed by `redux-first-router` [here](https://github.com/faceyspacey/redux-first-router/blob/master/src/action-creators/middlewareCreateAction.js#L28) and then it routes to the not-found page.

The code that is currently in master could provide a workaround since `route.toPath` is called, but that's still not a clean solution.

For reference, I'm using `0.0.16-next` which is the current "latest" tag on NPM.

**Comment by faceyspacey** [comment]
use named regexes:

```
SECOND: {
    path: '/appA/:subRouteName(.+)'
  },
```

That should make the action become:

```
dispatch({
  type: 'ROUTE_APP_A',
  payload: { subRouteName: 'subRoute' }
});
```

**Comment by stezu** [comment]
Thanks @faceyspacey, that works for one level, but not for two or more levels. Since I'm using this only as a top level router, the child apps can add as many levels as they want on top.

I really just want to dispatch an action that takes an arbitrary string route and appends it to the base path I configured in my `routesMap`. With your suggestion, I could theoretically add a workaround with a bunch of optional named regexes and then some code to split my arbitrary string on slashes and name each segment, but that seems more like a hack than a solution.

**Comment by faceyspacey** [comment]
does this work (taking from tests from the upcoming version, which should still work here):


createTest('optionally match "multi segment params" as single param', {
  REPO1: {
    path: '/repo1/:user/:repo/blob/:branch/:filePath*'
  },
  REPO2: {
    path: '/repo2/:user/:repo/blob/:branch/:filePath*'
  }
}, [
  {
    type: 'REPO1',
    params: {
      user: 'faceyspacey',
      repo: 'rudy',
      branch: 'master'
    }
  },
 ```

`:filePath` can be a url to a file like on a github repo `/foo/bar/bla` -- and its named

**Comment by faceyspacey** [comment]
u can even do multiple:

```js
createTest('match MULTIPLE "multi segment params" as single param', {
  SECOND: {
    path: '/second/:segments1+/bla/:segments2+'
  },
  THIRD: {
    path: '/third/:segments1+/bla/:segments2+'
  }
}, [
  {
    type: 'SECOND',
    params: {
      segments1: 'foo/bar',
      segments2: 'baz/yo/sdf'
    }
  },
  '/third/foo/bar/bla/baz/yo/sdf'
])```
