### ISSUE TITLE
What's the best way to write error-handling code whenever there are uncaught errors in the thunks?

### ISSUE THREAD

**Issue by w9** [faceyspacey/redux-first-router#235]
My current way of using the lastest RFR is to have all my page data retrieval in the RFR routesMap thunks. I want that whenever an uncaught error happens (usually when the params in the url don't make sense to my database queries) the page is redirected (e.g. to NOT_FOUND). What I usually end-up doing is writing this boilerplate for each route:

```
  [USER_PROFILE]: {
    path: '/user-profile/:userId',
    thunk: async (dispatch, getState, { action: {userId}, extra: { apolloClient } }) => {
      try {
        const someData = await apolloClient.query(...)
      } catch (e) {
        console.error(e);
        dispatch(redirect({ type: NOT_FOUND }));
      }
    },
  },
```

this error catching code has to be repeated for each route which can get tedious. Is there a better way to put my error handling code?

**Comment by faceyspacey** [comment]
I'm almost done with the next major version and we have built-in error handling. But yea, this can get a bit tedious, and @psachs21 technique is basically the best way to reduce code redundancy. 

The other technique, again as @psachs21 suggested, is to essentially iterate through all your routes and automatically apply it. It's a solid practical solution.
