### ISSUE TITLE
Double handling location change

### ISSUE THREAD

**Issue by KoalaHuman** [faceyspacey/redux-first-router#237]
This check https://github.com/faceyspacey/redux-first-router/blob/rudy/src/connectRoutes.js#L544
```javascript
if (nextPath !== currentPath) {
```
will fail when the url has special characters because `currentPath` is taken from the browser location and is not put through `decodeURIComponent`,  which will result in additional action dispatch.
Example using redux-first-router-boilerplate (with rfr 1.9.15, but this also happens in rudy branch)
https://github.com/KoalaHuman/redux-first-router-boilerplate
Check the React% link at the sidebar, clicking it will dispatch 2 LIST actions (with different metas) as well as call LIST's thunk twice.
Is this the intended behavoir?

**Comment by faceyspacey** [comment]
In the next version we'll have way better support for special characters, and lower level customization. I'm going to close this for now, but stay tuned for the next major version.

**Comment by KoalaHuman** [comment]
Great, looking forward to it 🚀
