### ISSUE TITLE
Role-Based Permissions

### ISSUE THREAD

**Issue by christian8287** [faceyspacey/redux-first-router#239]
Hi!

I wasn't able to find it in the docs, therefore I wanted to ask this question here. How do you guys with redux-first-router integrate role-based permissions. For example role X is allowed to open Url "/manage" and role Y is not allowed to open this url... Is there any good integration? Would it be an option to add this subject to the docs?

Thank you very much!

**Comment by NicholasGWK** [comment]
I've been using onBeforeChange, but this is difficult for a lot of things presently since it is not promise aware. This means if you have to hit the server or to check a permission, you can get some flicker without some frontend gymnastics (setting a flag to "checking" or something).

This should be different in the upcoming version of Rudy, but for now it seems like onBeforeChange is a good spot, or thunks.

**Comment by faceyspacey** [comment]
@NicholasGWK thanks again for helping out with these answers.

Basically you would have:

```js
const routesMap = {
   DASHBOARD: {
      path: '/dashboard',
      roles: ['admin', 'member']
   },
   LOGIN: '/login'
}

const options = {
   onBeforeChange: (dispatch, getState) => {
      const { user, location: { type } } = getState()

      if (!routesMap[type].roles.includes(user.role)) {
         dispatch(redirect({ type: 'LOGIN' }))
      }
   }
}
```

As @NicholasGWK 's promises will be supported shortly, but you don't need them. If in the future you were to use that strategy, you'd have to make an additional async request for every route change. Instead--and what you can do currently--is find the user once and store his/her role in Redux state, and synchronously check it. Obviously for ajax requests, you'll want to verify access as well (which is the real security here). This is a common strategy for dealing with client side routing--i.e. just check an easily manipulatable role for the user, *but then fail to actually retreive any data when ajax requests fail to authenticate the user*. 

You can use JWTokens to authenticate user's server-side on every ajax request without an additional hit to the db.

**Comment by NicholasGWK** [comment]
No worries! Happy to help :)
