### ISSUE TITLE
Authentication best practices with Redux First?

### ISSUE THREAD

**Issue by bmoquist** [faceyspacey/redux-first-router#24]
**First off, this is great work -- thanks for making this! I'm so happy to have everything in Redux.** 

Could you provide some pointers/best practices on how authentication fits into this (examples would be amazing)? To be more specific in my case, I've been looking at this library for Amazon Cognito, which nicely holds user state in Redux: https://github.com/isotoma/react-cognito

With this library and React Router, one creates a guard
```
const guard = createGuard(store, '/forbidden');
```
and then passes it to onEnter in the Route to determine whether to show the user the route or redirect elsewhere if needed.
```
<Route
     path="/change_email"
     component={updateEmail}
     onEnter={guard()}
/>
```
What's the best way to do something like this/handle authentication and routing with Redux First?
Appreciate the help!

**Comment by faceyspacey** [comment]
Glad u like it. I'm ending my day. I can help more later but try this: in options.onAfterChange u r passed getState as the second param. Compare the pathname in the location state and if it passes call guard.

U could also use a thunk in a route with the same path, but those are primarily for data fetching and should be kept that way.

**Comment by faceyspacey** [comment]
Also write a blog article if u love it. Sooner than later. Trying to blow this up. More support for u :)

**Comment by faceyspacey** [comment]
Also check the redirects example. Linked from the readme. There is a redirect action creator for redirecting for auth. It's the only exported ac and one of the few such anomaliees making up the API surface

**Comment by faceyspacey** [comment]
Do u really need createGuard? If not u redirect urself in thunks when conditionss aren't met.

**Comment by faceyspacey** [comment]
Ok I'm out. Good luck. Let me know how it goes.

**Comment by bmoquist** [comment]
Thanks much for the suggestions -- I'll test them out, and let you know how it goes!

**Comment by faceyspacey** [comment]
@brendanwheble you're gonna love the latest update to the Demo:

https://github.com/faceyspacey/redux-first-router-demo

It's major. It includes lots of authentication filtering stuff. It has SSR + Code Splitting. There's also updates to this package. So update your deps. The takeaway is redirect in `onBeforeChange` if not authenticated.
