### ISSUE TITLE
Navigate without Link/NavLink

### ISSUE THREAD

**Issue by christian8287** [faceyspacey/redux-first-router#240]
I wasn't able to find something about this in the docs. I have a use case where I want to navgiate to a certain page without using Link/NavLink. I looked at the source code of redux-first-router-link and found the following code:

`dispatch(pathToAction(url, routesMap, serializer))`

Is this the code which is needed to dispatch an action that navigates to a different page?

Nevertheless, I think it should be added to the docs. I hope that I didn't read over the part where it is but wasn't able to find it.

**Comment by NicholasGWK** [comment]
You should be able to just dispatch an action of the type that corresponds to the route you want based on your routesMap! So if you had something like this:

```const routesMap = {
  SOME_ROUTE: '/theRouteYouWant',
}```

You can just do `dispatch({ type: SOME_ROUTE })` and it should take you there!

**Comment by faceyspacey** [comment]
Yea, links are required. The whole system is setup to be *just redux*. Links are optionsal. Just dispatch an action that matches a type in your routesMap. Any params in the route's path must have keys in your payload.
