### ISSUE TITLE
Too big numeric strings do not parse correctly.

### ISSUE THREAD

**Issue by TomiHiltunen** [faceyspacey/redux-first-router#242]
The current default behavior of parsing path params from strings to numbers breaks IDs with too big numeric values.

Original string value: `"794533627949140550"`
Parsed number: `794533627949140600`

**Comment by zackljackson** [comment]
Commented on PR, but for historical references: Cause is JavaScripts uses the IEEE 754 double precision floating-point. That means, you have a maximum of 52 bits of precision, which is a bit more than 15 decimal places.

**Comment by faceyspacey** [comment]
The next major version will allow for complete customization of URL parsing. Thanks for drawing our attention to this particular case @TomiHiltunen
