### ISSUE TITLE
The thunk middleware should return what the thunk returns

### ISSUE THREAD

**Issue by w9** [faceyspacey/redux-first-router#244]
According to [this post](https://github.com/reactjs/redux/issues/1676), in the original redux-thunk middleware, the call:

```javascript
const res = store.dispatch({ type: 'MY_THUNK' });
```

should return whatever is returned by the thunk function. This is especially important when the thunk function is async, as it returns a Promise, and allows for thunk chaining:

```javascript
await store.dispatch({ type: 'MY_THUNK_1' });
await store.dispatch({ type: 'MY_THUNK_2' });
```

Right now, the thunk middleware in redux-first-router returns the action itself, which is almost never useful.

**Comment by faceyspacey** [comment]
This is addressed in the next major version
