### ISSUE TITLE
Redirect to external URL

### ISSUE THREAD

**Issue by mrceperka** [faceyspacey/redux-first-router#245]
Hello :wave: 
I've struggled with redirecting to external URL. However, I've managed to solve it.
```js
import { NOT_FOUND, redirect } from 'redux-first-router'
export const goToUrl = (url) => redirect(
  { meta: { location: { current: { pathname: url } } } },
  NOT_FOUND
)
```
But it does not feel right. I am using `NOT_FOUND`, because I have to pass through  [if statement](https://github.com/faceyspacey/redux-first-router/blob/master/src/reducer/createLocationReducer.js#L18) in reducer. I could probably add my own `REDIRECT_TO_EXT_URL` to my `routesMap` and it would pass too (but I'd had to pass more conditions).

Is there any better way how to do this? Like built in?

:pray: Thanks for the answer

**Comment by faceyspacey** [comment]
If it's external, you should do `window.location = externalUrl`.

**Comment by mrceperka** [comment]
I am doing this in `thunk`, so it is server side.
I am also using
```js
export const doesRedirect = ({ kind, pathname }, res) => {
  if (kind === 'redirect') {
    res.redirect(302, pathname)
    return true
  }
  return false
}
```
which I've taken from the demo-app.

**Comment by faceyspacey** [comment]
ic. ..so server side, if you want to redirect to an external URL, it's really up to you. you can dispatch any indicator (and perhaps use your own additional reducer) to store the info of what external site to redirect to. There's no idiom ultimately. I wouldn't worry about it, and just do what feels right to you.
