### ISSUE TITLE
doing a redirect within onBeforeChange is losing basename

### ISSUE THREAD

**Issue by pjnovas** [faceyspacey/redux-first-router#246]
Hey, thanks for this awesome work!

**Version**: `redux-first-router@0.0.9-rudy`

I'm not sure if I'm doing something wrong but I have this on my router:

```js
import { connectRoutes, redirect } from 'redux-first-router'

connectRoutes(
  {
    'HOME': '/',
    'GROUPS': '/groups'
  },
  {
    basename: '/base/path',
    onBeforeChange: (dispatch, getState, {action}) => {
      if (action.type === 'HOME') {
        dispatch(redirect({type: 'GROUPS'}));
      }
    }
  }
);
```

**Expected behavior:** when I go to `/base/path` I get redirected to `/base/path/groups`
**Actual behavior:** when I go to `/base/path` I get redirected to `/groups`

I have simplified all my code for the sake of this issue, `basename` is working fine for all routes this only happens on the `kind: 'redirect'` so I'm not sure if is a bug or I should be doing something else in there.

Thanks!!!

**Comment by zackljackson** [comment]
I’m currently digging around in the basename stuff. I’ll get back to you on if this is in fact a bug. I’ll check it against the lastest dev branch. If it’s a bug there, then I’ll patch and PR it. 

Otherwise I’ll need a few days before I can address it

PR is always welcome 🤗🙂

**Comment by pjnovas** [comment]
@zackljackson thanks!, an update around this.

I have a `doesRedirect` function (which I took from your example project), so updating it by adding the basename get this to work (I'm on nodejs side tho, this would be on first render from SSR).

```js
const doesRedirect = ({ kind, pathname }, res) => {
  if (kind === 'redirect') {
//    res.redirect(302, pathname);
    res.redirect(302, `/base/path${pathname}`);
    return true;
  }
};
```

First parameter is from `store.getState().location`; so I think (and idk if is possible) that location should have the `basename` somewhere (which was already pre configured by `connectRoutes()`)

something like:
```js
const doesRedirect = ({ basename, kind, pathname }, res) => {
  if (kind === 'redirect') {
    res.redirect(302, `${basename}${pathname}`);
 // or pathname would already has it
    return true;
  }
};
```


Those are my 2 cents on this, hope it helps and thanks again for your work!

**Comment by faceyspacey** [comment]
@pjnovas the next major version of RFR will have basename support exactly as you're saying. For now you need to store it somewhere yourself and prepend it. You're doing this server-side so you can get it out of `req.path` and see if the first segment(s) match a basename you're using.

**Comment by pjnovas** [comment]
awesome thanks!
