### ISSUE TITLE
Ability to cancel takeEvery via a route change

### ISSUE THREAD

**Issue by whnunlife** [faceyspacey/redux-first-router#250]
I looked thru the source code and am unable to find, any type of event that I can import into my sagas, to cancel any dispatches until the route is loaded again.

In react boilerplate, I would be able to implement this via the following.

```
import { take, call, put, cancel, takeLatest, all } from 'redux-saga/effects';
import { LOCATION_CHANGE } from 'react-router-redux';

export function* sitesRequestSaga() {
  const watcher = yield takeLatest(GET_SITES, callSitesRequest);

  // Suspend execution until location changes
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}

```

Is there anything similar to `LOCATION_CHANGE` that I can include in my saga and be notified when a route has been changed?

**Comment by faceyspacey** [comment]
We aren’t based on one action/event. Every action type can be such an event. Which is part of the secret sauce here. You need to take all keys of your routes map. You can use Object.keys.
