### ISSUE TITLE
Create PREFIX constant from NOT_FOUND

### ISSUE THREAD

**Issue by madurmanov** [faceyspacey/redux-first-router#252]
Sometimes in big projects we need avoid collisions of constants names. For this we can use helper function of concatenate our actions names with some prefixes. In `redux-first-router` used `@@redux-first-router` prefix for `NOT_FOUND` constant. I guess what all types of routes constants should have one prefix. What about cut out `@@redux-first-router` from `NOT_FOUND` constant to `PREFIX` constant?

Something like this:
```
export const PREFIX = '@@redux-first-router'
export const NOT_FOUND `${PREFIX}/NOT_FOUND`
```
Example of helper function:
```
export const prepareConstants = (constants, prefix) =>
  constants.reduce((acc, constant) => ({
    ...acc,
    [constant]: prefix ? `${prefix}/${constant}` : constant,
  }), {})
```
Example of use:
```
import { PREFIX, NOT_FOUND } from 'redux-first-router'
import { prepareConstants } from 'utils'

const PAGES = prepareConstants([
  'HOME',
], PREFIX)
PAGES.NOT_FOUND = NOT_FOUND

export const PAGES
```

Thank you.

**Comment by faceyspacey** [comment]
The next version has this capability. Thanks for the feedback.
