### ISSUE TITLE
Browser back and forward buttons refresh the page

### ISSUE THREAD

**Issue by deepfriedbrain** [faceyspacey/redux-first-router#254]
I've a React / Redux based app, which uses my custom routing scheme using URL hash. I had tried to use react router couple years ago, but gave up because of several issues that I encountered at that point. Recently I started to relook at routers, and came across Redux Little Router and learned how it solves the problems with React Router for Redux based applications. From there I discovered Redux First Router. I found this very promising and started to play around with it. 

However, I noticed one problem when using the Sandbox example. When I use the browser back/forward buttons, the whole page is refreshed. But if the action is initiated from within the app, the page is not refreshed. My current implementation doesn't have this issue. 

Here's how my app works today -

I have 4 tabs with names and URLs shown below:

    Tab Name | URL
    =======================
    tab1 | /app#tab1
    tab2 | /app#tab2
    tab3 | /app#tab3
    tab4 | /app#tab4
    =======================

When user clicks on any tab inside the application, the URL automatically changes accordingly without any page refresh. Each tab maintains it's state (including scroll positions). And when user uses the browser back/forward buttons, it behaves the same i.e. page is not reloaded and all the state is maintained. 

But without the hash, the whole page is refreshed and state lost if user navigates back and forth using the browser back/forward buttons. I think I would need to continue using the hash URLs. Can you help me figure out how to configure the router to work with hash URLs? 

Another question - I'm confused about the branch that I should be using. Since I'm started afresh, should I go with the master or the Rudy branch? I cannot find clear documentation on this.

Thanks.

**Comment by faceyspacey** [comment]
Use the rudy tag on npm.

Currently we don’t have full support for hashes. The next version will have it.

But there should be no problem with the browser buttons. Code sandbox has issues here because they use an iframe and fake the browser buttons. Codesandbox originally didn’t have this issue but they changed their implementation. Try the boilerplate and you wouldn’t have that issue.
