### ISSUE TITLE
Enhance action in onBeforeChange 

### ISSUE THREAD

**Issue by belgac** [faceyspacey/redux-first-router#255]
Hello, i'm looking for a way to enhance the current route action in onBeforeChange.

My concrete usecase goes as follows: i get a token from an external library in onBeforeChange and i would like to add it to the payload or meta of the current route action to use it in subsequent middleware/thunks.

Is there an "official way" of doing this?

**Comment by faceyspacey** [comment]
Add it to your context/api object, which is passed as the third argument to callbacks.
