### ISSUE TITLE
Scroll restoration does not work with asynchronously loaded pages

### ISSUE THREAD

**Issue by edahlseng** [faceyspacey/redux-first-router#257]
When content on a page loads asynchronously and affects the overall height of the page, scroll restoration does not work. To reproduce the error, find a page with asynchronously loaded content, and scroll down the page. Refresh. The scroll restoration will scroll partly down the page at initial load, but will remain there once the asynchronous content is rendered. This occurs even with the `redux-first-router-restore-scroll` package added, and with a promise being returned from the route's thunk.

Looking into the problem, it appears that there are two causes for this error:
1. `redux-first-router` is looking for a `next` function on a thunk's promise, rather than a `then` function. ([src/pure-utils/attemptCallRouteThunk.js, lines 29 and 30](https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/attemptCallRouteThunk.js#L29-L30))
2. `redux-first-router` attempts to update the scroll position in the middleware ([src/connectRoutes.js line 352](https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L352)) and in the enhancer ([src/connectRoutes.js line 451](https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L451)). One of these updates appears to trigger the `onWindowScroll` event within the `scroll-behavior` package, resetting the saved scroll position. This means that even if problem 1 is fixed, the scroll position would still not properly update with asynchronous content. Beyond this information, I haven't worked out how to fix this issue, whether there's some API that can be used with `scroll-behavior`, whether the update scroll process needs to be bypassed within the middleware and enhancer if a promise is returned from a thunk, or something else.

If I change `next` to `then` as described in number 1, and comment out the `_updateScroll` lines linked in number 2, then everything works as expected.

It's critical that I solve this issue relatively soon, so I'm happy to submit PRs to fix this, but I need some guidance on how to solve problem number 2.

**Comment by zackkirsh** [comment]
@faceyspacey lets make sure we solve this in Rudy

**Comment by faceyspacey** [comment]
As I recall I set it up so you can call the updateScroll method manually. Our restore scroll package should have some hints.

In the next version we have a new way of dealing with this.

**Comment by edahlseng** [comment]
@faceyspacey, we can call the updateScroll method manually, but there's issues with doing that due to point 2 that I listed above. Furthermore, it looks like this was intended to handle thunks in the first place, which means that there is a bug causing this to not be handled properly.

While it's great that there will be a new way of dealing with this in the next version, if that next version is not going to be released in the immediate future then I think this issue should be reopened and these bugs should be fixed. I'm happy to do the work, I'm just looking for a little more background on point 2.
