### ISSUE TITLE
Flow complains on NOT_FOUND import

### ISSUE THREAD

**Issue by ferborva** [faceyspacey/redux-first-router#259]
I'm finding myself facing a bit of an odd issue ... I'm using the 1.9.19 version (latest) and am importing the NOT_FOUND constant for use in my reducer, page switches ...

This is how I'm importing:
`import { NOT_FOUND } from 'redux-first-router';`

And this is how flow complains:
`
[flow] Named import from module 'redux-first-router' (This module has no named export called 'NOT_FOUND'.)
(alias) const NOT_FOUND: "@@redux-first-router/NOT_FOUND"
`

So followed on to the definition of NOT_FOUND in the RFR module. My IDE took me to `index.d.ts` file where I see the following:
`export const NOT_FOUND: '@@redux-first-router/NOT_FOUND';`

Very odd given that in the src I can clearly the that NOT_FOUND is being correctly exported ... Any ideas as to what this can be and how to fix it??

:(
In the meanwhile I've put a workaround in place and have created a constant in my code with the expected value. ie `export const NOT_FOUND = '@@redux-first-router/NOT_FOUND';`

**Comment by faceyspacey** [comment]
I'm pretty sure this flow issue is solved in the rudy tag on NPM. Do `yarn upgrade redux-first-router@rudy`. That's what we're all using these days. It has very minor differences from the latest, which are listed at the top of the repo.

**Comment by ferborva** [comment]
Fair enough. I think I'll keep the work around in place for the moment for a couple reasons though:
- installing rudy gets me a 0.0.x version. Doesnt' seem a production ready realease (I guess if it was I would be the latest release)
- none of the rudy/next changes are in the docs so I wouldn't like to count on them yet

Thanks for the info though. I will keep an eye out for the next release 👍 Lovin RFR
