### ISSUE TITLE
Consider adding lib type definitions to flow-typed

### ISSUE THREAD

**Issue by DrummerHead** [faceyspacey/redux-first-router#26]
https://github.com/flowtype/flow-typed

Since you're already using flow and even flow-typed itself :) could be a differentiation factor "against" redux-little-router ([which isn't in flow-typed either](https://github.com/FormidableLabs/redux-little-router/issues/148))

Cheers!

**Comment by faceyspacey** [comment]
Good call. Will do soon. 

...also note, we have TS types thanks to @Valbrand:

https://github.com/faceyspacey/redux-first-router/issues/19#issuecomment-310058348

**Comment by faceyspacey** [comment]
is there a super automated way to get the flow-types into flow-typed? I've just been publishing the flow types via `flow-copy-source`, but that has a few issues (as I recall) that just makes it better to have it in the flow-typed directory.

all the types for this project are in `src/flow-types.js`. Any help is much appreciated. 

U get a chance to use this yet?

**Comment by Valbrand** [comment]
I risk making an ignorant assumption here, but is there a need for publishing the types in `flow-typed`? Isn't it possible to ship the types along with the npm package?

**Comment by faceyspacey** [comment]
That's what I do via flow-copy-source but I read somehwere it's not as good. It has something to do with

**Comment by faceyspacey** [comment]
I'm just gonna close this since we do provide types in the package that exist in your `node_modules` folder. If someone comes back and says it really needs to be on *flow-typed*, we'll address it then.
