### ISSUE TITLE
NOT_FOUND redirect behaves differently than one for any other route

### ISSUE THREAD

**Issue by cake-jnorman** [faceyspacey/redux-first-router#261]
First, the obligatory "thank you" for providing the community with the clear successor to React-router.  There's definitely a lot i love about RFR.

And now the reason that I am here.  

**The setup - I have the following route:**
```
  SOME_ROUTE: {
    path: '/some-route',
    thunk: (dispatch, getState) => {
      const state = getState();
      if (!state.location.query || !state.location.query.id) {
        dispatch(redirect({ type: NOT_FOUND })); // we treat a missing qs param as a 404
      }
      return getSomeData(state.location.query.id)
        .then((resp) => {
          dispatch(mappers(resp.data));
        })
        .catch((error) => {
          const status = Math.floor(error.response.status / 100);
          console.log(status);
          if (status === 4) {
            dispatch(redirect({ type: NOT_FOUND })); // server gives us a 4xx, treat it as such
          } else {
            const action = redirect({ type: 'OOPS' }); // server gives us a 5xx - we call this an OOPS
            dispatch(action);
          }
        });
    },
  },
  OOPS: {
    path: '/oops',
  },
  [NOT_FOUND]: {
    path: '/not-found',
  },
```

Basically, if we have a 4xx server error, we show the not found page because this is in alignment with our UI experience.  (religious debate over this somewhere else please)

BUT, if we have a 5xx server error, we want to treat this as 'something went wrong' aka 'oops'.  

**The problem**
The OOPS route is triggered in the code above, and the corresponding component does get rendered.  (WOOT!)  Then, the current route takes over and the /some-route's component gets rendered after the /oops route.  So what finally gets rendered is the /some-route component, and with missing data! (SAD-FACE!)

From what I understand i *could* use some of the event lifecycle methods to handle this situation, but I'd REALLY like to handle this redirect here, and have it be honored like the NOT_FOUND route.  The fact that NOT_FOUND is treated differently is really adding to my frustration, especially when i see its route rendered correctly...

In short, in both situations, the path is updated correctly (NOT_FOUND => /not-found, OOPS => /oops) but while NOT_FOUND correctly renders the NotFound component, OOPS renders the originally requested route's component.  The OOPS page correctly renders if i go directly there.

(I proved the above to myself by swapping 'OOPS' with NOT_FOUND)

Is there a way to treat custom routs the same as the NOT_FOUND route?

Thanks in advance!

**Comment by faceyspacey** [comment]
There's clearly something else adding to the equation. 

Are you server rendering? Are we talking about the page initially rendered by the server after a redirect or is this purely client side in an SPA?

If you are server-rendering, make sure that the `doesRedirect` stuff described here:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/server-rendering.md

is functioning correctly. 

----

If this is an SPA or if this is all happening on the client after initial load of the page, what states are you seeing in the redux devtools? 

You described components rendered or *not* as the primary indicator as to whether `OOPS` behaved correctly, however the most helpful indicator for us is what states you see in the redux devtools. 

Just dealing with states isolates the issue in terms of RFR and takes out of the equation any possible problems with components that are unrelated, and also may point you in the direction of other things that might be wrong, like with the reducers.


----

Does this `NOT_FOUND` code path work:

```js
const status = Math.floor(error.response.status / 100);
          console.log(status);
          if (status === 4) {
            dispatch(redirect({ type: NOT_FOUND }));
```
??

In which case it has to do with the promise aspect, and not `NOT_FOUND` vs `OOPS`.

----

In general, this shouldn't be happening and the best thing to do is to reduce it to the simplest case to be sure of what the root of the problem is. The demo redirects to another non-NOT_FOUND route correctly.  So you can be confident that RFR--at least in the average use case--works correctly. That means there is likely some missing piece to the equation hidden in there that's causing the problem.

**Comment by cake-jnorman** [comment]
James, thank you!

Let's see if i can answer your questions.  First, this is a client side SPA only - so no server side rendering to worry about.  

As far as redux states go, they are absolutely identical when triggering the 400 route and the 500 route (with the exception of the page/location data, as would be expected).  By 400 and 500 routes, i am referring to the code below:

```
try {
        const resp = await getData(state.location.query.id);
        dispatch(setData(resp.data));
      } catch (error) {
        const status = Math.floor(error.response.status / 100);
        if (status === 4) {
          console.log(4);
          return dispatch(redirect({ type: NOT_FOUND }));
        } else {
          console.log(5);
          return dispatch(redirect({ type: 'OOPS' }));
        }
      }
```

I also swapped out 'OOPS' with NOT_FOUND - at which point the 400 and 500 work identically, without issue.  they redirect to, and render the not-found view.

For grins, I converted the code over to use async / await so that it more closely matched the sample app.  No different there.  But something I DID notice is that the rendering order was not the same for the two paths (when 400 => NOT_FOUND, and 500 => 'OOPS'):

It is worth noting that i am using the excellent UniversalComponent.  I did some logging within it and in the components in question, and i did find the following to be interesting.

lets call my landing page 'start-page'.

For the NOT_FOUND path of events, the following happened:
UniversalComponent reported that it received a request to render 'start-page'
UniversalComponent reported that it received a request to render 'not-found'
**start-page's render was then called
not-found's render was then called**

Note that the desired page was rendered last - this is the good scenario.

For the OOPS path of events, the following happened:
UniversalComponent reported that it received a request to render 'start-page'
UniversalComponent reported that it received a request to render 'oops'
**oops' render was then called
start-page's render was then called**

Here, the oops page 'gets stepped on'.  

I'll continue to dig through everything.  I feel like the rendering order is the key here.  I do not understand why the final rendering order is different for the two paths.  there is nothing special about either of the components.  If any of this sheds light on the issue, well... one can wish.  Please let me know if any more info is needed.  As i mentioned, i'll continue working through this on my end.

Thanks again.

**Comment by faceyspacey** [comment]
Try making it work without universal component. Reduce everything to the absolute simplest case, while still containing what you hypothesize to be the problem. That's the only way to know for sure that is the problem. It just can't be the problem, as RFR is in wide use and people are able to redirect to other routes just fine. 

My guess something related to Universal may come to the surface. So if you want to isolate things in steps, first just remove Universal. Then proceed to removing everything unrelated to the experiment.

**Comment by cake-jnorman** [comment]
roger 👍

**Comment by cake-jnorman** [comment]
Good call! it is an issue within UniversalComponent.  I'll see if I can narrow down the issue and then open an issue over in that repo if it has not already been brought up.  Thank you for your time James!

**Comment by cake-jnorman** [comment]
James, It looks like you own UniversalComponent as well.  I need to get my current working solution delivered, but as soon as i do, i'll circle back around and see if i can figure out what was going on within the UC.  

Again, thank you.  I appreciate your quick responses.  It definitely strengthens my resolve in choosing RFR as our routing library.  Props for the great work.
