### ISSUE TITLE
some routes in <Link to={path}> throwing error

### ISSUE THREAD

**Issue by jameswillett** [faceyspacey/redux-first-router#263]
hello fellow james!

I'm having a weird issue i cant figure out. Some routes (when passed the string of the route) are giving me a "Cannot read property 'length' of undefined" error. the string passed in matches the path in the routesMap, and it only affects SOME routes; in the same `<Nav />` component i link to `/products` and `/sign-in`.. sign-in works while products dont. this issue is completely alleviated if i link to `{{ type: SOME_ROUTESMAP_ACTION }}` but id much rather use the paths when i dont need a payload (plus it will be easier for the design team to not have to worry about redux at all 😏). any help would be appreciated!

**Comment by faceyspacey** [comment]
It's really hard to tell without more information. This problem shouldn't be happening make sure you're using the `rudy` tag on NPM. do: `yarn upgrade redux-first-router@rudy redux-first-router-link@rudy`.

**Comment by jameswillett** [comment]
🎉updating totally fixed it. i didnt realize i was using v0.0.16
