### ISSUE TITLE
Dispatching action with multiple multi segments

### ISSUE THREAD

**Issue by TheoneLucas** [faceyspacey/redux-first-router#264]
Hi, I have the following route declaration: 

```
const routesMap = {
  SHOW_STORE:  { path: '/:domain/(f)?/:filters(.*)?' },
}
```

This declaration successfully allow me to access the route using any of these URL's:

localhost/foo
localhost/foo/f/something-123
localhost/foo/f/bar-123/baz-123

The problem is that: whenever I try to open this route in sagas, I'm redirected to NOT_FOUND. Here is how I'm doing it:

```
yield put({
  type: SHOW_STORE,
  payload: { domain: 'foo', 0: 'f', filters: 'foo-123/bar-123' },
});
```

I tried converting the route declaration from an object to a string, like so:

```
const routesMap = {
  SHOW_STORE:  '/:domain/(f)?/:filters(.*)?',
}
```

What makes me able to open the route in sagas using the same previous code, but my `:filters` parameter now is URL encoded, and my URL becomes:

`localhost/foo/f/foo-123%2Fbar-123`

But it should be:

`localhost/foo/f/foo-123/bar-123`

Thanks.

[EDIT]

After I tried a lot of random things, I managed to make it work using a backslash as the segments separator:

```
yield put({
  type: SHOW_STORE,
  payload: { domain: 'foo', 0: 'f', filters: 'foo-123\\bar-123' },
});
```

I don't know if this is what I was supposed to do as I didn't found any mentions to using a backslash in the documentation, so I hope to hear your opinions on this, thanks again.

**Comment by faceyspacey** [comment]
Check the different variants in the test cases here and let me know if that solves your problem:

https://github.com/faceyspacey/redux-first-router/blob/rudy-respond/__tests__/integration/params.js#L111-L240

Also, keep in mind, most the path matching is based on the `path-to-regexp` library:

https://github.com/pillarjs/path-to-regexp

So anything you can do there, you can do here.

**Comment by faceyspacey** [comment]
another note: named parameters are better than `0:`. You'll see in the above links how to do that.

As far as dealing with weird characters that can appear after conversions, in the next version we have a lower level API to do completely custom conversions. For now, if you can get it to work, i.e. with the 2 slashes, I wouldn't worry about it.

**Comment by TheoneLucas** [comment]
> Check the different variants in the test cases here and let me know if that solves your problem
> 
> https://github.com/faceyspacey/redux-first-router/blob/rudy-respond/__tests__/integration/params.js#L111-L240

Yes, these test cases seems to catch my examples, I just didn't see a case to match 
optionals MULTIPLE "multi segment params" as single param, maybe I missed something, but anyway.

> another note: named parameters are better than 0:. You'll see in the above links how to do that.

Thanks for the note, I did that, I named my "0" parameter to "f".

> 
As far as dealing with weird characters that can appear after conversions, in the next version we have a lower level API to do completely custom conversions. For now, if you can get it to work, i.e. with the 2 slashes, I wouldn't worry about it.

Ok, I will keep using double backslashes while waiting for the next release, looking foward  to it!
