### ISSUE TITLE
Initial state does not keep query

### ISSUE THREAD

**Issue by CNDW** [faceyspacey/redux-first-router#265]
Since the project appears to be fragmented, and I'm unsure of the actual state of things, I'm leaving this here. If I can get some guidance as to what branch is current I will make a pr.

I am using the rudy branch currently, it looks like the `initialAction` created inside of the `connectRoutes` function is not being given the querySerializer option, as a result any query params that exist on the initial route are not put into the redux store.

**Comment by CNDW** [comment]
This is happening browser side, on the rudy branch.

For some additional context; I have a password reset route that I am checking for the existence of a token query param in the `onBeforeChange` hook in the state, if the query param isn't there, I redirect to the login route. The route is directed to via an email link, so the route with the query param is the first thing when redux-first-router loads. The initial location state does not include the query params as I would expect. I traced the problem to line 167 in `connectRoutes.js`.
```
  const initialAction = pathToAction(currentPath, routesMap)
```
`pathToAction` doesn't process query params if a 3rd serializer argument is not given, the serializer just needs to be passed in.

If rudy is the correct branch I can make a PR, it's just really hard to tell what is going on with the project.

**Comment by faceyspacey** [comment]
Not sure how that got in there. May be a regression. Feel free to PR the rudy branch.

**Comment by ScriptedAlchemy** [comment]
Merged into the rudy branch on github. Working on a release
