### ISSUE TITLE
[QUESTION] Finding the right structure for my routes map

### ISSUE THREAD

**Issue by PhilippHandke** [faceyspacey/redux-first-router#266]
I am working on a project we'd love using RFR with. As I red a lot of posts (e.g #126) and looked through some nice examples, I am still confused about setting op the right route structure.

Lets say we are realising some kind of address book. There is a list of contacts, that can be filtered by the role a contact can have (e.g. Client, Customer, Staff etc.).  So the route mapping looks like:
```
CONTACT_LIST: '/contacts/:role(clients|customers|staff)*'
```

If I click on an entry in my list, the link is getting me to the detail page of the selected contact. My first try with this was to realise this with a new route for that detail view:
```
CONTACT_LIST: '/contacts/:role(clients|customers|staff)*',
CONTACT_DETAIL: '/contact/:id(\\d+)'
```

Now we have the requirement, that the contact detail page shows a link for getting me to my list of all contacts (like "Go to contact list"). If the user previously came from this list of clients, the link should redirect to this page with this filtering (Route: `/contacts/clients`). To do this right, the url for the contact detail page has to include this information. So the routes can always be generated in a proper way. So the contact detail page is a nested version of the contact list. I modified my route structure like this:
```
CONTACTS: '/contacts/:role(clients|customers|staff)*/:id(\\d+)'
```
Now both views can be accessed by this route using the right parameters. Using this structure, I run into multiple issues when my page gets more complex. So what if:

- There are more filter criteria on the contact list page (a general search-string or pagination params).
- The contact-detail-page contains even more functionality, like several tabs with specific information or modal views for editing the contact data, or a list view with additional data that also has search filters and a pagination.

If i continue with this, the route the mapping and the link generation becomes insanely complex, at lest for me 😰. Getting all my current or future criteria for the client pages to fit in one route definition does not seem to lead to a page that is good to maintain. Or would it be right to define more routes that still contain some kind of parameter string, other (parent)routes need for their representation?

What point am I missing? Thanks a lot!

**Comment by CNDW** [comment]
I would not have the `role` included as part of the url params, I would instead use query params to provide that data `/contacts?role=(clients|customers|staff)` The role is less of a routing concern, that work should be handled by whatever is providing the list

**Comment by faceyspacey** [comment]
as @CNDW mentioned, query parameters are best suited for complex criteria filtering/sorting. And for the exact reasons you mentioned where the number of configurations can skyrocket.

If you don't want long query strings, you can also use a reducer to track where the user came from and other recently selected options.
