### ISSUE TITLE
Browser beforeunload/unload/load events are not listened to

### ISSUE THREAD

**Issue by hedgepigdaniel** [faceyspacey/redux-first-router#267]
Currently when navigating using redux actions, the included history package, and the browser back/next buttons (when applied to transitions via redux), all the route callbacks are called in the order you would expect.

However, when non SPA transitions occur as a result of clicking on undecorated `<a />` links or similar, the routing actions behave differently:
 * Callbacks are not executed when the page is unloaded
 * If the next page is in the app (at least in `rudy`), the `onBeforeChange` callback is called *after* the page transition.

What would make more sense to me is something along the lines of the following:
 * The router listens to the `beforeUnload` browser event (for `confirmLeave` in `rudy` and `beforeLeave` in `rudy-respond`) and the `unload` browser event (for `onBeforeChange` in `rudy` and `beforeLeave` in `rudy-respond`).
 * On SPA transitions, everything works the way it does
 * On initial page loads, only the callbacks associated with the new route are called (`['onAfterChange', 'thunk']` for `rudy` or `['beforeEnter', 'onEnter', 'thunk', 'onComplete']` for `rudy-respond`)
 * When the page is unloaded, all the callbacks associated with the old route are called (`['onBeforeChange', 'confirmLeave']` for `rudy`, `['beforeLeave', 'onLeave']` for `rudy-respond`). The caveat is that you can't make the browser wait for a promise here - although you can block the navigation in `beforeUnload`. If the callbacks are given information about the situation (or if there are different callbacks for these situations) user code can handle this, e.g. by doing sendBeacon requests instead of XHR requests.

I think this would be more consistent, and would reduce the need for putting side effectful code in components or elsewhere for listening to these browser events. Most apps have some external links and many are not fully SPA capable, so handling non redux transitions is important.

I'd be happy to work on this if you're open to the idea.

**Comment by hedgepigdaniel** [comment]
Closing this because its a big new feature, unlikely to be addressed in RFR.

At some point I'll look at writing a middleware for rudy that can support this use case, and any core improvements that are needed.

**Comment by ScriptedAlchemy** [comment]
Mad love bro! I’m still working on ur reply. It’s busy busy. But I want to be clear and see what’s possible.
