### ISSUE TITLE
action to prevent transition from current route

### ISSUE THREAD

**Issue by agaurav** [faceyspacey/redux-first-router#27]
`action` for use of `history.block` api so that user can `lock` or `free` current route. 
Possible use cases are unsaved forms, pending results etc.

**Comment by faceyspacey** [comment]
we also need a function to provide for the confirmation prompt. It should be provided in the options. It can be called the same as in the history package, i.e: `getUserConfirmation`.

As far as the action, I think we could even just provide another function called something like `canLeave`. And we pass `state` and the latest `action`. And if `canLeave` returns false, `getUserConfirmation` prompt is displayed. 

So where do we put it?

Well, ideally we put it before the address bar changes and before the incorrect action is dispatched, i.e. before this:

https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L240

And before this is called:
https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L366

However, we don't have as much control on when the user presses the back/next button in the address bar. We also don't want the imperative approach of having to call `history.block`. So essentially we must call `canLeave` before the dispatch (and `_beforeRouteChange`). If it's false, we call `next` with the unchanged action.

However, if the user had pressed the back/next button, we need to use call `history.push` or `history.goBack` to reset the history to exactly what it was lol. That's the only way I can see without using `history.back`...actually here's another idea:

`shouldBlock` will be called when entering a route. I.e. in `_afterRouteChange`:

https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L243

And then we call `history.block` . And then in `canLeave`, if it returns true, we unblock.

**Comment by faceyspacey** [comment]
in Summary:

```js
connectRoutes(history, routesMap, {
   shouldBlock: (state, action) => boolean, // called after entering a route
   canLeave: (state, action) => boolean // called before leaving a blocked route; unblock if true
})
```

**Comment by faceyspacey** [comment]
so now that should be able to handle the case when the user presses the back/next browser buttons where we don't want our listeners called. 

However, in the regular case that the user dispatches action, we must simply detect `canLeave() === false` and pass the action on in the middleware.

**Comment by agaurav** [comment]
Yes, I think this approach covers all the possible scenarios. I guess we can simplify the config option by having specific redux `action` take care of the `shouldBlock` & `canLeave`, as only way the user will able to transition a state will be via an action itself. So why not let the router do it for him.

e.g. usage 
- action: `REACT_ROUTE_LOCK` => router calls history.block (if not already blocked), can have an optional `message` payload, used for confirmation message if a custom `getUserConfirmation` is not provided.
- action: `REACT_ROUTE_UNLOCK` => calls unblock

This also protects router from being passed `shouldBlock,canLeave` selectors which are not safe (i.e. blocking, memory-leaks etc.)

**Comment by faceyspacey** [comment]
Obviously that's a rough sketch. But the idea is the user never does anything but dispatch to THANK_YOU. If there's an error, he'll be redirected back. That's not exactly correct, but that part doesn't matter. Perhaps it shows possible complexities. What matters is that simply when he returns to the page he'll be blocked again until the payment succeeds.

**Comment by faceyspacey** [comment]
What the actions has going for it is that it's essentially a lower level API, which means if we miss any edge cases there's less work we gotta do on redux-first-router in the future to support those edge cases.

However, that said, if ur using Redux correctly, everything is supposed to be state driven. So that means everything u need to make decisions should be in state, which you can access in the 2 callbacks.

**Comment by agaurav** [comment]
There might be few issues with scaling in the selector based approach

- In case of multiple forms, logic for `shouldBlock` selector wound need to handle all possible cases e.g. 
``` javascript
shouldBlock: (state, action) => {
       if (state.location.type === 'PAYMENT' && state.payment.formDirty)
             return true;
       }
       if (state.location.type === 'settings' && state.settings.formDirty)
             return true;
       }

// ... so on
```

- app or parent component can't forcefully unblock if the route blocking component or something else fails.

Also as said in your last comment, it forces the application to necessarily sync everything to main redux state

**Comment by faceyspacey** [comment]
All cases is fine. It's just like a reducer. And forcing you to use redux state is a good pattern. It's what this package is all about. I'm fine with that. If you really needed, you could get around it with your own ad hoc global store.

**Comment by agaurav** [comment]
Ok, I guess that covers everything.
I will create a PR accordingly.

**Comment by faceyspacey** [comment]
Have you used the package yet? What do you think? I noticed you were using RLR and wanted this feature. So it only really makes sense if you're now using RFR.

Anyway, let me know if you need help. It can be tricky to put this stuff in the right places. If you get the first draft of the basic functionality, I can help with the rest.

**Comment by agaurav** [comment]
I haven't been able to actually use it but idea looks solid. Unlike RLR, it lets me use my own `history` instance, one can implement blocking or any other similar feature on his own. 

I am not sure about using route name as actions & creating reducers based on these action; unlike using RLR approach of using a single action for transition & single substate for storing params etc. Again for large apps it adds the overhead of maintaining too many reducers with the routes.

Currently, I am saving my form state in redux (along with syncing it to `localStorage` in a `saga` ), If a route is changed with unsaved changes I show a toast with link to unsaved form. This way form values are preserved even across page reloads.
I will use this router in future projects.

**Comment by agaurav** [comment]
Thanks, I will be needing your help writing the tests :).

**Comment by faceyspacey** [comment]
Typically, you have one primary page reducer that does most the work:

```js
const components = {
  HOME: 'Home',
  LIST: 'List',
  VIDEO: 'Video',
  [NOT_FOUND]: 'NotFound'
}

export const page = (state = 'HOME', action = {}) =>
  components[action.type] || state
```

So what ultimately happens is the same reducers you currently have simply listen for route-change action types. 

It's less reducers than you imagine. It's the same reducers listening to *fewer* actions. Instead of many ad-hoc actions, you have a smaller number of route-change actions. To compensate, what typically happens is your reducers do more tear-down work when the realize they are leaving a page. So you have less actions, and more work (in your reducers) in response to each action. "Thin actions" and "fat reducers," but not more.

If you haven't read the release article, it explains a lot of the logic behind this approach:
https://medium.com/faceyspacey/pre-release-redux-first-router-a-step-beyond-redux-little-router-cd2716576aea

**Comment by faceyspacey** [comment]
Hey brother you get a chance to work on this? I'll probably be getting to it this weekend if you haven't.

**Comment by agaurav** [comment]
I was planning to do the same this weekend (Sorry, was just able to go through the code last weekend because of some other priorities). 
I think I will be able to get a working PR by sunday.

**Comment by faceyspacey** [comment]
Awesome brother. Thanks!

**Comment by faceyspacey** [comment]
I actually never got a chance to get to this myself. Any luck/time on your side?

**Comment by ingro** [comment]
Hello! I'm very interested in getting this to work, do you plan to implement it? Otherwise I can try to put up a PR but i'm not very familiar with the internals of this kind of things unfortunately :/

**Comment by faceyspacey** [comment]
How well do you know the `history` package? Basically I explain my first thoughts on how to do it above. A PR would be much appreciated. I can help. How much time do you have to devote to it?

I think I'm really finally getting around to do it this week FYI.

**Comment by ingro** [comment]
I've used `history` package mainly with methods exposed by `react-router`, not much directly... I guess I should just use the **block** method but my real concers are where to integrate it in your library's code. I don't have much time this week, I could try to take a stab the next one if you haven't already!

**Comment by faceyspacey** [comment]
This is done. It's in the @next dist-tag on npm. to get it do:

```
yarn upgrade redux-first-router@next
```

Here's how you use it:

```js
const routesMap = {
   HOME: '/'
   FOO: {
      path: '/foo',
      confirmLeave: (state, action) => {
         if (action.type === 'HOME' && !state.formComplete) {
             return 'Are you sure you want to leave without completing your purchase?'
         }
     }
  }
}
```

So each route can have a `confirmLeave` option, and if you return a string it will be shown in the `confirm` yes|no dialog. If you return a falsy value such as undefined, the user will be able to navigate away from the current route without being shown any dialog.

If you'd like to customize that dialog (which is required in React Native since there is no `window.confirm` in React Native), you can pass a `displayConfirmLeave` option to `connectRoutes` like so:

```js
const options = {
  displayConfirmLeave: (message, callback) => {
    showModalConfirmationUI({
       message,
       stay: () => callback(false),
       leave: () => callback(true)
    })
  }
}

connectRoutes(history, routesMap, options)
```
> so `showModalConfirmationUI` is an example of a function you can make to display a confirmation modal. If the user presses **OK** call the `callback` with `true` to proceed with navigating to the the route the user was going to. And pass `false` to block the user. 

One special thing to note is that if you define this function in the same scope that is likely created below, you can use `store.dispatch` to trigger showing the modal instead. You could even do:

```js
store.dispatch({ type: 'SHOW_BLOCK_NAVIGATION_MODAL', payload: { callback } })
```

and then grab the callback in your `<Modal />` component. Since this is happening solely on the client and the store will never need to serialize that `callback` (as you do when rehydrating from the server), this is a fine pattern. Redux store state can contain functions, components, etc, if you choose. The result in this case is something highly idiomatic when it comes to how you render the React component corresponding to the modal. *No imperative tricks required.*

Here's a final example:

*src/reducers/blockNavigation.js:*

```js
export default (state = {}, action = {}) => {
  switch (type): {
    case 'SHOW_BLOCK_NAVIGATION_MODAL':
       const { message, callback: canLeave } = action.payload
       return { message, canLeave  }
    case 'HIDE_BLOCK_NAVIGATION_MODEL':
       return {}
    default:
       return state
  }
}
```

*src/components/BlockModal:*

```js
const BlockModal = ({ show, message, cancel, ok }) =>
  !show 
    ? null
    : <div className={styles.modal}>
        <h1>{message}</h1>

        <div className={styles.modalFooter}>
               <span onClick={cancel}>CANCEL</span>
               <span onClick{ok}>OK</span>
        </div>
   </div>

const mapState = ({ blockNavigation: { message, canLeave } }) => ({
   show: !!message,
   message,
   cancel: () => canLeave(false),
   ok: () => canLeave(true)
})

export default connect(mapState)(BlockModal)
```
> obviously you could wrap `<BlockModal />` in a [transition-group](https://github.com/faceyspacey/transition-group) to create a nice fadeIn/Out animation


*src/configureStore.js:*
```js
const options = {
  displayConfirmLeave: (message, callback) => {
     store.dispatch({ 
       type: 'SHOW_BLOCK_NAVIGATION_MODAL',
       payload: { message, callback } 
     })
  }
}

const { reducer, middleware, enhancer } = connectRoutes(history, routesMap, options)

const rootReducer = combineReducers({ ...reducers, location: reducer })
const middlewares = applyMiddleware(middleware)
const enhancers = composeEnhancers(enhancer, middlewares)
const store = createStore(rootReducer, preLoadedState, enhancers)
```

**Comment by ingro** [comment]
Woah thanks for the writeup, I will try it asap!

**Comment by pksjce** [comment]
Hey @faceyspacey - Would love to get this feature in a release! Whats stopping the next release? Could you use my help to get it there?

**Comment by faceyspacey** [comment]
when rudy 0.0.1 is out we'll need a few long-time users to migrate their codebases, so we can iron out kinks as fast as possible :)

Other things we need:
- typescript definitions
- website!
- demos (**TodoMVC demo**, **blog demo**, obvservables demo, sagas demo)

ps. almost almost there

**Comment by razorf80** [comment]
Hello, I've tried the confirmLeave and it works nicely. 

However there are some cases where the confirmLeave function doesn't get triggered. For example for the below routeMap. When you're on the FOO route and say there is a link to BAR route, the confirmLeave function do get triggered. And say you press OK, now you're in BAR route. Now when you press the browser back button to go back to the FOO route and change again the BAR route, the confirmLeave function doesn't get triggered. 

Would it be possible to trigger the confirmLeave function as well when the route is changed using the browser back?

```
const routesMap = {
   HOME: '/',
   FOO: {
      path: '/foo',
      confirmLeave: (state, action) => {
         return 'Are you sure you want to leave without completing your purchase?'
      }
   },
   BAR:'/bar',
}
```

Thanks in advance.

**Comment by raRaRa** [comment]
When the confirmation message is displayed, the page scrolls to the top. Is there a way to stop that from happening?

Thanks.

**Comment by ScriptedAlchemy** [comment]
@raRaRa https://github.com/faceyspacey?utf8=%E2%9C%93&tab=repositories&q=scroll&type=&language=

Might need an update though, haven't used it in a while.. leemme know
