### ISSUE TITLE
How to add conditional route parameters?

### ISSUE THREAD

**Issue by goulashsoup** [faceyspacey/redux-first-router#274]
Let's say  i have a route map:

    PAGE_MANAGEMENT_CONTACT_TAGS: {
        path: '/management/contact-tags/...',
        thunk: (dispatch) => {
            dispatch(fetchTagListIfNeededAction());
        }
    },

Now i want the path to have either one or two parameters:

1. action (`:action(new|edit)`), allways provided
2. id (`:id(\\d+)`), only provided if `action == 'edit'`

I first looked out for `path-to-regexp` but to my understanding nested slashed routes (e.g. `.../:action(new|edit/:id(\\d+))`) are not possible.

So is there a way to do that?

**Comment by hedgepigdaniel** [comment]
Why not two separate route action types, one for the edit action (with id), and another for other actions? You have reducers and selectors at your disposal to resolve these two different types of URLs into the appropriate app state.

**Comment by goulashsoup** [comment]
@hedgepigdaniel I was just curious to know if there is a way to do that with one route...

**Comment by ScriptedAlchemy** [comment]
If you find a solution PR our documentation
