### ISSUE TITLE
Refreshing homepage doesn't call thunk after initial load 

### ISSUE THREAD

**Issue by connorsmallman** [faceyspacey/redux-first-router#276]
If a user clicks on a Link that points to the current route the thunk is not called. This only happens until the user navigates away from the current route, after that an action with the same type as current route calls the thunk again. 

I believe this happens because the location reducer doesn't update the `kind` when pathname is the same. The `attemptCallRouteThunk` function takes the `kind` from the state (still set to load) and not the action (set to push).

https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/attemptCallRouteThunk.js#L21

https://github.com/faceyspacey/redux-first-router/blob/master/src/reducer/createLocationReducer.js#L20

**Comment by hedgepigdaniel** [comment]
That sounds like a legit bug to me. @ScriptedAlchemy should we consider accepting a PR to the `rudy` branch?

**Comment by ScriptedAlchemy** [comment]
Yeah, ill accept a PR for this.

@hedgepigdaniel ill also do a upstream merge back into the fork

**Comment by ScriptedAlchemy** [comment]
@connorsmallman if you can patch this, I have just opened a pull request for the next release of RFR

**Comment by connorsmallman** [comment]
@ScriptedAlchemy I'll try and get this done today, if not me one of my colleagues will.

**Comment by hedgepigdaniel** [comment]
Fixed in https://github.com/faceyspacey/redux-first-router/pull/288
