### ISSUE TITLE
Add query params to current url

### ISSUE THREAD

**Issue by borovik96** [faceyspacey/redux-first-router#278]
I want to add query param to current url, I don't know what current url is. 

For example I have `/token/ETH` or `/user/user1` urls and want to change they to `/token/ETH?m=ref` or `/user/user1?m=ref` accordingly. 

Is it possible to define an action only for updating query in URL? 

Will appreciate any help

**Comment by hedgepigdaniel** [comment]
The current route action is available in the `location` reducer, so its quite simple to write a thunk which copies the current route action, changes some part of it, and dispatches it.

**Comment by borovik96** [comment]
Thanks, will try to do it

**Comment by srinivasdamam** [comment]
@hedgepigdaniel @faceyspacey 
First of all Sorry for writing on a closed thread.

When I just want to change the query of the current route, why should my component be subscribed to the current route or the need to add a custom thunk to handle it ?

I guess the library expose action creator to modify the query or payload without changing the route.

Happy to correct if I'm wrong or I missed something.

**Comment by hedgepigdaniel** [comment]
I don't think there is a function in the library, but its quite simple to write one, since the current route is in the store

```javascript
const { type, payload, params } = getState().location;
dispatch({
  type,
  payload,
  {
    ...query,
    changed: 'value',
  },
});
```

**Comment by wasinsandiego** [comment]
I know it's closed but closed issues are still useful when people are looking for solutions,  right? In case it's useful for someone else...

This is my higher order component (using recompose and connect) that adds a function prop named `queryUpdate` to any component that will dispatch an action to update the query without a route change. You could modify to create a react hook or a HOC without recompose.

```javascript
import { connect } from 'react-redux'
import { compose, withHandlers } from 'recompose'
// my selectors to get things from location slice
import {
  locationTypeSelector,
  locationPayloadSelector,
  locationQuerySelector
} from 'routes.selectors'

export const updateQuery = ({ type, payload, query }) => ({
  type, payload, query
})

const mapStateToProps = state => ({
  locationType: locationTypeSelector(state),
  locationPayload: locationPayloadSelector(state),
  locationQuery: locationQuerySelector(state)
})

const mapDispatchToProps = {
  updateQuery
}

export const withQueryUpdate = compose(
  connect(mapStateToProps, mapDispatchToProps),
  withHandlers({
    queryUpdate: ({ updateQuery, locationType, locationPayload, locationQuery }) => ({ query }) => {
      updateQuery({
        type: locationType,
        payload: locationPayload,
        query: { ...locationQuery, ...query }
      })
    }
  })
)
```
