### ISSUE TITLE
Allow slashes in route parameter

### ISSUE THREAD

**Issue by goulashsoup** [faceyspacey/redux-first-router#279]
I have a path in which i want to allow slashes for the only parameter:

`'/management/contract/assured-roles/edit/:abbrev(.*)'`

The route works when i test it in the [express-route-tester](http://forbeslindesay.github.io/express-route-tester/) but not in the application, redux-first-router reports that it can't create a path from action with `abbrev`: `"L/DO"`.

How can i allow slashes?

**Comment by ScriptedAlchemy** [comment]
might wanna try the `@next` tag on npm, its got better route parsing

**Comment by hedgepigdaniel** [comment]
```javascript
EDIT_ROLES: {
  path: '/management/contract/assured-roles/edit/:abbrev*',
}
```

should do it

**Comment by goulashsoup** [comment]
@hedgepigdaniel Thank you, your answer seems to work.
