### ISSUE TITLE
Unable to use dispatch action to redux-observable epic

### ISSUE THREAD

**Issue by rgupta2** [faceyspacey/redux-first-router#282]
This is more of a [usage issue](https://stackoverflow.com/questions/52197728/defining-action-for-redux-first-router) but posting it here just to be sure that I am using redux-first-router correctly.

My project is written in typescript and uses redux-observable alongwith FSA style actions.

While integrating redux-first-router, I am dispatching an existing action `fetchPage.started` in onPageChange. The action does gets dispatched and reaches the reducer but not to the epic. I am unable to figure out the missing piece. Could you be of help here?

Is action dispatched from `onPageChange` supposed to follow certain guidelines? 

```
const { reducer: routeReducer, middleware: routeMiddleware, enhancer: routeEnhancer } = connectRoutes(
  history,
  routesMap,
  {
    querySerializer: queryString,
    onAfterChange: (dispatch: Dispatch<any>, getState: StateGetter<any>) => {
      const state = getState();      
      const query = state.location && state.location.query && state.location.query.search;
      
      dispatch(fetchPage.started({index: 0,
        pageSize: 10,
        sort: [],
        query }));
    }
  }
);

```

**Comment by hedgepigdaniel** [comment]
Just taking a guess - is the redux-observable middleware/enhancer before or after the rfr middleware? If its before, maybe its too late for redux-observable to ...observe... it?

**Comment by ScriptedAlchemy** [comment]
based on how james built this, id say that @hedgepigdaniel is correct. 

We build the plane "as it flies", in this case, the plane is already taking off once you try to add something onto it. Needs to be before
