### ISSUE TITLE
canGoBack: "TypeError: _history.entries is undefined"

### ISSUE THREAD

**Issue by kyle-johnson** [faceyspacey/redux-first-router#285]
As noted in #238, `canGoBack` fails client side on 0.0.16-next (my use case is once the user visits a new URL, they click a button which tries `canGoBack` before calling `back`).

I get: "TypeError: _history.entries is undefined"

My workaround is to go look up `location` in redux and then call `back()` if a previous URL existed (this works).

**Comment by ScriptedAlchemy** [comment]
Fixed and will be released in the next version. PR currently open
