### ISSUE TITLE
Inconsistency in API for connectRoutes in readme and typescript definition vs. actual code

### ISSUE THREAD

**Issue by mungojam** [faceyspacey/redux-first-router#300]
I upgraded to 2.0.1 and started changing my code to use the history package as shown in the readme and what seemed to show up in auto-complete in VS Code. However, my routing broke completely, and I believe it is because the code still just expects routes and options to the function call:

https://github.com/faceyspacey/redux-first-router/blob/f1d3835a455377ce4e4317f359979eb08fe848da/src/connectRoutes.js#L94

**Comment by ScriptedAlchemy** [comment]
Have a look at the new demo that was also released. 

To be honest, i didn't work on this release and am trying to get up to speed on it.

Ill take a look at the demo  and try to spot any outdated areas, however if you are working on an upgrade at the moment and figure something out. Feel free to PR it

Alternative, my work has been mostly around Rudy, which is getting its own repo and npm tag this week (beta release) 

I know its not ideal, but this part was before my time with faceyspacey

**Comment by ScriptedAlchemy** [comment]
I also have never used TS, so they could very well be outdated. I can remove them or leave it as is and wait for someone who cares enough to fix it

**Comment by mungojam** [comment]
I really appreciate you picking this up and good luck with getting it all in shape, looking good so far. 

I think the ts may actually be some automatic VS Code feature, maybe it just didn't update.

Meanwhile it seems like the readme is out of date maybe. Am I right to think that the dependency on history is the old way and the new way is an internal history feature? I could submit a PR to reflect that if you think that might be the case

**Comment by ScriptedAlchemy** [comment]
Yeah i think history might be outdated. 

From what i know about Rudy, we built our own history api - so its likely we use it in this version of RFR too. 

Please, feel free to PR as much as you want - if are updating your projects it would be fantastic to note down and PR the "right" way 

Once i release Rudy, as a thank you, Ill personally help you upgrade your project if you wish.

**Comment by ScriptedAlchemy** [comment]
Right now, Im maintaining RFR, Rudy, Universal (and all its packages), Webpackery, Icarus, and React Static - its definitely a balancing act and sure would appreciate any help i can get on the documentation side

**Comment by mungojam** [comment]
Great work! Thanks for all your contributions :+1:  I'll do what I can to help but it will probably be just bits and pieces if I come across them

**Comment by ScriptedAlchemy** [comment]
Thats totally fine! Every bit helps - you are the first to migrate a project, so it will be very helpful to others who start. 

For Rudy, ill be documenting the migration as well as releasing Icarus which is an enterprise boilerplate for Universal and Rudy together. Its what I use personally. 

follow me on twitter - ill post updates to Rudys progress (it done, just needs one last feature and some docs)

**Comment by hedgepigdaniel** [comment]
@mungojam does your PR fix the issue and 2.0.1 works after adjusting your code to account for history being handled internally by `redux-first-router`?

**Comment by mungojam** [comment]
Yeah, I think the typescript thing was just VS code playing up
