### ISSUE TITLE
Usage with redux-saga

### ISSUE THREAD

**Issue by KaRkY** [faceyspacey/redux-first-router#31]
Hello,

would it be possible to delay action that is dispatched on initial load? I am using redux saga and the initial action is happening before sagas are started. It would be nice if connectRoutes would return a function or something similar so I can call it after sagas are started.

**Comment by faceyspacey** [comment]
Try putting this middleware first and let me know how it goes. Someone else has success with that.

**Comment by KaRkY** [comment]
Sorry will not work because sagas start after store is created. If you look at the code below you will see that sagas start listening at the line: sagaMiddleware.run(rootSaga);
```
const history = createHistory();
  const { reducer, middleware, enhancer } = connectRoutes(history, routes);
  const sagaMiddleware = createSagaMiddleware();
  const middlewares = [];

  middlewares.push(middleware);
  middlewares.push(sagaMiddleware);

  if (process.env.NODE_ENV !== "production") {
    middlewares.push(createLogger({
      collapsed: true,
      diff: true
    }));
  }

  const store = createStore(
    combineReducers({
      location: reducer,
      ...storeReducer
    }),
    composeEnhancers(
      enhancer,
      applyMiddleware(...middlewares),
    ));

  sagaMiddleware.run(rootSaga);
```

**Comment by faceyspacey** [comment]
and are you using SSR?

**Comment by KaRkY** [comment]
No I am not.

**Comment by KaRkY** [comment]
There is an issue on the redux-saga repo about this but it is probably not a priority.

https://github.com/redux-saga/redux-saga/issues/736

**Comment by faceyspacey** [comment]
scroll to the bottom here:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/connectRoutes.md#options
look for `initialDispatch` option.

**Comment by faceyspacey** [comment]
when the package updates, update your dependency:

https://www.npmjs.com/package/redux-first-router

I've been meaning to add this feature for this precise use-case.

**Comment by faceyspacey** [comment]
travis should automatically publish in 1-3 minutes.

**Comment by KaRkY** [comment]
Ok I tried it and it does not work maybe I am doing something wrong. 
This is my setup code:
```
const history = createHistory();
  const { reducer, middleware, enhancer, initialDispatch } = connectRoutes(history, routes, {
    initialDispatch: false
  });
  const sagaMiddleware = createSagaMiddleware();
  const middlewares = [];

  middlewares.push(middleware);
  middlewares.push(sagaMiddleware);

  if (process.env.NODE_ENV !== "production") {
    middlewares.push(createLogger({
      collapsed: true,
      diff: true
    }));
  }

  const store = createStore(
    combineReducers({
      location: reducer,
      ...storeReducer
    }),
    composeEnhancers(
      enhancer,
      applyMiddleware(...middlewares),
    ));

  sagaMiddleware.run(rootSaga);
  initialDispatch();
```

I tried to debug why it is not working and only found that initialDispatch function is empty.

**Comment by faceyspacey** [comment]
and this is running completely in the client? if there is a server, this stuff only runs on the server. When it gets rehydrated on the client, no dispatches happen ever.

**Comment by faceyspacey** [comment]
what your state for `getState().location.hasSSR` ?

**Comment by faceyspacey** [comment]
found the issuing. publishing..

**Comment by KaRkY** [comment]
hasSSR is undefined. I was able to debug that this part of your code is actualy getting called:

```
initialDispatch = () => {
        const action = historyCreateAction(
          currentPathname,
          routesMap,
          prevLocation,
          history,
          'load'
        )
```

**Comment by faceyspacey** [comment]
you mean *NOT* getting called?

**Comment by KaRkY** [comment]
No I mean it is getting called but the function reference does not change. I am not primary JS developer so I do not know all JS quirks maybe I am doing something wrong.

**Comment by faceyspacey** [comment]
ok. 1-3 minutes and upgrade. this time it will work.

**Comment by faceyspacey** [comment]
published

**Comment by KaRkY** [comment]
Ok now it works thanks for the quick job.

I must say I realy like this project it is exactly like I would build a router.

**Comment by faceyspacey** [comment]
glad u like it. let me know any time u need something. ...a big SSR + Code Splitting demo coming out today or tomorrow. Keep a lookout.

**Comment by wilbert-abreu** [comment]
@faceyspacey Great work with this. The example you posted does not include sagas: https://github.com/faceyspacey/redux-first-router-demo
Is there another example with sagas? Thanks!

**Comment by faceyspacey** [comment]
Not yet. @KaRkY would you be interested in posting a demo of using RFR with Sagas to https://codesandbox.io ??

**Comment by KaRkY** [comment]
Yeah I can try to put something simple up.

**Comment by KaRkY** [comment]
Here is first extremely simple example. I just ripped out relevant code from my personal project. Will try to pretty up the example today or tomorrow when I will have more time.

https://codesandbox.io/s/n5QZAVQ05

**Comment by faceyspacey** [comment]
Excellent, you're the best!
