### ISSUE TITLE
Trailing slash in pathname

### ISSUE THREAD

**Issue by cdoublev** [faceyspacey/redux-first-router#312]
A route `/foo/` is currently matching an url `/foo` and vice-versa. I suppose that this behavior comes from `path-to-regexp` and that it will not be changed as FaceySpacey indicated in https://github.com/faceyspacey/redux-first-router/issues/63. But:

> http://example.com/foo/ (with trailing slash, conventionally a directory)
> http://example.com/foo (without trailing slash, conventionally a file)
>
> Google treats each URL above separately (and equally) regardless of whether it’s a file or a directory, or it contains a trailing slash or it doesn’t contain a trailing slash.

https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

It obviously has serious SEO implications. Wouldn't be usefull to add something about that in the readme, ie. test `/foo === location.pathname || redirect({ type: '/foo/' })`, if it would not be handled in RFR?

**Comment by cdoublev** [comment]
It would probably boil down to pass a `strict` option to `pathToAction` and use it as the second argument for calling `compilePath` [here](https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/pathToAction.js#L35).

**Comment by ScriptedAlchemy** [comment]
Open a PR with your suggestion - if you can Mock up a small unit test for it. Ill also apply the same thing to Rudy
