### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by rebyul** [faceyspacey/redux-first-router#313]
Hey I love your project, beginning to learn React and the controlled state management ecosystem.
I have chosen to go with typescript over flow for my project, so I was wondering if there will be typing support for v2+ anytime soon?
I tried to use the v1 compatible @types/react-first-router project (https://www.npmjs.com/package/@types/redux-first-router) which broke at the connectRoutes call (seems history is not injected anymore) and fails silently (javascript things).

Currently I have the configureStore function (as shown in the documentation examples) written in plain javascript and being called from the typescript code.

So is there any plans to creating typings for the project?
Thanks in advance :)

**Comment by ScriptedAlchemy** [comment]
Thrilled you like the project. Check out Rudy -  Its the successor of RFR.

Docs are still really old, from RFR2 era (RFR 2 is a year old version of Rudy), but check out the under the hood code of Rudy :) Id does far more and is one feature short of a release  

Hey,  theres another issue open somewhere. But those typings were publicly submitted. I've never written TS before and didnt even know these typing existed till last week.

Sadly this is one I cant fix myself

**Comment by rebyul** [comment]
Ah i see, thanks so much for working with @faceyspacey on this great project, hope the concept of RFR becomes more widely adopted!

Keep up the beautiful work :)
