### ISSUE TITLE
redux-first-history -> one way in react-router and @reach/router

### ISSUE THREAD

**Issue by salvoravida** [faceyspacey/redux-first-router#317]
redux-first-history -> one way in react-router and @reach/router

https://github.com/salvoravida/redux-first-history

Maybe it could be usefull to users that need only one source of truth.

I look forward to receiving your feedback.
Regards.

**Comment by kyle-johnson** [comment]
What's the shape of the store redux-first-history creates?

**Comment by ScriptedAlchemy** [comment]
Interesting. I wonder how it would fit into RFR. Our next iteration enables us to do complex things like mutate the browser history and synchronized either way
