### ISSUE TITLE
Broken links in FAQ

### ISSUE THREAD

**Issue by ixje** [faceyspacey/redux-first-router#32]
The links under the question **Does this work with React Native?** are not valid. I think they probably have to point to `.../docs/react-native.md` instead of `.../docs/react-navigation` but I'm not sure (which is why I didn't create any pull request).

ps: and thanks for being elaborate in your FAQ answers. It's really helpful for us less experienced developers 👍 . Looking forward to your big end-of-june update to see if this package might help me overcome some of react-navigation's routing difficulties I'm experiencing.

**Comment by faceyspacey** [comment]
Workin on it. Got something comin out later today.

Would u mind making a pr to fix that? If ur new to PRs, readme changes are the perfect place to start 🚀

**Comment by ixje** [comment]
Great.

I'm going to assume you requesting me to PR means my guess for the new URLs is correct. I've submitted a PR accordingly (#33)

**Comment by faceyspacey** [comment]
perfect job with the #hash. thanks!

**Comment by ixje** [comment]
yw
