### ISSUE TITLE
Optimizing API calls in the route configuration

### ISSUE THREAD

**Issue by NavnathKumbhar** [faceyspacey/redux-first-router#322]
Hello,
I know this is not a forum but I did not find the same for my problem regarding **redux-first-router.**
I am using redux-first-router and its pretty well fulfilling my needs.

In route configuration, I have three routes:
1. HOME: /
2. VIEW: /:projectName/:view
3. ELEMENT: /:projectName/:view/:elementId

I performed required api calls under the thunk of each route. 
Each view has list of elements. I do some activity when I click on element.
So basically, when I use/click element, I call the ELEMENT route, otherwise I call VIEW route.

When I hit the URL http://localhost:port/projectname/viewname/elementId, it goes to ELEMENT route and calls required api calls.

Also when I select any element in the view, it should go to the ELEMENT route which again calls all the api calls unnecessarily.  Off course I can add some filter there to save these api calls when I click on element. But I don't think it is a good idea (perhaps). 

I hope you understood my problem here.
Could you please suggest some better "redux-first-router way" or any other good way for this situation?

Thank you in advance!
Navnath

**Comment by hedgepigdaniel** [comment]
You can write your own code to determine whether or not its necessary to do the API call again:

```javascript
{
  ELEMENT: {
    path: '/:projectName/:view/:elementId',
    thunk: (dispatch, getState, bag) => {
      const state = getState();
      // Check the current redux state to see if we have the data about the element we are currently viewing (`state.location.payload.elementId`)
      if (!selectHasFetchedCurrentlyViewingElement(state)) {
        // If not, fetch it.
        dispatch(fetchCurrentlyViewingElement();
      }
    },
  },
}
```

It's hard for redux-first-router to know which of your thunks should or should not be repeated on each visit to each route. The best way IMO is for your app to contain that logic.

**Comment by ScriptedAlchemy** [comment]
Agreed. Computer science hardest thing...  cache invalidation 

In Rudy, we do have a basic thunk cache though!! So we have thought about this
