### ISSUE TITLE
Prevent navigation back into the login screen

### ISSUE THREAD

**Issue by Rafi993** [faceyspacey/redux-first-router#323]
I wanted to prevent users from navigating back to login screen using back button once they are re-directed into home screen after login. I couldn't find a way to solve this. How should I proceed ?

**Comment by Rafi993** [comment]
I tried this https://github.com/faceyspacey/redux-first-router/blob/master/docs/blocking-navigation.md but I don't want alert to be shown but just to block user from navigation

**Comment by hedgepigdaniel** [comment]
I suggest to read those docs you linked more carefully - I think `displayConfirmLeave` can do what you want. The modal is just the default behaviour.

**Comment by ScriptedAlchemy** [comment]
Do we need updated docs, or can I choose this

**Comment by Rafi993** [comment]
Sorry I didn't figure out this first. I am closing this issue

**Comment by ScriptedAlchemy** [comment]
I know there was another issue like this. Check or closed issues. They might help
