### ISSUE TITLE
Correct version of redux-first-router-link ?

### ISSUE THREAD

**Issue by magnusjt** [faceyspacey/redux-first-router#327]
npm install redux-first-router-link installs version 1.4.2, but it seems to me that the version that works with the current version of redux-first-router is redux-first-router-link#0.0.3-rudy. At least basename only works with that version. 

Am I correct in using redux-first-router-link#0.0.3-rudy ?

**Comment by klis87** [comment]
Maybe `redux-first-router-link` version 1 could be released like `redux-first-router` was, as still there must be a big confusion among developers, especially for ones just discovering this repo, or maybe link could be included in `redux-first-router` itself if thats easier.

**Comment by magnusjt** [comment]
Since redux-first-router and redux-first-router-link are so tightly bound it seems like a good solution to have them in the same repo, though there may be some other reason to separate them that I'm not aware of.

**Comment by klis87** [comment]
The only one I could think of is that `redux-first-router` is univeral, and `redux-first-router-link` is bound to react

**Comment by ScriptedAlchemy** [comment]
Was just updated today
