### ISSUE TITLE
Payload value should be picked from store if not provided

### ISSUE THREAD

**Issue by villesau** [faceyspacey/redux-first-router#336]
Would be usability wise very good if all the link actions could be filled without payload, or with only partial payload. you might have eg. `/:userId/routes/:whatever`. where userId does not change at least within context, but is still dynamic. it's cumbersome that the value needs to be picked from redux every time you want to navigate in the sub route.

**Comment by cdoublev** [comment]
I think it would be implemented in Respond Rudy. See https://github.com/respond-framework/rudy/issues/3.

**Comment by villesau** [comment]
what's that?

**Comment by ScriptedAlchemy** [comment]
RFR is just the core of Rudy. 40 files vs 400. 

James rewrote RFR and I am in the process of trying to wrap up its last feature
