### ISSUE TITLE
trouble using redux-first-router in combineReducers?

### ISSUE THREAD

**Issue by sashahilton00** [faceyspacey/redux-first-router#343]
Apologies if this has been answered before, but from a few minutes searching I've not found the same issue.

I'm trying to integrate redux-first-router into a project with react-saga enabled, though I am consistently hitting the following error:

```
Error: [redux-first-router] you must provide the key of the location reducer state and properly assigned the location reducer to that key.
```
The code in my index.js used for configuring the store is as follows, taken from the minimal example mostly:
```
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose

//Routes
const routesMap = {
  HOME: '/',
  CUSTOMER: '/customers/:id',
  CUSTOMERS: '/customers'
}


const history = createHistory()
const router = connectRoutes(history, routesMap, {
  initialDispatch: false
})
const sagaMiddleware = createSagaMiddleware();

const rootReducer = combineReducers({
  location: router.reducer,
  ...reducers
})
const rootEnhancer = composeEnhancers(
  router.enhancer,
  applyMiddleware(router.middleware),
  applyMiddleware(sagaMiddleware)
)
const initialState = state

const store = createStore(
  rootReducer,
  initialState,
  rootEnhancer
);

sagaMiddleware.run(initialiseApp);
router.initialDispatch();
```
My reducers function is as follows:
```
export function reducers(state = {}, action) {
  switch (action.type) {
    case 'STORE_SETTINGS_REQUEST': {
      return { ...state, uiState: ... }
    }
    case 'STORE_SETTINGS_SUCCESS': {
      return { ...state, storeSettings: ... }
    }
    case 'STORE_SETTINGS_FAILURE': {
      return { ...state, error: ... }
    }
    default: {
      return state
    }
  }
}

export default reducers
```
When running the code above, I get the error above, and debugging the app, I see that the state is set to the following:
```
{
  location: {
    pathname: '/',
    type: '@@redux-first-router/NOT_FOUND',
    payload: {},
    prev: {
      pathname: '/',
      type: '@@redux-first-router/NOT_FOUND',
      payload: {}
    },
    kind: 'load',
    routesMap: {
      length: 2,
      action: 'POP',
      location: {
        pathname: '/',
        search: '',
        hash: ''
      }
    }
  }
}
```
i.e. the state from my app is nonexistent, resulting in props undefined errors. Note, when I remove the line `location: router.reducer`, my app state is correctly initialised as follows, but obviously missing the location parameter, and induces the error mentioned above. The state is as follows:
```
{
  data: {
    ...
  },
  storeSettings: {},
  uiState: {
    ...
  },
  search: {
    ...
  },
  error: null,
  renderError: false
}
```
Is this a known issue, or am I doing something wrong, and if so, what? Thanks in advance for any assistance.

**Comment by cdoublev** [comment]
I think you have uptdated RFR without removing `history` from [args passed to `connectRoutes`](https://github.com/faceyspacey/redux-first-router/blob/master/docs/connectRoutes.md#signature). It has changed since this [commit](https://github.com/faceyspacey/redux-first-router/commit/0c2ec39cf0e404da04fac1d84c8f1d34adb3a75d#diff-e93dc268a463b8fa67c0b201239bcbc8R94).

**Comment by sashahilton00** [comment]
Thanks for the pointer, missed that. That has solved a problem not mentioned above of RFR only returning NotFound (I was passing the history const as the routes map), but I'm not sure it solves the original issue. Either way, the original issue is no longer the issue, as I have played around with things, and splitting reducers into their modular components and exporting them in an `index.js` file, then changing the `combineReducers` part to use the following code solved it:
```
import * as reducers from './reducers'
const rootReducer = combineReducers({
  ...reducers,
  location: router.reducer,
})
```
I'm 99% sure there was some sort of bad imlpementation on my behalf that I invariably fixed when modularising it without noticing, as I cannot think of any logical reason as to why this behaviour would come from Redux or RFR. Hence closing the issue, will reopen issue if problem reappears.
