### ISSUE TITLE
Issue with minimal example

### ISSUE THREAD

**Issue by hungHoangDang** [faceyspacey/redux-first-router#344]
Hi guys,

I followed the **minimal example** using `create-react-app`. I did everything the same with the instruction from [here first](https://www.npmjs.com/package/redux-first-router) and then I went to [github page](https://github.com/faceyspacey/redux-first-router) for a minor difference.

And here is my `index.js` file
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';
import { Provider } from 'react-redux';
import configureStore from './configureStore';

const store = configureStore();

ReactDOM.render(
    <Provider store={store}>
        <App />
    </Provider>,
document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```
Then I ran into this problem
```
TypeError: store.getState is not a function
```
This is the first message in the console: 
```
Warning: Failed prop type: The prop `store.subscribe` is marked as required in `Provider`, but its value is `undefined`.
    in Provider (at src/index.js:12)
```
I did a few google search and my best guess is that the issue lies in my `configureStore()` though I'm not so sure.
Can you guys please have a look and tell me what I did wrong? Many thanks!

**Comment by cdoublev** [comment]
I didn't read the whole README.md very carefully but I feel that it might be missing some details. Anyway, here is the typo:

```js
const { store } = configureStore()
```

Check https://github.com/faceyspacey/redux-first-router/blob/master/examples/minimal/src/index.js#L8.

**Comment by hungHoangDang** [comment]
Thanks man! It works well for me although I don't really understand because normally I write as I did but it doesn't work this time.

**Comment by ScriptedAlchemy** [comment]
If docs need updating for minimal to work, feel free to amend or add a note about what caught you up
