### ISSUE TITLE
Thunks returning promises

### ISSUE THREAD

**Issue by conartist6** [faceyspacey/redux-first-router#346]
First, I have spotted a bug in the existing code. Assuming `prom` is short for promise [this code](https://github.com/faceyspacey/redux-first-router/blob/3008c9485f9e1419b05079507e2183a042ed713d/src/pure-utils/attemptCallRouteThunk.js#L32) makes sense. When the thunk is done, it tries to adjust the page scroll. The problem is that `next` should be `then`.

Second, I am hoping for an improvement. If I dispatch a routing action that results in a thunk being called and that thunk returns a promise, I would hope that the entire routing action would return that thunk's promise. Otherwise it is not possible for me to trigger some routing action and understand when it has completed.

**Comment by conartist6** [comment]
Also the `redirect` action creator would lose that promise since it needs to return the action for non-thunk action creators. Fortunately the `setKind` method is exported from the library so it will still be possible to create a userland helper which dispatches a history-replacing action and returns the thunk's promise.

**Comment by conartist6** [comment]
I think it should be possible to get the route thunk promise from the router state as well

**Comment by hedgepigdaniel** [comment]
Re the improvement, this is a specific case of https://github.com/faceyspacey/redux-first-router/issues/90 and is addressed generally in [Rudy](https://github.com/respond-framework/rudy)

In Rudy, callbacks like `thunk` honour promises returned. Dispatching an action returns a promise that resolves when the entire pipeline of asynchronous middlewares (`thunk`, `beforeChange`, `afterChange` and others) have completed in order.

**Comment by conartist6** [comment]
Any insight on when Rudy will be ready?

**Comment by hedgepigdaniel** [comment]
Ready is a relative term.

At OpenLearning we are using it in production, and I know a few others are also.

Docs are very sparse at the moment but if you're familiar with RFR you'll work it out without too much trouble.
