### ISSUE TITLE
Fallback to `back` in case it would leave the website

### ISSUE THREAD

**Issue by gustavopch** [faceyspacey/redux-first-router#347]
Let's analyze two history flows at Twitter's website (second one is the most important):

Flow A:
---
- You enter Twitter's home page.
- You click to open a specific tweet, `History.pushState()` occurs and the tweet is displayed in a modal.
- You click outside the modal, `History.back()` occurs.

Flow B:
---
- You go directly to a permalink of a tweet and it's also displayed in a modal.
- You click outside the modal and **because using `History.back()` would throw you out of the website**, `History.replaceState()` is used instead to take you to what you expect to be the previous page.

Proposal
---
I propose that the `back` method, when used in web, should accept a `fallback` parameter to be used like in the following pseudo-code:
```
function back(fallback) {
  if (fallback != null && !prevRouteExists()) {
    history.replace(...)
  }

  history.goBack()
} 
```
I'm currently doing this by checking whether `location.prev.type !== ''` to know whether there's a previous route or not so that I can decide whether I'll use `back` or `replace`, but I think this behavior is so critical to UX that it should be managed by the lib.

**Comment by hedgepigdaniel** [comment]
> because using History.back() would throw you out of the website, History.replaceState() is used instead to take you to what you expect to be the previous page

It seems like what you want the app to do when you click outside the modal is to close the modal, but instead you have effectively pressed the back button. Why not dispatch an action that closes the modal?

If you want the actions that open and close the modal to not be included in the back button, then you can make those actions redirects.

Does that solve your problem?
