### ISSUE TITLE
Regex path parameter matching for Guids are not working

### ISSUE THREAD

**Issue by rebyul** [faceyspacey/redux-first-router#348]
I have a path in my route map that looks like this:

pathKey: {
path:  '/somePath/:id'
}

I needed this to be a required matched path with only valid Guid values for :id so I changed the path to 
/somePath/:id([a-fA-F0-9]{8}-([a-fA-F0-9]{4}-){3}[a-fA-F0-9]{12})
which matches the guids I am receiving from the server 
example id: eee26e3e-c189-411d-ad0f-54043f2507fc

It only works when I change the path regex matcher to:
/somePath/:id([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})

Does the rudy match regex parser not play nicely with multiplicity rules on groups?
Thanks in advance :)

**Comment by hedgepigdaniel** [comment]
`[a-fA-F0-9]{8}-{3}[a-fA-F0-9]{12}` looks like that would only match three hyphens in a row?

**Comment by rebyul** [comment]
So sorry i'll update the question!

**Comment by hedgepigdaniel** [comment]
I'm not sure if it does or why/why not, but you could perhaps start by checking if `path-to-regexp` as used by `redux-first-router` via `rudy-match-path` supports it - see
- https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/pathToAction.js#L36
- https://github.com/faceyspacey/rudy-match-path/blob/master/src/index.js
