### ISSUE TITLE
Using basename doesn't work in RFR 2. But it works in RFR rudy.

### ISSUE THREAD

**Issue by re6exp** [faceyspacey/redux-first-router#349]
The problem is described [here](https://muffinman.io/react-router-subfolder-on-server/).

In RFR#rudy this code works well:
```
const { store } = configureStore(window.REDUX_STATE, { basename: '/admin' })
```
If I try to use basename with RFR 2, using the history package, the prefix doesn't being included:
```
//SSR
import {createMemoryHistory} from 'history'
...
const history = createMemoryHistory({ initialEntries: [req.path], basename: '/admin' })
const { store, thunk } = configureStore(history, preLoadedState)
```
or in the client code:
```
import {createBrowserHistory} from 'history'
...
const history = createBrowserHistory()
const { store } = configureStore(history, window.REDUX_STATE, { basename: '/admin' })
```

I've tried this with old versions of deps and with latest, with the same result.

**Comment by hedgepigdaniel** [comment]
Have you passed the `basename` option to `connectRoutes`? https://github.com/faceyspacey/redux-first-router/blob/master/docs/connectRoutes.md#options

**Comment by re6exp** [comment]
I did all possible. And, in that time I had participation in basename introducing to rfr...

My first prototype was based on rudy so I change only deps versions of egg and rfrl, update them and change the signature of connectRoutes method corresponding to rfr 2.

At the moment it works but with rudy version of rfr and rfrl.

**Comment by hedgepigdaniel** [comment]
The code you've put in the description doesn't have a call to `connectRoutes`, and according to the docs that's where the `basename` option is passed in.

**Comment by re6exp** [comment]
Yep, that is my omission. But the option is using there, I swear you. :)
I checked.

**Comment by re6exp** [comment]
For a few points, I had to check them all.
It was my fault. Everything is working.
One less problem!

Thank you for force me to review what I've done. :)
