### ISSUE TITLE
Docs are wrong

### ISSUE THREAD

**Issue by conartist6** [faceyspacey/redux-first-router#350]
The docs for [history types](https://github.com/faceyspacey/redux-first-router/blob/master/docs/connectRoutes.md#history-types) are incorrect. They tell you to import create history as follows if you need to dictate a particular history implementation.

```js
import createHistory from 'history/createBrowserHistory'
// or
import createHistory from 'history/createMemoryHistory'
```

This is incorrect. The paths it should give are:
```js
import createHistory from "rudy-history/createBrowserHistory";
// or
import createHistory from "rudy-history/createMemoryHistory";
```

**Comment by ScriptedAlchemy** [comment]
Thanks I’ll update this
