### ISSUE TITLE
onAfterChange 

### ISSUE THREAD

**Issue by bradcrawford** [faceyspacey/redux-first-router#351]
Hi there, I'm looking for clarification as to the expected behaviour of `onAfterChange` when redirecting during an `async` thunk. My understanding (based on https://github.com/faceyspacey/redux-first-router/issues/96) is that if a redirect action is dispatched during the thunk, the `onAfterChange` should not get run but this is not what I am seeing.

I have put together a simple CodeSandbox to demonstrate - https://codesandbox.io/s/q8y5k9vv3q. The relevant parts are:
```
// Simulate network request
function timeout(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

...

const routesMap = {
  HOME: "/",
  USER: {
    path: "/user",
    thunk: async (dispatch, getState) => {
      await timeout(3000);
      dispatch(redirect({ type: NOT_FOUND }));
    }
  }
};

...

const { reducer, middleware, enhancer } = connectRoutes(routesMap, {
  onAfterChange: (_dispatch, _getState, bag) => {
    console.log("afterChange", bag);
  }
});
```

With this setup, calling `dispatch({ type: 'USER' })` results in the `onAfterChange` callback running once for the transition to the `/user` route and then a second time after the redirect to `/not-found`

What I am basically trying to achieve is to handle network/auth token errors during the route transition, redirecting if appropriate (auth token expired >`/login`, 404 -> `/not-found`), without triggering the `onAfterChange` callback for the route transition that triggered the redirect.

This is quite possibly user error or a misunderstanding on my part but have I missed something obvious here?

Thanks for your work putting together such a fantastic library!

**Comment by hedgepigdaniel** [comment]
This issue is a specific case of https://github.com/faceyspacey/redux-first-router/issues/90 and is addressed generally in [Rudy](https://github.com/respond-framework/rudy)

In Rudy, callbacks like `thunk` honour promises returned, which means that the route transition would be delayed in your example until after the redirect occurred (vs in RFR where the only way to stop it is to **synchronously** dispatch a redirect)
