### ISSUE TITLE
Page reducer returns initial state not current route

### ISSUE THREAD

**Issue by gitstud** [faceyspacey/redux-first-router#355]
Using React Universal Component and Express

![Screen Shot 2019-05-22 at 6 46 33 PM](https://user-images.githubusercontent.com/19921972/58220034-0face700-7cc2-11e9-97b4-f41baa229b16.png)

![Screen Shot 2019-05-22 at 6 46 55 PM](https://user-images.githubusercontent.com/19921972/58220039-150a3180-7cc2-11e9-9e1e-c7c026b264bc.png)

Pretty stuck on this one, any help is appreciated!

**Comment by gitstud** [comment]
Figured it out, the page reducer needed to be included in the server side createStore call.

**Comment by ScriptedAlchemy** [comment]
Yyyuuup!

**Comment by ml242** [comment]
someone was smoking something...
