### ISSUE TITLE
usage routesMap with redux-saga

### ISSUE THREAD

**Issue by maystrenkoYurii** [faceyspacey/redux-first-router#358]
How integration with redux-saga in routesMap? Not found in docs

**Comment by davidjnelson** [comment]
Does this work?

https://medium.com/@bryanfillmer/a-redux-first-router-saga-67c2cda9252e

**Comment by ScriptedAlchemy** [comment]
@re6exp do you have any insights? If so would you be interested in helping me add some examples to a readme?

**Comment by re6exp** [comment]
In thunk (), you post some kind of initial action and catch it somewhere in your sagas by takeLatest(). This first comes to my mind.
