### ISSUE TITLE
Run thunks when the hash change

### ISSUE THREAD

**Issue by HenriqueLimas** [faceyspacey/redux-first-router#366]
I have a use case where every time the hash is changed I should run the thunk on it (Similar to #254). Basically I am considering the hash as a query, but I am not using query for SEO limitations.

Example I am on `/my-url/#hash1=123`, if I go back or go to `/my-url/#hash1=123&hash2` the thunk should run again. 
From the code I saw that the action are dispatched only when `location.pathname + location.search` are different. ([Code here](https://github.com/faceyspacey/redux-first-router/blob/a8f3bb3995089f1a9355ca596ce20987e10ee572/src/connectRoutes.js#L571))

It would be nice to have a way to consider also the hash or provide a function like `shouldDispatchAction(currentPath, location)` that is used in that line of code.

The main idea

```js
const defaultShouldDispatchAction = (currentPath, location) => currentPath !== pathnamePlusSearch(location);

const shouldDispatchAction = options.shouldDispatchAction || defaultShouldDispatchAction
...

const _historyAttemptDispatchAction = (store, location, historyAction) => {
  if (shouldDispatchAction(currentPath, location)) {
     ...
  }
}
```

The problem with that solution is that the current logic is based on the `currentPath`. So it needs to change a bit.

Another proposal would be to have a `mapPathToCheck(location)` function like that: 
```js
const _historyAttemptDispatchAction = (store, location, historyAction) => {
  const nextPath = mapPathToCheck(location);

  if (currentPath != nextPath) {
    ...
  }
}
```

The way I am solving this right now is to overwrite the `history.listen` method on the createHistory option. Something like that:

```js
  const createHistory = (...args) => {
    const history = createBrowserHistory(...args);
    const _listen = history.listen.bind(history);

    history.listen = fn => {
      return _listen((location, historyAction) => {
        const newLocation = {
          ...location,
          search: location.search + location.hash,
        };
        return fn(newLocation, historyAction);
      });
    };

    return history;
  };

connectRoutes({
  createHistory
})
```

But the problem with that solution is that it's depends on the logic that the `redux-first-router` is dealing that under the hood. If the logic change, this will break.

**Comment by hedgepigdaniel** [comment]
This issue is addressed in Rudy with the help of this PR (not yet merged): https://github.com/respond-framework/rudy/pull/66

Rudy includes hashes as part of the routing action, so its possible to dispatch a routing action that consists of the current route and a changed hash, and then the `thunk` will run again for the route.
