### ISSUE TITLE
Remove routes action?

### ISSUE THREAD

**Issue by dbartholomae** [faceyspacey/redux-first-router#368]
Hi there!

I'm currently thinking about how to best use this library with [redux-dynamic-modules](https://github.com/microsoft/redux-dynamic-modules/), a library that allows to easily split redux related code across features by organizing it in modules. After sifting through the code I found the ADD_ROUTES action which seems to be a perfect fit: On store creation I could start off with an empty routesMap and when loading a module the module could dispatch an ADD_ROUTES action to add in the missing routes.
For full compatibility though it would be best to also remove routes when the module is removed, e. g. by firing a REMOVE_ROUTES action. Is there a specific reason this action is not included? Would you be open to a PR?

Best,
Daniel

**Comment by ScriptedAlchemy** [comment]
might be worth looking over here. https://github.com/respond-framework/rudy we have moved development efforts to a new project
