### ISSUE TITLE
Clarify query string action to matching route map

### ISSUE THREAD

**Issue by Maushundb** [faceyspacey/redux-first-router#51]
I'm trying to add a query parameter to one of my routes, using:

```
<Link to={{type: 'SEARCH', payload: {find: this.state.findValue /* string */}}}> Blah </Link>
```

With the route

```
{
  SEARCH: '/search',
}
```
Ive also tried adding the query field, dased on [these docs](https://github.com/faceyspacey/redux-first-router/blob/master/docs/query-strings.md):

```
<Link to={{type: 'SEARCH', payload:  {find: this.state.findValue /* string */}}}> Blah </Link>
```

As well as adding a dynamic field to my route map:

```
{
  SEARCH: '/search/:find',
}
```

But I can't seem to get RFR to change my query string for me. I have to do something like 

```
{
  SEARCH: '/search?find=:find
}
```

To get the query string to show up at all. But from your [live example](https://codesandbox.io/s/pgp5mEkzm?module=H1Ebz7rL7rZ) it seems that I shouldn't need to manually code the query string in the route. In addition, I never find my query at `store.getState().location.query` after I click my link.

So with that all said, what is the proper mapping between what you supply to Link to={...} and what your route looks like in your routes map, in order RFR create the query string for you?

**Comment by faceyspacey** [comment]
You don't supply a string. You supply a query object like this:

```js
<Link to={{type: 'SEARCH', payload:  { find: findValue }, query: { foo: 'bar' }}>
```
or like this:
```js
<Link to={{type: 'SEARCH', payload:  { find: findValue, query: { foo: 'bar' } }}>
```
or like this:
```js
<Link to={{type: 'SEARCH', payload:  { find: findValue }, meta: { query: { foo: 'bar' } } }}>
```

**Comment by faceyspacey** [comment]
I probably should have pasted some full examples to of action objects to that readme file. Feel free to supply a PR.

**Comment by Maushundb** [comment]
Happy to submit a PR once I get it figured out. What's the associated route map look like for those choices you gave?

**Comment by faceyspacey** [comment]
path: /whatever-you-want/:key

...the query is never in the path, as it doesn't determine the action type to dispatch. only the path does. The query is an *extra* with the special powers of changing the URL string appended, but without changing the type dispatched. Hope that makes sense.

**Comment by Maushundb** [comment]
Yeah that makes perfect sense, I'm just not getting the behavior I think I should. For example:

```
// In '/' markup
<Link
  className={styles.button}
  to={{
    type: 'SEARCH',
    payload: {query: {find: this.state.findValue}},
  }}
>
 ...
// routeMap
{
    LANDING: '/',
    SEARCH: '/search/:find',
}
```

Seems to just throw a warning upon loading:

```
[redux-first-router-link] could not create path from action: { type: 'SEARCH', payload: { query: { find: 'value' } } } For reference, here are your current routes: { LANDING: '/', SEARCH: '/search/:find' }
```

And then redirects me to the search route? I'm looking for the route to look like`/search?find=value`

**Comment by faceyspacey** [comment]
can you make a codesandbox to reproduce it.

**Comment by faceyspacey** [comment]
sorry. ...the way u do that is take :find out of the path. it doesnt belong there. queries and path params are different.

**Comment by faceyspacey** [comment]
:find cant be in the query. it needs to be in the payload. i.e. payload: { find: foo

...basically make ur path this:

SEARCH: '/search'

and ur action this:

{ type: 'SEARCH', query: { find: value } }

**Comment by KaRkY** [comment]
@Maushundb Did you supply query string serializer to RFR options?

@faceyspacey Maybe you schould add to docs that you need a query serializer like query-string. I don't know if I overlooked that part in the docs but I needed good 20min to figure it out why there was no query part in my URL.

**Comment by faceyspacey** [comment]
oh shit. i totally i forgot about that. my bad. i'll add it now.

**Comment by Maushundb** [comment]
No, I did not do that haha! Something like:

```
  import queryString from 'query-string';
  const {reducer, middleware, enhancer, thunk} = connectRoutes(
    history,
    routesMap,
    {
      querySerializer: queryString,
    };
,
  );
```

Sound about right?

Gives me the following error, which seems to be a step in the right direction:

```
vendor.js:444 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) div><a href="/search" class="SearchBar__
 (server) div><a href="/search?find=value" class="

```

Seems like that did something, but that SSR isn't liking it.

**Comment by faceyspacey** [comment]
maybe stop/start the app instead of rely on HMR. as store creation isn HMRed.

**Comment by faceyspacey** [comment]
ok, the docs are updated:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/query-strings.md

@Maushundb did you get it working?

**Comment by Maushundb** [comment]
Not yet, it seems that the SSR is getting it right, but the client isn't for some reason (Turning off JS on the page in dev makes it work!). I'm certainly closer, but I'll get back to it in the morning. I'm using your demo app as a base if it makes anything come to mind. Thanks for the fast help so far, stoked to get this working!

**Comment by Maushundb** [comment]
Ok got it working. No ideas what was going on, but deleting node_modules then reinstalling seems to have fixed the error. Must have been some weird caching issue or a bad package interaction for anyone reading this with the same issue. Closing the issue for now, thanks again for the support @faceyspacey and for updating the docs!

**Comment by primozs** [comment]
I also have some issues seting up query string support.
query string does not get into the state:
I was using     
"redux-first-router": "^0.0.4-rudy",

when I did yarn upgrade 
"redux-first-router": "^0.0.16-next"

I got
```
error: (MODULE_NOT_FOUND) Route: /?s=2&b=3
```

I did server restart in both cases.

my query string parser is qs
```
import Qs from 'qs';

added to options like this to connectRoutes
querySerializer: Qs,
```

```
I have tryed this and by the docs the api should be ok, functions are there
Qs object has both, Qs.parse and Qs.stringify

in the case of 
"redux-first-router": "^0.0.4-rudy",
I got no error just not query parameter anywhere in the location state
```
Its a bit late here I will check more tomorrow.
cheers

**Comment by faceyspacey** [comment]
does it work on older versions of RFR?

**Comment by primozs** [comment]
I was checking now 1.9.19 and in the code connectRoutes. The problem I have is that I need extra parmeter on the setup. It seams that connectRoutes in the master is not supporting this yet.

```
my rudy setup,
query serializer is in the options
const { reducer, middleware, enhancer, thunk } = connectRoutes(
    routesMap,
    { ...options, extra: services, initialEntries }
  );
```

**Comment by faceyspacey** [comment]
can you try to find the issue with queries in the latest issue? it could be the redux-first-router-link package. search the code for `getOptions`.

here's where you will find the 2 usages:

https://github.com/faceyspacey/redux-first-router-link/blob/rudy/src/toUrl.js#L9

https://github.com/faceyspacey/redux-first-router-link/blob/rudy/src/handlePress.js#L40


....try isolating your app temporarily to not use the link package and quickly verify if it's the link package causing the issue. 

If that's not the issue, find where it's used in the main rfr package in a similar way, and just add logging before and after its usage and see if you see anything wrong. If you can give me intel, i can quickly fix it.

**Comment by primozs** [comment]
Back on rudy I have tried a few more things. Should I open another issue?

If I dispatch an action like this on the client
```
props.dispatch({
   type: 'ROUTE_HOME',
   payload: { query: { a: 2, b: 3 } }
})
```

then in the location state I get
```
query: {
   a:2,
   b:3
},
search:"a=2&b=3"
```
but on the page reload of ``` http://127.0.0.1:8888/?a=2&b=3 ```
query and search are not in the state so it seams it server side issue

**Comment by faceyspacey** [comment]
oh, this isn't an issue with RFR. it just needs better documentation. if you're using express, `request.path` does not contain the query. You need to append it manually. See this:

https://github.com/faceyspacey/redux-first-router/issues/56#issuecomment-318880126
https://www.npmjs.com/package/query-string

If you could update the query string doc, i'd greatly appreciate it.

**Comment by primozs** [comment]
Thx I will look into this!
Cheers

**Comment by primozs** [comment]
Hi,
It works I get params and query in the state. On the server I did. 
```
  const { store, thunk } = configureStore(preLoadedState, {
    services,
    // initialEntries: [req.path]
    initialEntries: [req.originalUrl]
  });
```
Should I make PR for the docs against master or rudy?

**Comment by faceyspacey** [comment]
master. thanks @primozs ! ..make sure to be explicit about what must be in there (path + query). I.e. dont just assume everyone is using express. So make note that often these server routing frameworks separate the path + query, so they must be re-combined, or u must find a string that has them pre-combined like apparently `req.originalurl` has :)
