### ISSUE TITLE
SSR'd React components depending on query not matching client

### ISSUE THREAD

**Issue by Maushundb** [faceyspacey/redux-first-router#56]
When use in conjunction with SSR, it seems that when rendered on the server, the location state object doesn't container the query. So, a mapStateToProps like:
```
const mapStateToProps = ({location}) => {
  return {
    tabActive:
      get(location, ['query', 'find'], null) ===
      Constants.FIRST_OPTION,
  };
};
```

Gets the checksum react error for server markup not matching client markup, since on the server location.query is not present, yet on the client it is. Is there a proper way to access the query string from the server side rendering pass?

**Comment by faceyspacey** [comment]
How to you set initialEntries on the server.

I actually haven't done it but you would need to combine the search and the query string.

**Comment by faceyspacey** [comment]
request.path does not contain the query

**Comment by Maushundb** [comment]
Sorry, updated the comment with something more descriptive.

**Comment by faceyspacey** [comment]
Can u paste how u create the story server side.

**Comment by Maushundb** [comment]
Ah ok, it seems like I'm setting only req.path on the server.
```
  const history = createHistory({ initialEntries: [req.path] })
```

Will probably want to add in the query, which I'm guessing will populate `location` as well?

**Comment by faceyspacey** [comment]
Exactly. You have to manually recreate /path?query=foo

Look at the history API. I forget but it might take a location object instead of a string which will be easier for you to provide without string creation.

Also log history.location after you create the history. If it has the query on it, it will work. ..crossing my fingers that the history memory package works the same as the browser one.

**Comment by Maushundb** [comment]
Yup, doing 
```
  const path = req.path + (isEmpty(req.query) ? '' : '?' + queryString.stringify(req.query));
  const history = createHistory({ initialEntries: [path] })
```

Seems to have done the trick! Cheers.
