### ISSUE TITLE
Initial load action not triggering thunk (client-only use case)

### ISSUE THREAD

**Issue by mspae** [faceyspacey/redux-first-router#59]
Hello! First off: awesome library, I really like the idea behind it!

I'm currently working on an app which will not have SSR.

I'm just refactoring the data fetching strategy from `componentDidMount` to within thunks. (As outlined here: https://medium.com/faceyspacey/redux-first-router-data-fetching-solving-the-80-use-case-for-async-middleware-14529606c262)

However I've noticed that on the initial load action. (I.e. I go to `/`, triggering the respective action defined in `routesMap`) it doesn't trigger the thunk. Now if I understand correctly this has to do with the SSR-aligned philosophy: The state should come from initial state from the reducer when rendering on the server. In my case however this is not viable because I don't have a server behind the app which can create initial state.

My question is this: What's the recommended way of doing this? What am I missing?

**Comment by faceyspacey** [comment]
I dont suppose you can make a repro or a codesandbox. If you look at this codesandbox:

https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox/tree/master/?initialpath=%2Flist%2Ffp&module=BydW1Lh7u8b

you will see it calls the thunk attached to the `LIST` type on load. 

Here's the logic to determine whether to call that first thunk:

https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/attemptCallRouteThunk.js#L20

Have you checked the devtools and confirmed the correct route type is initially dispatched at all?

Here's a screenshot of the what the devtools is showing:
![screen shot 2017-08-01 at 2 11 23 am](https://user-images.githubusercontent.com/154732/28818011-c43f7730-765e-11e7-8c17-4f8f854b324a.png)

Make sure you're logging the thunk attached to the initial type dispatched, etc.

Perhaps you are using RFR+Redux on the server and rehydrating and didn't know it (e.g. as part of some boilerplate), but without calling `await thunk` on the server and therefore not getting data to rehydrate from. Besides a bug, that's the only case that would trigger this.

If RFR runs in the server at all, it will think it's running in an SSR context.

**Comment by mspae** [comment]
Hello. Thanks for getting back to me so quickly on this!!

I reduced the codesandbox and it works there. I can confirm that a) the load action is dispatched b) I am indeed logging the thunk, so I would see if it is called.

![routesmap](https://user-images.githubusercontent.com/1044829/28820612-92a9c258-76b2-11e7-9249-800af2ff14fc.png)

![actionlog](https://user-images.githubusercontent.com/1044829/28820530-4e52a084-76b2-11e7-80bb-d9b8ab039f8d.png)
= No message in log.

I am using `webpack-dev-server` – But the issue also appears when I build a file bundle.

I've added debugging statements to `attemptCallRouteThunk.js` but it is apparently not an issue in that file as the function isn't even being called on first load with me.

This is my store creation setup: https://gist.github.com/mspae/e831468187d2179c2dc07ee149ca6258

I will have a go at finding out why attemptCallRouteThunk is not being called.

**Comment by faceyspacey** [comment]
whats in your `routeOptions`

**Comment by mspae** [comment]
```javascript
import {
  NAVIGATE_TO_DEFAULT,
  NAVIGATE_TO_LOGIN,
  NAVIGATE_TO_LOGOUT,
  NAVIGATE_TO_PAGE
} from './action-types';

// this object is passed to redux-first-router as an object of callbacks and
// can be used for authentication and other global tasks
export const routeOptions = {}

// we use redux-first-router, so this is actually not part of our
// regular redux stack but is used in create-store as routing config for
// redux-first-router
// @see https://github.com/faceyspacey/redux-first-router
const routesMap = {
  [NAVIGATE_TO_DEFAULT]: {
    path: '/',
    thunk: (dispatch, getState) => {
      alert('navigated to default!!');
    }
  },
  [NAVIGATE_TO_LOGIN]: '/login',
  [NAVIGATE_TO_LOGOUT]: {
    path: '/logout',
    thunk: (dispatch, getState) => {
      api.user.logout().then(() => {
        console.log('loggedout');
        dispatch(logoutAction());
        dispatch(redirect({
          type: NAVIGATE_TO_LOGIN
        }));
        dispatch(setSuccessStatusAction('Logged out succesfully!'));
      });
    }
  },

  [NAVIGATE_TO_PAGE]: {
    path: '/page/:id',
    thunk: async (dispatch, getState) => {
      const state = getState();
      const user = getUser(state);
      const  { id, session } = state.location.payload;

      const page = await api.page.read(user, id);
      dispatch(loadPageAction(page));
    }
  }
}

export default routesMap;
```

**Comment by mspae** [comment]
So apparently the problem is that the middleware is called with the action after route load action (https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L199) Which is kind of weird. Thats why `var route = routesMap[action.type];` returns undefined and `beforeRouteChange` and `after...` isn't called. So there seems to be something messed up with my middleware config.

**Comment by faceyspacey** [comment]
put `redux-localstorage` and as the last enhancer. if that doesnt work, put the thunk middleware last. RFR should come as early as possible. I've been meaning to document this.

**Comment by mspae** [comment]
Awesome. that did it! Thanks for your time & keep up the good work!

**Comment by faceyspacey** [comment]
Not a problem. Enjoy!

**Comment by pvpshoot** [comment]
Hi, i have the same issue, but initial `onBeforeChange` didn't happen
this is my config https://gist.github.com/pvpshoot/a24314c85b30c1cea3b5277f13af9594
with or without redux-thunk it doesn't work
RFR - 1.4.2
i just use create react app
