### ISSUE TITLE
`redirect(...) => action.meta.location.current === undefined`

### ISSUE THREAD

**Issue by sdougbrown** [faceyspacey/redux-first-router#60]
https://github.com/faceyspacey/redux-first-router/blob/edad20c402d058a00c1ee2b7f43b92e32a168916/src/reducer/createLocationReducer.js#L20

https://github.com/faceyspacey/redux-first-router/blob/edad20c402d058a00c1ee2b7f43b92e32a168916/src/pure-utils/setKind.js#L6

Using the `redirect` ActionCreator results an undefined `current` location object, and throws when it hits the reducer.

I'd like to nail this down for you and create a PR, but I don't think I'll have time today.   Thanks for your work on this so far. 😄

**Comment by sdougbrown** [comment]
FWIW, here's how I've had to work around this so far...

```
import { actionToPath } from 'redux-first-router';
import { assocPath } from 'ramda';
import * as PAGES from './actions/pages';

type Route = $Values<typeof PAGES>;

export const routesMap = {
  ... // mapped from `PAGES`
};

function createRedirect(route: Route, ops?: Object) {
  const action = {
   // `ops` is an object that could potentially contain a `payload` param...
    ...ops,
    type: route,
    meta: {
      location: {
        current: {},
        kind: 'redirect',
      },
    },
  };

  return assocPath(['meta', 'location', 'current', 'pathname'], actionToPath(action, routesMap), action);
}
```

This is obviously a lot of overhead for a simple action creator - not sure if it'd need to do this much if implemented in this lib. 😄

**Comment by faceyspacey** [comment]
I've been meaning to get to this, but basically the reducer shouldn't be receiving an almost raw action. It's supposed to be transformed by the middleware to have all the additional stuff on the action. 

Can you log the action as it first hits the middleware, before next is called in the middleware and when it hits the reducers. And then paste the 3 logs here.

Basically you shouldn't have to make the action creator do any more than tag the action with the kind. The middleware is supposed to apply the rest, but for some reason it's not happening.

**Comment by sdougbrown** [comment]
yeah it sure looks like the middleware is skipped entirely...

here's the redirect sequence:
```
raw middleware action: {type: "@@page/dashboard", payload: Object, meta: Object}
skipped, before next undefined Object {type: "@@page/dashboard", payload: Object, meta: Object} 
action in reducer Object {type: "@@page/dashboard", payload: Object, meta: Object}
action in reducer Object {payload: Object, type: "@@page/dashboard/photos", meta: Object}
```

Note how there's no middleware logs for `@@page/dashboard/photos`.  That's the whole ballgame.

I've also noticed that back/forward actions also seem to skip the middleware (no `onAfterChange` fires, subsequent middleware never sees the action either). 
 Additionally, I noticed that`onBeforeChange/onAfterChange` are provided a `dispatch` that skips other middleware as well.  With all of these disparate utilities missing the middleware, I feel like there's a strong chance that the issue is in `connectRoutes`, but I'm not sure I can provide you a solution.  Happy to help though.

**Comment by faceyspacey** [comment]
Do you you can provide a repro?

**Comment by tim-mc** [comment]
FWIW, I was experiencing this same problem until I realized that I had my `enhancer` and `applyMiddleware()` returned value switched in `composeEnhancers`. I went from:

```
	const appliedMiddleware = applyMiddleware(...middlewares.concat(additionalMiddlewares));
	const composedEnhancers = composeEnhancers(appliedMiddleware, enhancer);
	const store = createStore(
		combineReducers(reducers),
		preloadedState,
		composedEnhancers,
	);
```

to: 

```
	const appliedMiddleware = applyMiddleware(...middlewares.concat(additionalMiddlewares));
	const composedEnhancers = composeEnhancers(enhancer, appliedMiddleware);
	const store = createStore(
		combineReducers(reducers),
		preloadedState,
		composedEnhancers,
	);
```

This was causing an issue with redirects as well as with calling my `onBeforeChange` function on initial load (none of my actions were making it through any sort of middleware since they were being registered *after* the initial location action was dispatched).

**Comment by tim-mc** [comment]
To be clear, after I made the above change, my creation and dispatching of the redirect action could be returned to the way described in the documentation, e.g.:

```
const redirectAction = redirect({
  type: 'LOGIN',
});
dispatch(redirectAction);
```

**Comment by sdougbrown** [comment]
@tim-mc Thank you!  Initial testing is promising.  The `README` does have the enhancer listed first, but I hadn't noticed that the order was important.  I'm happy to add a PR to update the docs to call this out to help others avoid the same mistakes if @faceyspacey thinks that'd be valuable. 😄

**Comment by faceyspacey** [comment]
I do. Need as much help as possible. Thanks guys!

**Comment by faceyspacey** [comment]
docs updated. muchos gracias!!
