### ISSUE TITLE
Calling the location reducer "location"

### ISSUE THREAD

**Issue by GuillaumeCisco** [faceyspacey/redux-first-router#66]
Hello,

By using redux-first-router which is amazing and clearly is the tool I always wanted for dealing with routes in redux, I found that calling the location reducer location can lead to dumb avoidable errors.

Indeed when destructing the state in a function, we can mistakenly make calls to `window.location` xD
Example:
```javascript
const f = ({location: type}) => console.log(location);
```
This code won't raise errors, and will log the `window.location` variable.
If the reducer where called for example `routing`:
```javascript
const f = ({routing: type}) => console.log(routing);
```
It will correctly raise an error.

I'd like to highlight this behavior because it cost me some weird interpretation ^^"
Maybe we should make a line in the README about that or changing the reducer name in the examples.
I know it is something small and not an issue, but wanted to share it for others ;)

Thanks,

**Comment by Qw-in** [comment]
Seems reasonable, I would put forward `route` as an option too. Just seems to align more with `location` to me

**Comment by faceyspacey** [comment]
I'm open to a troubleshooting.md that starts to list such things. Trying to not add too much cognitive overhead to the readme itself.

I'm going to close it, but feel free to re-open it in the form of a PR.

**Comment by GuillaumeCisco** [comment]
@faceyspacey, just made a PR for it ;)
https://github.com/faceyspacey/redux-first-router/pull/72
Hope it helps
