### ISSUE TITLE
dispatching redirect on client fires two actions

### ISSUE THREAD

**Issue by veddermatic** [faceyspacey/redux-first-router#67]
Given this code in my `options`:

```javascript
export default {
    onBeforeChange: (dispatch, getState, action) => {
        if( action.type !== 'LOGIN' ) {
            const loginAction = {type: 'LOGIN'};
            const _loginRedirect = redirect( loginAction );
            dispatch( _loginRedirect );
        }
    }
}
```

With these routes:

```javascript
export default {
    HOME: '/',
    FORGOT_PASSWORD: '/forgot-password',
}
```

Why does dispatching `{type: 'FORGOT_PASSWORD'}` result in __two__ `HOME` actions being fired?  Both appear identical and happen near instantaneously:  

![doublehome](https://user-images.githubusercontent.com/322479/28984953-59296082-792e-11e7-871c-6d3f8c3a3e39.png)

Is this something I am causing to happen? Is it intentional? If so, what is the rationale behind it. Just curious if there's some benefit to it being called twice, or if it's a bug.

**Comment by faceyspacey** [comment]
Can you try navigating to another route first without a redirect, and then navigate to the link you want to redirect from. That way we can find out if it's just an issue on first load.

Also, if you could provide a minimal repro, that would help. I would like to get this one figured out with you.

**Comment by veddermatic** [comment]
I will be working on a test project to duplicate soon, FYI.

**Comment by manubo** [comment]
I am experiencing the same thing. When I redirect in the onBeforeChange callback, the redirect-action gets fired twice.

I have noticed that in the second action, the `location`'s `current` and `prev` objects are the same. I am using this to ignore the second action in the handler, but it is a hack.

For further clarity, here are my two dispatch action objects:
- the first redirect action
```
{
  type: 'ROUTE_SETTINGS_SUBSCRPTIONS',
  meta: {
    flash: {
      error: 'You don't have a valid subscription. Select one to continue.'
    },
    location: {
      current: {
        pathname: '/settings/subscriptions',
        type: 'ROUTE_SETTINGS_SUBSCRPTIONS',
        payload: {}
      },
      prev: {
        pathname: '/invoices/unbilled',
        type: 'ROUTE_INVOICES_UNBILLED',
        payload: {}
      },
      kind: 'redirect'
    }
  },
  payload: {}
}
```
- the second redirect action
```
{
  type: 'ROUTE_SETTINGS_SUBSCRPTIONS',
  meta: {
    flash: {
      error: 'Du hast kein gültiges Abonnement. Wähle ein neues Abonnement aus, um fortzufahren.'
    },
    location: {
      current: {
        pathname: '/settings/subscriptions',
        type: 'ROUTE_SETTINGS_SUBSCRPTIONS',
        payload: {}
      },
      prev: {
        pathname: '/settings/subscriptions',
        type: 'ROUTE_SETTINGS_SUBSCRPTIONS',
        payload: {}
      },
      kind: 'redirect'
    }
  },
  payload: {}
}
```

**Comment by faceyspacey** [comment]
Can u do a manual logging in your reducer and see if it appears twice.

The way redirects word is the initial action is dispatched but when it reaches the RFR middleware it's short circuited before proceeding to the next middleware or reaching reducers. A new action is dispatched.

**Comment by faceyspacey** [comment]
Either way I need a repro. You can make one on codesandbox.

**Comment by manubo** [comment]
I will try to create a repro on codesandbox later today. 

Please note that the initial action is not dispatched, as expected. But the new action is dispatched twice.

Will let you know about codesandbox.

**Comment by faceyspacey** [comment]
Twice in the devtools of twice in reality, is if u manually log a reducer receiving it? The devtools may log something that doesn't happen.

For the sandbox try to use the repo already on there as the base.

**Comment by manubo** [comment]
Yes, the new action reaches my root reducer twice. I have a middleware which shows an alert message if the action has a `meta.flash` key. The alert is shown twice, that's how I noticed.

**Comment by faceyspacey** [comment]
fyi, i've reproduced this. i'll fix it.

**Comment by manubo** [comment]
Thanks @faceyspacey

And also thanks for this fantastic router and your great work 👍

**Comment by faceyspacey** [comment]
Sorry for the wait. This is fixed. do `yarn upgrade redux-first-router@next`.
