### ISSUE TITLE
Render nested routes

### ISSUE THREAD

**Issue by lauritzsh** [faceyspacey/redux-first-router#75]
Nice work with this, it is an interesting approach for routing. I have played around this evening but there are some areas I still have trouble figuring out.

I read the pre-release Medium post and that is what caused me to try it out. It makes a lot of sense when we have unique pages only. However if there are multiple levels of a path I am having trouble figuring out how to structure that.

For example let's say we have a books URL: `/books`, `/books/:id` and `/books/:id/edit` or something. For the first I want a sidebar to the left and content to right can be some statistics for all books. For the second I want the sidebar again and some statistics of a specific book as content. The last one also needs a sidebar and content is just some fields.

So in this example the three paths share some common sidebar module that we can extract and reuse. It feels a bit weird to code up three specific pages that shares a lot of the same layout code however. Also that we want some common data such as all books so we need to repeat thunk code as well.

What is a nice way to deal with this? I have tried three added route maps that all use the same `BooksPage` component. Then in that component I will do an additional `{props.page === 'BOOKS_BOOK_EDIT_PAGE' && <BookEdit bookId={4] />}` or something  but that also kind of gets weird fast.

There might be a very obvious solution I am just not seeing, I hope there is. Any suggestions for how one might deal with this nested route with shared components/layout that does not result in too much redudant code that would not be with React Router?

I am a bit lost what to title this, sorry. Hope the question is more clear.

**Comment by faceyspacey** [comment]
If I'm understanding you correctly, the *change-in-design* to support this is moving from many *"setter style"* actions to fewer *page-centric* actions, and fatter reducers.

I actually happen to discuss it in the RFR interview that went out today. There's only one code example in it, and it covers exactly what I think your question is:
https://survivejs.com/blog/redux-first-router-interview/

Also, it's covered deeper in the data fetching article that came out a few weeks ago:
https://medium.com/faceyspacey/redux-first-router-data-fetching-solving-the-80-use-case-for-async-middleware-14529606c262

Basically it boils down to this:

**Old approach with many setter actions**

```javascript
const sidebarOpen = (state = false, action = {}) => {
  switch (action.type) {
    case 'SIDEBAR_CLOSED':
      return false;
    case 'SIDEBAR_OPEN':
      return true;
    default:
      return state;
  }
}

export default sidebarOpen;
```

**New approach with fewer actions and smarter / fatter reducers:**

```javascript
const sidebarOpen = (state = false, action = {}) => {
  switch (action.type) {
    case 'HOME':
    case 'LIST':
    case 'VIDEO':
    case 'LOGIN':
      return false;
    case 'SETTINGS':
      return true;
    default:
      return state;
  }
}

export default sidebarOpen;
```

So in short, you offload the work to your reducers, and make the `sidebarOpen` reducer respond to actions for all 3 books related pages. Then in your component, display the sidebar based on this state.

Here's an example based on your actions:

```javascript
const sidebarOpen = (state = false, action = {}) => {
  switch (action.type) {
    case 'BOOKS':
    case 'BOOKS_BOOK':
    case 'BOOKS_BOOK_EDIT_PAGE':
      return true;
    case 'OTHER':
      return false;
    default:
      return state;
  }
}
```

*and component code:*

```js
import Sidebar from './Sidebar'
import Content from './Content'

const Layout = ({ sidebarOpen })) =>
    <div>
        {$sidebarOpen && <Sidebar />
        <Content />
    </div>

const mapState = ({ sidebarOpen }) => ({ sidebarOpen })
export default connect(mapState)(Layout)
```

So the main takeaway is rather than creating additional actions with type `'SIDEBAR_OPEN'` (which you'd have to send additionally in each route's `thunk` option), you get the most out of your current actions from your routesMap and, and make your reducers smarter. 

Working this will will make your app far more manageable as you won't suffer from an explosion in action count.

**Comment by lauritzsh** [comment]
Thanks for getting back so fast, I read most articles I found but the message might have escaped me. My initial approach was inspired by your `PageComponent` from [this](https://medium.com/faceyspacey/pre-release-redux-first-router-a-step-beyond-redux-little-router-cd2716576aea) article. We keep the page in the Redux store and render based on that. The example is neat because each route is its own corresponding page. I _think_ it's usually the case that `RepoComponent` would be under the `ReposComponent` since we dealing with nested route: at least that is how it is in my application and this got a lot more tricky dealing with how to render what inside other components.

So I tried the proposed here and I think it makes more sense. What I did was to make a UI reducer that will keep track of what pages to display and inner components. Now I can easily render nested routes and display components based on the route because that will update the store.

With your `sidebarOpen` reducer I feel like it would get quite hard to manage all the different route states however (in case we have ten or more different routes (where `/books` and `/books/:id` are considered two different routes)) as any other page besides BOOKS related routes would have to be added as a case (like the `case 'OTHER':` I assume).

I feel like it would make more sense to only listen for those routes that we want to match. Anything else we can simply say we do not care to render the sidebar. That would look something like this:

```javascript
const sidebarOpen = (state = false, action = {}) => {
  switch (action.type) {
    case 'BOOKS':
    case 'BOOKS_BOOK':
    case 'BOOKS_BOOK_EDIT':
      return true;
    default:
      return false;
  }
}
```

Now the problem is that _any_ other action will close the sidebar. Even if we are in the correct page. So to fix this I would just suffix _every_ route to match with a `_PAGE`. Thus we would get something like this:

```javascript
const sidebarOpen = (state = false, action = {}) => {
  if (!action.type.endsWith('_PAGE')) {
    return state;
  }

  switch (action.type) {
    case 'BOOKS_PAGE':
    case 'BOOKS_BOOK_PAGE':
    case 'BOOKS_BOOK_EDIT_PAGE':
      return true;
    default:
      return false;
  }
}
```

Now we do not have to update _every_ reducer when we add a new page to its "handle all other cases".

What I am afraid of is that this UI reducer would grow in size very quickly. So this UI reducer would not just combine its own reduceres I imagine but we could split the UI into multple pages: books, albums, users etc. Then to render a specific page we just check

```javascript
<div>
  {ui.books && <BooksComponent />}
  {ui.albums && <AlbumsComponent />}
</div>
```

and inside the `BooksComponent` we just check `ui.books.sidebarOpen` or whatever to render that one.

I have not really played a lot with middlewares but maybe this could somehow be wrapped up in a custom middleware specifically made for the app you are writing.

Is this overengineered? Am I thinking too abstract? Would appreciate any feedback on this approach as I think this makes it easier to keep track of routes, reducers and state without adding a lot of redundant information all over by sticking to so some sort of convention (in this case `_PAGE`).

I have an ugly demo with this approach that I can share but would have to clean up a bit, I will clean it if it is something you want to see.

**Comment by faceyspacey** [comment]
I'll respond in depth later but another solution is to use a selector (with or without reselect) and base the decision on a few other reducers whose state in sum indicate whether the sidebar should open.

But otherwise, yea expect it to add other actions to it. You can also just use a regex to test if they start or contain certain strings in the type.

This is the price that must be paid for time travel and less actions. Having a million actions is far more error prone for all sorts of reasons. For one, back to back dispatching of multiple actions is a perf problem. It also means u must now remember to do all these extra actions. 

Thinking how your reducer will respond given all actions makes it more resilient and extensible. It means u can add new features and not have to go around sprinkling actions. Just build your app while focusing on the core aspect of the features, and then later add a few types to a switch.

**Comment by lauritzsh** [comment]
Looking forward to the in depth answer, interested with your take on this. I forgot to add that I did not prior to this library keep any UI state in the Redux store. In my current app with React Router the sidebar is just included into the component and is only rendered based on these nested `<Route />` components so there are no need for any sort of `OPEN_SIDEBAR` or `CLOSE_SIDEBAR` action.

With this approach I definitely see a need for this and your approach to just listen for specific route actions such as `BOOKS_PAGE` is more clean than specific `OPEN_SIDEBAR`. Since I never used to have UI state in my Redux store since React Router was taking care of this, this library is a completely new approach for me and I think I have just have to get used to thinking a bit more differently.

I think I am trying to apply how I would do with React Router to Redux-first router and failing. I just have to think differently what routes mean. But how do you feel about having a specific UI reducer that combines specific page UI reducers to tell how any current route should be displayed? Anyway, looking forward to the in depth reply, hope you will include some selector examples as that sounds interesting.

**Comment by faceyspacey** [comment]
I guess my answer is pretty much the same--you just gotta keep adding actions to the reducer. I personally would do that over doing more complex string comparisons. It's more explicit. That's the thing--we dont want magic. We want explicit and to know what our app is doing at all times. Over-engineering abstractions is one of the primary lessons of the whole *React revelation*--don't do it. It causes more problems than it's worth. 

Undestanding abstractions ends up becoming harder than understanding more simpler code. That's the idea.

That's not to say there isn't some solution. E.g. making a selector that combines state from several reducers.

Another option if you really want is you could set the path to something like: `/books/*`. But that has the cost of using the same type for all segments after `/books`. You will get the value of * in `payload[0]`, I'm pretty sure. It's not a documented strategy, it just happened to work. In the future the remaining path may go into an array at `payload.parts` or something. It can contain multiple parts, i.e. if u do `(*)/(*)`. That would filled the array with 2 entries.

I'd just fill the reducer brotha. That's what I do and eliminates pitfalls surrounding magic.

**Comment by lauritzsh** [comment]
I think I will play around with this approach, I still need to wrap my head around this approach but hopefully it will click suddenly. Could you provde a selector example because I am still not sure how you would do that exactly to calculate some UI state.

Is there more to it than just doing the example below or how can selectors be used for routing nested paths?

```javascript
export const booksSidebarOpen = state =>
  state.page === "BOOKS" ||
  state.page === "BOOKS_BOOK" ||
  state.page === "BOOKS_BOOK_EDIT";
```

The issue can be closed after, think I am starting to understand where I can experiment until it clicks.

**Comment by faceyspacey** [comment]
Checkout reselect:

https://github.com/reactjs/reselect

basically you combine the states of 2+ reducers to make the `sidebarOpen` state for the whole app.

But you can only do that if other reducers in sum can indicate whether the sidebar is open. The idea is perhaps you have a states like `isUser` and `isPanel`. Then combined, you know you have a sidebar for a member area. Whereas if the user is on some faq page outside of the panel, you know there shouldn't be a sidebar.
