### ISSUE TITLE
pathToRegexp.compile import issues in node 8

### ISSUE THREAD

**Issue by kristfal** [faceyspacey/redux-first-router#79]
Hey,

really sweet project! Tons of kudos. One issue: I'm unable to match actions to routes using node 8.2.1. 

The issue seems to stem from the way `pathToRegexp.compile` is imported in node 8. My project currently requires `path-to-regexp` at the root `node_modules` level of the project, and somehow this messes up the import in `actionToPath.js`. The result is a silent error when identifying `path` in `actionToPath.js` which in turn makes all actions result in route not found. 

I can resolve the issue by require the import in the following way:

`const {compile} = require('../../node_modules/path-to-regexp');`

and then use `compile` as is to evaluate the `path`. 

I haven't issued a PR as the test suite seems to be failing in both node 6 and 8. I don't know if this way of require will break on other versions of node or further complicate stuff, so let me know if you want any more info/help to fix it.

**Comment by faceyspacey** [comment]
This is bizarre. I use 8.3 and it works fine. Are you sure it's not something else? Is it only working for me because I use webpack or babel to bundle the server?

This is the first i've heard of this issue. I dont even know what to say..

**Comment by kristfal** [comment]
I think the root cause is that my project requires an old version of `path-to-regexp` at the root `node_modules` level that doesn't include `compile`. 

When the dependency is required by `redux-first-router`, node 6 seems to pick up the sub module within the `redux-first-router` folder, but node 8 picks up the root module which returns `undefined` for `compile`. I'm also using webpack with a cookie cutter config, so doubt that is the issue.

Bizarre yes.

**Comment by faceyspacey** [comment]
its weird that these dependency management systems sometimes use different versions of packages and put them in nested node_modules folders. I'm no expert in yarn or npm and havent invested the time studying these things, but clearly it's rough around the edges and not 100% perfect.

**Comment by faceyspacey** [comment]
i mean it's weird that sometimes they *do* and sometimes they *dont*. it would be less weird to pick one way.

**Comment by faceyspacey** [comment]
but i can guess why they did it. but the point is sometimes we have no idea what's going on internally, and crazy bugs are happening externally. it's just bad for observability into what's going on.

**Comment by faceyspacey** [comment]
perhaps if in RFR the dependency was better pinned to a precise version that would solve it.

**Comment by kristfal** [comment]
After digging into it, it seems like express is requiring path-to-regexp 0.1.7, installing it in the root folder. That is the cause of this mess.

Swapped from NPM to Yarn and that resolved the issue. Closing this issue.

**Comment by faceyspacey** [comment]
excellent
