### ISSUE TITLE
Using simple <a> tags while abstracting away path structure

### ISSUE THREAD

**Issue by pelotom** [faceyspacey/redux-first-router#80]
Hi, this looks like a great library and I'm excited to use it. I find it very appealing to work with objects like

```js
{ type: 'GOTO_USER_PROFILE', payload: { userId: 1925724 } }
```

rather than specific paths. However, I want to keep my components very dumb and ignorant of actions; ideally the url prop passed into the component should be just a simple string that the component can render as e.g. `<a href={props.url}>User Profile</a>`. I want it to be the selectors' job to turn actions into urls for rendering. Is there function I can call to do that conversion without having to use the `Link` component?

**Comment by faceyspacey** [comment]
examine these 2 files in the Link package:

https://github.com/faceyspacey/redux-first-router-link/blob/master/src/toUrl.js

https://github.com/faceyspacey/redux-first-router-link/blob/master/src/handlePress.js

what ur looking for is these 2 methods exported from RFR:
- `actionToPath`
- `pathToAction`

As to why you cant/dont_want_to use the Link package, I don't know. But it's not the most complex package. I'd definitely study it cuz I'm sure there are uses cases for why you'd want to create your own.

If you're deadset on using an `<a />` tag of your own, u gotta make sure to add an `onClick` handler that calls `e.preventDefault()` and dispatches an action.

Let me know if that helps.

**Comment by pelotom** [comment]
If I don't use `e.preventDefault()`, would that just cause a spurious page refresh, or something more serious? Shouldn't navigating to the URL through a normal mechanism have the same ultimate effect as dispatching the associated action?

**Comment by faceyspacey** [comment]
if you have SSR setup on the server, you'll see the same stuff. If you want the fastest result, you need to prevent the default event so the browser doesnt change the URL. The browser can change what's shown in the URL without actually changing the page. This  is the modern way. And then within the app itself we display what will be displayed by dispatching the correct action.

I'd really *really* try to give the Link components a try. That's what we're all doing. Without understanding your use case, I'd have a hard time recommending otherwise.

**Comment by pelotom** [comment]
Maybe I'm thinking about things wrong, but the `Link` component still feels like it's intermixing logic with view concerns. I want to be able to take all of my components and render them in complete isolation with extremely simple primitive props, without any knowledge of actions. I should be able to throw any of my components into react storybook and render it without having a real app and routes backing it up. Does that make sense?

**Comment by faceyspacey** [comment]
I'd venture to say React Storybook is missing the mark in that it's a design-focused tool, and not a tool to run full fledged app with async setups, etc (note: i've been working on jus this sorta functionality).

That said, someone else in one of the issues here or in the Link component had that issue. Here it is:
https://github.com/faceyspacey/redux-first-router-link/issues/30

If you use the `shouldDispatch` prop you can block dispatching:
https://github.com/faceyspacey/redux-first-router-link/issues/30#issuecomment-320273318

That might help.

The main thing--and if you want to essentially guarantee what you want to achieve--is you gotta import `actionToPath` and `pathToAction` to handle what you need. Just give it a try by passing in the parameters it expects, as shown in the above links. It will work.

I'm going to close this issue as it belongs over in the Link package. Feel free to re-open if none of these solutions work for you. It's a little non-standard, but I'm happy to help. I'm closing shop for the day tho.

**Comment by faceyspacey** [comment]
ps. u may just have to mock it. use the webpack config to alias the Link package to a different one. storybook lets u do that.

**Comment by pelotom** [comment]
Thanks, `actionToPath` is exactly what I want!
