### ISSUE TITLE
Dispatching redirect() in onBeforeChange doesn't change the URL

### ISSUE THREAD

**Issue by salzhrani** [faceyspacey/redux-first-router#91]
I'm trying to redirect the user away from the login page if credentials before rendering the login component. It works but the URL doesn't change.

**Comment by reywright** [comment]
@salzhrani Can you create a code example? The demo on codesandbox currently redirects properly using that exact setup. 

https://codesandbox.io/s/319wqq9oo1

Take a look at options.js. Change `LOGIN` to `HOME` and click on the Admin button in the interface and you'll be taken to the home page. If you're just having issues locally, I'd recommend making sure confirming you've configured the history package correctly.

**Comment by salzhrani** [comment]
the sandbox works fine, I might have messed up. will recheck and report if there is worth reporting.

**Comment by salzhrani** [comment]
yup its my bad.
