### ISSUE TITLE
In the store, location is sometimes mutated rather than replaced

### ISSUE THREAD

**Issue by gouegd** [faceyspacey/redux-first-router#93]
demo on CodeSandbox: https://codesandbox.io/s/mz9wzojo9j

Click the 'FP' SEO-friendly link.
Then click the one I added below, "FP with query".

Result: the URL is modified (a querystring is added), an alert popup states the new location object is equal (`===`) to the previous one. However it now contains a query object.

Expected: redux states should never be mutated but replaced, so this equality check should return false.

This will cause issues, for instance,  for people relying on PureComponent and similar perf strategies.

**Comment by faceyspacey** [comment]
Cool. Next step: paste the source code that causes this problem.

**Comment by gouegd** [comment]
Couldn't find the issue in the code. I checked the error again. The boolean check was reversed 😬

**Comment by faceyspacey** [comment]
awesome sauce!
