### ISSUE TITLE
translatable paths

### ISSUE THREAD

**Issue by klis87** [faceyspacey/redux-first-router#94]
Thank you for such an awesome routing library, I am going to switch from React Router 4 :)
All in all, I think I know how to cover all cases, except for one - having translatable routes in `routesMap`:
so, instead of this:
```javascript
const routesMap = { 
  HOME: '/home'
};
```
something like this:
```javascript
const routesMap = { 
  HOME:  : {
    en: '/home', 
    de: '/haus'
  }
};
```

`en` or `de` could be part of redux `state.language` for example.
Would it be possible to achieve something like that with this library?

**Comment by faceyspacey** [comment]
Why is /:lang not an option?

**Comment by klis87** [comment]
Of course you are right, it should be like this:
```javascript
const routesMap = { 
  HOME:  : {
    en: '/:lang/home', 
    de: '/:lang/hous'
  }
};
```
But the question still remains - how to make `home` translatable?

**Comment by gouegd** [comment]
@klis87 with this approach you can check for the state's `location.payload.lang` to find out what language is accessed.

**Comment by gouegd** [comment]
@klis87 you can use a path param and check for the state's `location.payload.lang` to find out what language is accessed.
The routeMap would be like this:
```
const routesMap = { 
  HOME:  : '/:lang/home',
};
```

If you really want to have different URLs (which sounds a bit unusual to me), you could do:
```
const routesMap = { 
  HOME_EN:  '/:lang/home',
  HOME_DE: '/:lang/hous',
};
```

Then render the appropriate depending on the `location.type`

**Comment by TomsOzols** [comment]
@gouegd Just to add to Your answer - Maybe toPath/fromPath could be used to map the language specific "HOME" word.

**Comment by klis87** [comment]
@gouegd I though about language suffix like `HOME_EN`, but then in reducers we would need to handle all of those cases, for example by trimming a language before checking action type, we would also have much more possible routing action types (`number_of_languages` * `number_of_routes_per_language`).

In my opinion translatable urls could improve user experience, because no everyone knows english, but maybe it is just an overkill? Maybe prefixing url with /:lang should be enough bot for users and SEO?

But if you think this could benefit some websites, maybe we could add some additional function to each route, similar to `fromPath` and `toPath`, like `tranformUrl`?

```javascript
const homeMap = {
  en: 'home',
  de: 'hous'
};

const routesMap = { 
  HOME:  {
    path: '/:lang/{home}',  // {home} means that it could be transformed in transformUrl
    tranformUrl: (values) => {
      return {
        home: homeMap[values.lang]
      };
    }
};
```
This is just an idea. One problem I see is the following, it is easy to construct url, but how to go the other way around to know for example that `/de/hous` is `HOME` route? We would need a `reverseTransformUrl` of some kind, in the same way `fromPath` and `toPath` are working.

By the way, I introduced this `{home}` syntax because `:home` would force us to always provide `home` as part of the payload of `HOME` action, which would be really problematic, because then each static (translatable) part of url would need to be always provide in every payload. Or maybe it wouldn't be as big a deal when using action creators? Many questions... :)

**Comment by klis87** [comment]
@TomsOzols I think we cannot use `toPath` because this can transform only `:lang` part of a path.

**Comment by gouegd** [comment]
@klis87 besides the "array of paths" idea, as of today you can do this:

```
const routesMap = { 
  HOME_EN: '/:lang/home',
  HOME_DE: {
    path: '/:lang/hous',
    referTo: 'HOME_EN'
  }
};
```

Now in your reducer, instead of just using action.type, you can do something like
`type = getReference(action.type) || action.type`. That function would return the value in the map for the `referTo` field, if present (easy to code)
You can use this 'standardised' type everywhere in your conditions and only care about one version of each route type.

**Comment by klis87** [comment]
@gouegd An interesting idea. It is probably the best possible approach for now.

**Comment by klis87** [comment]
@gouegd Your array idea also is an interesting one, but instead of an array, woudn't a map or object be better? Especially for translations, if you do `['/:lang/home', '/:lang/hous']`, how could you know that `home` is in english, and `hous` is in german?

**Comment by gouegd** [comment]
@klis87 by inspecting the value of `location.payload.lang`

**Comment by klis87** [comment]
@gouegd But how this library could know which item of array to pick? Doing just `['/:lang/home', '/:lang/hous']` doesn't give us information what to do if `lang` is `en` for instance. We would still need some map, like `{ lang: { 'en': 0, 'de': 1 } }`

**Comment by klis87** [comment]
@gouegd Hardcoding would be ok I guess, so like `['/en/home', '/de/haus']`, but then, as you mentioned, we would have different problems.

> In that case, you could just hardcode the language in the path, and either rely on pathname, or perhaps add other variables to specify the language in each array item.

I am not sure what the best api could be for both path translation and optional paths parameters, so it could be the most convenient for both of those.

Maybe we should wait for @faceyspacey , as he could have some ideas.

**Comment by faceyspacey** [comment]
all these options are fine. My initial instinct is a payload param and then use it to key into a hash wherever needed. I mean that's the idiomatic obvious way. Just do that as your first draft until you find something very wrong with it. Otherwise it's likely over engineering.

But, a large number of types is an interesting option and allows you to reuse your routesMap by adding info to each route. The routesMap becomes the hash in this way, and this is also another best practices idiom with RFR. Who cares if it feels weird to have many similar routes. It makes for a lot of productivity to not have to do action dot payload dot lang everywhere. Flatter is better. The new semi fp React world is all about easy to read repetition. DRY is dead.

**Comment by klis87** [comment]
@faceyspacey Thanks. I think I will try the option with large number of types, I agree with you, a code easy to read is more important than minimizing simple repetitions (like function calls).

**Comment by faceyspacey** [comment]
Hey there, we just released optional params, regexes in paths, multi segment parameters and more. Essentially advanced path definitions:

https://github.com/faceyspacey/redux-first-router/issues/83#issuecomment-327703226

This may help your use case. For example, you can now do:

```js
const routesMap = { 
  HOME: '/(home|haus)','
};
```

Or even better:
```js
const routesMap = { 
  HOME: '/:lang(home|haus)','
};
```

Now that route will only be matched for `home` or `haus` and `payload.lang` will have the language for you.

**Comment by klis87** [comment]
@faceyspacey Thank you for this. The only thing I am not sure, how to send an action to go to `/en/home` and to `/de/haus`? For example let's imagine an action `{ type: 'HOME' }`, how router could know which alias to choose from?

**Comment by gouegd** [comment]
@klis87 you need to have a payload as well on your actions, such as:

` { type: 'HOME', payload: { lang: 'haus' } } `

**Comment by klis87** [comment]
ahh, so `:lang` refers to (home|haus)`. Thanks for this, now everything is clear.
